include('Saturations/SWB025-10/Saturations/E-SAT---3.0.ax').
fof(testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_11,conjecture,iext(uri_owl_propertyChainAxiom,uri_ex_hasUncle,sK4_testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_BNODE_l11) = true ).
