include('Saturations/SWB025-10/Saturations/E-SAT---3.0.ax').
fof(testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_4,conjecture,iext(uri_rdf_first,sK3_testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_BNODE_l22,sK1_testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_BNODE_l3) = true ).
