include('Saturations/SWB025-10/Saturations/E-SAT---3.0.ax').
fof(testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_7,conjecture,iext(uri_rdf_rest,sK4_testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_BNODE_l11,sK5_testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_BNODE_l12) = true ).
