include('Saturations/SWB025-10/Saturations/E-SAT---3.0.ax').
fof(testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_9,conjecture,iext(uri_rdf_rest,sK2_testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_BNODE_l21,sK3_testcase_premise_fullish_025_Cyclic_Dependencies_between_Complex_Properties_BNODE_l22) = true ).
