fof(maddux1_join_commutativity,conjecture,! [X0] : ! [X1] : join(X0,X1) = join(X1,X0) ).
fof(maddux2_join_associativity,conjecture,! [X0] : ! [X1] : ! [X2] : join(X0,join(X1,X2)) = join(join(X0,X1),X2) ).
fof(maddux3_a_kind_of_de_Morgan,conjecture,! [X0] : ! [X1] : X0 = join(complement(join(complement(X0),complement(X1))),complement(join(complement(X0),X1))) ).
fof(maddux4_definiton_of_meet,conjecture,! [X0] : ! [X1] : meet(X0,X1) = complement(join(complement(X0),complement(X1))) ).
fof(composition_associativity,conjecture,! [X0] : ! [X1] : ! [X2] : composition(X0,composition(X1,X2)) = composition(composition(X0,X1),X2) ).
fof(composition_identity,conjecture,! [X0] : composition(X0,one) = X0 ).
fof(composition_distributivity,conjecture,! [X0] : ! [X1] : ! [X2] : composition(join(X0,X1),X2) = join(composition(X0,X2),composition(X1,X2)) ).
fof(converse_idempotence,conjecture,! [X0] : converse(converse(X0)) = X0 ).
fof(converse_additivity,conjecture,! [X0] : ! [X1] : converse(join(X0,X1)) = join(converse(X0),converse(X1)) ).
fof(converse_multiplicativity,conjecture,! [X0] : ! [X1] : converse(composition(X0,X1)) = composition(converse(X1),converse(X0)) ).
fof(converse_cancellativity,conjecture,! [X0] : ! [X1] : join(composition(converse(X0),complement(composition(X0,X1))),complement(X1)) = complement(X1) ).
fof(def_top,conjecture,! [X0] : top = join(X0,complement(X0)) ).
fof(def_zero,conjecture,! [X0] : zero = meet(X0,complement(X0)) ).
