include('Saturations/CSR111+2/Saturations/E-SAT---3.0.ax').
fof(ax1_135,conjecture,subcollectionofwithrelationtotypefnissuingaprescriptionproductscorrectivelensprescription(c_tptpnsubcollectionofwithrelationtotypefnissuingaprescriptionproductscorrectivelensprescription_2804) ).
