fof(mp1_high_growth_rates,conjecture,! [E] : ! [S1] : ! [S2] : ! [T] : ( ( environment(E) & subpopulations(S1,S2,E,T) & greater(growth_rate(S2,T),growth_rate(S1,T)) ) => selection_favors(S2,S1,T) ) ).
fof(l3,conjecture,! [E] : ! [T] : ( ( environment(E) & subpopulations(first_movers,efficient_producers,E,T) ) => ~ decreases(difference(disbanding_rate(first_movers,T),disbanding_rate(efficient_producers,T))) ) ).
fof(mp_critical_point_means_FM_and_EP,conjecture,! [E] : ( ( environment(E) & in_environment(E,critical_point(E)) ) => subpopulations(first_movers,efficient_producers,E,critical_point(E)) ) ).
fof(mp_FM_and_EP_when_EP_appears,conjecture,! [E] : ( ( environment(E) & in_environment(E,appear(efficient_producers,E)) ) => subpopulations(first_movers,efficient_producers,E,appear(efficient_producers,E)) ) ).
fof(mp_decreasing_function,conjecture,! [E] : ! [T] : ! [To] : ( ( environment(E) & in_environment(E,To) & greater_or_equal(difference(growth_rate(first_movers,To),growth_rate(efficient_producers,To)),zero) & greater_or_equal(T,appear(efficient_producers,E)) & greater(To,T) ) => ( decreases(difference(growth_rate(first_movers,T),growth_rate(efficient_producers,T))) => greater(difference(growth_rate(first_movers,T),growth_rate(efficient_producers,T)),zero) ) ) ).
fof(mp_difference_between_founding_rates,conjecture,! [T] : ( ( decreases(difference(founding_rate(first_movers,T),founding_rate(efficient_producers,T))) & ~ decreases(difference(disbanding_rate(first_movers,T),disbanding_rate(efficient_producers,T))) ) => decreases(difference(growth_rate(first_movers,T),growth_rate(efficient_producers,T))) ) ).
fof(mp_negative_growth_rate_difference,conjecture,! [T] : ( greater(zero,difference(growth_rate(first_movers,T),growth_rate(efficient_producers,T))) <=> greater(growth_rate(efficient_producers,T),growth_rate(first_movers,T)) ) ).
fof(mp_positive_growth_rate_difference,conjecture,! [T] : ( greater(difference(growth_rate(first_movers,T),growth_rate(efficient_producers,T)),zero) <=> greater(growth_rate(first_movers,T),growth_rate(efficient_producers,T)) ) ).
fof(mp_durations_are_time_intervals,conjecture,! [E] : ! [T1] : ! [T2] : ! [T] : ( ( environment(E) & in_environment(E,T1) & in_environment(E,T2) & greater_or_equal(T2,T) & greater_or_equal(T,T1) ) => in_environment(E,T) ) ).
fof(mp_opening_time_in_duration,conjecture,! [E] : ( environment(E) => in_environment(E,start_time(E)) ) ).
fof(mp_no_FM_before_opening,conjecture,! [E] : ( environment(E) => greater_or_equal(appear(first_movers,E),start_time(E)) ) ).
fof(mp_symmetry_of_FM_and_EP,conjecture,! [E] : ! [T] : ( ( environment(E) & subpopulations(first_movers,efficient_producers,E,T) ) => subpopulations(efficient_producers,first_movers,E,T) ) ).
fof(mp_FM_and_EP_members_EP_appeared,conjecture,! [E] : ! [T] : ( ( environment(E) & subpopulations(first_movers,efficient_producers,E,T) ) => greater_or_equal(T,appear(efficient_producers,E)) ) ).
fof(mp_greater_or_equal,conjecture,! [X] : ! [Y] : ( greater_or_equal(X,Y) <=> ( greater(X,Y) | X = Y ) ) ).
fof(mp_relationship_of_growth_rates,conjecture,! [E] : ! [T] : ( ( environment(E) & subpopulations(first_movers,efficient_producers,E,T) & ~ greater(zero,difference(growth_rate(first_movers,T),growth_rate(efficient_producers,T))) ) => greater_or_equal(difference(growth_rate(first_movers,T),growth_rate(efficient_producers,T)),zero) ) ).
fof(a10,conjecture,! [E] : ! [T1] : ! [T2] : ! [T] : ( ( environment(E) & subpopulations(first_movers,efficient_producers,E,T1) & subpopulations(first_movers,efficient_producers,E,T2) & greater_or_equal(T,T1) & greater_or_equal(T2,T) ) => subpopulations(first_movers,efficient_producers,E,T) ) ).
fof(d1,conjecture,! [E] : ! [Tc] : ( ( environment(E) & Tc = critical_point(E) ) => ( ~ greater(growth_rate(efficient_producers,Tc),growth_rate(first_movers,Tc)) & ! [T] : ( ( subpopulations(first_movers,efficient_producers,E,T) & greater(T,Tc) ) => greater(growth_rate(efficient_producers,T),growth_rate(first_movers,T)) ) ) ) ).
fof(a11,conjecture,! [E] : ! [T] : ( ( environment(E) & subpopulations(first_movers,efficient_producers,E,T) ) => decreases(difference(founding_rate(first_movers,T),founding_rate(efficient_producers,T))) ) ).
fof(prove_t3,conjecture,~(! [E] : ! [T] : ( ( environment(E) & in_environment(E,critical_point(E)) & greater_or_equal(T,appear(efficient_producers,E)) & greater(critical_point(E),T) ) => selection_favors(first_movers,efficient_producers,T) ) )).
