fof(na8_1,conjecture,! [A] : ? [B] : g_true_only(A,B) | ( ? [A] : ( ? [B] : g_both(A,B) & ~ ( ? [B] : g_true_only(A,B) ) ) & ~ ( ? [A] : ! [B] : g_false_only(A,B) ) ) ).
fof(na8_2,conjecture,! [A] : ! [B] : ! [C] : ( g_false_only(A,B) | g_false_only(B,C) | g_true_only(A,C) ) | ( ? [A] : ( ? [B] : ( ? [C] : ( ( g_both(A,B) | g_both(B,C) ) & ~ g_false_only(A,B) & ~ g_false_only(B,C) & g_both(A,C) ) & ~ ( ? [C] : ( ( g_true_only(A,B) & g_true_only(B,C) & ( g_both(A,C) | g_false_only(A,C) ) ) | ( ( g_both(A,B) | g_both(B,C) ) & ~ g_false_only(A,B) & ~ g_false_only(B,C) & g_false_only(A,C) ) ) ) ) & ~ ( ? [B] : ? [C] : ( ( g_true_only(A,B) & g_true_only(B,C) & ( g_both(A,C) | g_false_only(A,C) ) ) | ( ( g_both(A,B) | g_both(B,C) ) & ~ g_false_only(A,B) & ~ g_false_only(B,C) & g_false_only(A,C) ) ) ) ) & ~ ( ? [A] : ? [B] : ? [C] : ( ( g_true_only(A,B) & g_true_only(B,C) & ( g_both(A,C) | g_false_only(A,C) ) ) | ( ( g_both(A,B) | g_both(B,C) ) & ~ g_false_only(A,B) & ~ g_false_only(B,C) & g_false_only(A,C) ) ) ) ) ).
fof(na8_3,conjecture,! [A] : g_false_only(A,A) | ( ? [A] : g_both(A,A) & ~ ( ? [A] : g_true_only(A,A) ) ) ).
fof(nc8,conjecture,~(! [A] : ! [B] : ( h_false_only(A) | h_false_only(B) | g_true_only(A,B) | g_true_only(B,A) ) | ( ? [A] : ( ? [B] : ( ( h_both(A) | h_both(B) ) & ~ h_false_only(A) & ~ h_false_only(B) & ( g_both(A,B) | g_both(B,A) ) & ~ g_true_only(A,B) & ~ g_true_only(B,A) ) & ~ ( ? [B] : ( ( h_true_only(A) & h_true_only(B) & ( ( ( g_both(A,B) | g_both(B,A) ) & ~ g_true_only(A,B) & ~ g_true_only(B,A) ) | ( g_false_only(A,B) & g_false_only(B,A) ) ) ) | ( ( h_both(A) | h_both(B) ) & ~ h_false_only(A) & ~ h_false_only(B) & g_false_only(A,B) & g_false_only(B,A) ) ) ) ) & ~ ( ? [A] : ? [B] : ( ( h_true_only(A) & h_true_only(B) & ( ( ( g_both(A,B) | g_both(B,A) ) & ~ g_true_only(A,B) & ~ g_true_only(B,A) ) | ( g_false_only(A,B) & g_false_only(B,A) ) ) ) | ( ( h_both(A) | h_both(B) ) & ~ h_false_only(A) & ~ h_false_only(B) & g_false_only(A,B) & g_false_only(B,A) ) ) ) ) )).
fof(true_only_h,conjecture,! [X_1] : ( h_true_only(X_1) <=> ( h_true(X_1) & ~ h_false(X_1) ) ) ).
fof(both_h,conjecture,! [X_1] : ( h_both(X_1) <=> ( h_true(X_1) & h_false(X_1) ) ) ).
fof(false_only_h,conjecture,! [X_1] : ( h_false_only(X_1) <=> ( h_false(X_1) & ~ h_true(X_1) ) ) ).
fof(exhaustion_h,conjecture,! [X_1] : ( h_true_only(X_1) | h_both(X_1) | h_false_only(X_1) ) ).
fof(true_only_g,conjecture,! [X_2] : ! [X_1] : ( g_true_only(X_2,X_1) <=> ( g_true(X_2,X_1) & ~ g_false(X_2,X_1) ) ) ).
fof(both_g,conjecture,! [X_2] : ! [X_1] : ( g_both(X_2,X_1) <=> ( g_true(X_2,X_1) & g_false(X_2,X_1) ) ) ).
fof(false_only_g,conjecture,! [X_2] : ! [X_1] : ( g_false_only(X_2,X_1) <=> ( g_false(X_2,X_1) & ~ g_true(X_2,X_1) ) ) ).
fof(exhaustion_g,conjecture,! [X_2] : ! [X_1] : ( g_true_only(X_2,X_1) | g_both(X_2,X_1) | g_false_only(X_2,X_1) ) ).
