fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq3(A,A,B,C) = B ).
fof(ifeq_axiom_001,conjecture,! [A] : ! [B] : ! [C] : ifeq2(A,A,B,C) = B ).
fof(ifeq_axiom_002,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(clause1,conjecture,! [U] : ! [V] : ifeq2(barrel(U,V),true,event(U,V),true) = true ).
fof(clause2,conjecture,! [U] : ! [V] : ifeq2(event(U,V),true,eventuality(U,V),true) = true ).
fof(clause3,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,thing(U,V),true) = true ).
fof(clause4,conjecture,! [U] : ! [V] : ifeq2(thing(U,V),true,singleton(U,V),true) = true ).
fof(clause5,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,specific(U,V),true) = true ).
fof(clause6,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,nonexistent(U,V),true) = true ).
fof(clause7,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,unisex(U,V),true) = true ).
fof(clause8,conjecture,! [U] : ! [V] : ifeq2(street(U,V),true,way(U,V),true) = true ).
fof(clause9,conjecture,! [U] : ! [V] : ifeq2(way(U,V),true,artifact(U,V),true) = true ).
fof(clause10,conjecture,! [U] : ! [V] : ifeq2(artifact(U,V),true,object(U,V),true) = true ).
fof(clause11,conjecture,! [U] : ! [V] : ifeq2(object(U,V),true,entity(U,V),true) = true ).
fof(clause12,conjecture,! [U] : ! [V] : ifeq2(entity(U,V),true,thing(U,V),true) = true ).
fof(clause13,conjecture,! [U] : ! [V] : ifeq2(entity(U,V),true,specific(U,V),true) = true ).
fof(clause14,conjecture,! [U] : ! [V] : ifeq2(entity(U,V),true,existent(U,V),true) = true ).
fof(clause15,conjecture,! [U] : ! [V] : ifeq2(object(U,V),true,nonliving(U,V),true) = true ).
fof(clause16,conjecture,! [U] : ! [V] : ifeq2(object(U,V),true,impartial(U,V),true) = true ).
fof(clause17,conjecture,! [U] : ! [V] : ifeq2(object(U,V),true,unisex(U,V),true) = true ).
fof(clause18,conjecture,! [U] : ! [V] : ifeq2(placename(U,V),true,relname(U,V),true) = true ).
fof(clause19,conjecture,! [U] : ! [V] : ifeq2(relname(U,V),true,relation(U,V),true) = true ).
fof(clause20,conjecture,! [U] : ! [V] : ifeq2(relation(U,V),true,abstraction(U,V),true) = true ).
fof(clause21,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,thing(U,V),true) = true ).
fof(clause22,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,nonhuman(U,V),true) = true ).
fof(clause23,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,general(U,V),true) = true ).
fof(clause24,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,unisex(U,V),true) = true ).
fof(clause25,conjecture,! [U] : ! [V] : ifeq2(hollywood_placename(U,V),true,placename(U,V),true) = true ).
fof(clause26,conjecture,! [U] : ! [V] : ifeq2(city(U,V),true,location(U,V),true) = true ).
fof(clause27,conjecture,! [U] : ! [V] : ifeq2(location(U,V),true,object(U,V),true) = true ).
fof(clause28,conjecture,! [U] : ! [V] : ifeq2(chevy(U,V),true,car(U,V),true) = true ).
fof(clause29,conjecture,! [U] : ! [V] : ifeq2(car(U,V),true,vehicle(U,V),true) = true ).
fof(clause30,conjecture,! [U] : ! [V] : ifeq2(vehicle(U,V),true,transport(U,V),true) = true ).
fof(clause31,conjecture,! [U] : ! [V] : ifeq2(transport(U,V),true,instrumentality(U,V),true) = true ).
fof(clause32,conjecture,! [U] : ! [V] : ifeq2(instrumentality(U,V),true,artifact(U,V),true) = true ).
fof(clause35,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq3(of(U,W,X),true,ifeq3(of(U,V,X),true,ifeq3(placename(U,W),true,ifeq3(placename(U,V),true,ifeq3(entity(U,X),true,W,V),V),V),V),V) = V ).
fof(clause36,conjecture,actual_world(skc5) = true ).
fof(clause37,conjecture,hollywood_placename(skc5,skc9) = true ).
fof(clause38,conjecture,placename(skc5,skc9) = true ).
fof(clause39,conjecture,chevy(skc5,skc7) = true ).
fof(clause40,conjecture,white(skc5,skc7) = true ).
fof(clause41,conjecture,dirty(skc5,skc7) = true ).
fof(clause42,conjecture,old(skc5,skc7) = true ).
fof(clause43,conjecture,barrel(skc5,skc6) = true ).
fof(clause44,conjecture,present(skc5,skc6) = true ).
fof(clause45,conjecture,event(skc5,skc6) = true ).
fof(clause46,conjecture,lonely(skc5,skc8) = true ).
fof(clause47,conjecture,street(skc5,skc8) = true ).
fof(clause48,conjecture,city(skc5,skc8) = true ).
fof(clause49,conjecture,of(skc5,skc9,skc8) = true ).
fof(clause50,conjecture,agent(skc5,skc6,skc7) = true ).
fof(clause51,conjecture,in(skc5,skc6,skc8) = true ).
fof(clause52,conjecture,down(skc5,skc6,skc8) = true ).
fof(clause33,conjecture,! [U] : ! [V] : ifeq(tuple(specific(U,V),general(U,V)),tuple(true,true),a,b) = b ).
fof(clause34,conjecture,! [U] : ! [V] : ifeq(tuple(nonexistent(U,V),existent(U,V)),tuple(true,true),a,b) = b ).
fof(goal,conjecture,a != b ).
