fof(person_1,conjecture,person(n1) ).
fof(person_2,conjecture,person(n2) ).
fof(person_3,conjecture,person(n3) ).
fof(person_4,conjecture,person(n4) ).
fof(person_5,conjecture,person(n5) ).
fof(person_6,conjecture,person(n6) ).
fof(not_equal_1_2,conjecture,not_equal(n1,n2) ).
fof(not_equal_1_3,conjecture,not_equal(n1,n3) ).
fof(not_equal_1_4,conjecture,not_equal(n1,n4) ).
fof(not_equal_1_5,conjecture,not_equal(n1,n5) ).
fof(not_equal_1_6,conjecture,not_equal(n1,n6) ).
fof(not_equal_2_1,conjecture,not_equal(n2,n1) ).
fof(not_equal_2_3,conjecture,not_equal(n2,n3) ).
fof(not_equal_2_4,conjecture,not_equal(n2,n4) ).
fof(not_equal_2_5,conjecture,not_equal(n2,n5) ).
fof(not_equal_2_6,conjecture,not_equal(n2,n6) ).
fof(not_equal_3_1,conjecture,not_equal(n3,n1) ).
fof(not_equal_3_2,conjecture,not_equal(n3,n2) ).
fof(not_equal_3_4,conjecture,not_equal(n3,n4) ).
fof(not_equal_3_5,conjecture,not_equal(n3,n5) ).
fof(not_equal_3_6,conjecture,not_equal(n3,n6) ).
fof(not_equal_4_1,conjecture,not_equal(n4,n1) ).
fof(not_equal_4_2,conjecture,not_equal(n4,n2) ).
fof(not_equal_4_3,conjecture,not_equal(n4,n3) ).
fof(not_equal_4_5,conjecture,not_equal(n4,n5) ).
fof(not_equal_4_6,conjecture,not_equal(n4,n6) ).
fof(not_equal_5_1,conjecture,not_equal(n5,n1) ).
fof(not_equal_5_2,conjecture,not_equal(n5,n2) ).
fof(not_equal_5_3,conjecture,not_equal(n5,n3) ).
fof(not_equal_5_4,conjecture,not_equal(n5,n4) ).
fof(not_equal_5_6,conjecture,not_equal(n5,n6) ).
fof(not_equal_6_1,conjecture,not_equal(n6,n1) ).
fof(not_equal_6_2,conjecture,not_equal(n6,n2) ).
fof(not_equal_6_3,conjecture,not_equal(n6,n3) ).
fof(not_equal_6_4,conjecture,not_equal(n6,n4) ).
fof(not_equal_6_5,conjecture,not_equal(n6,n5) ).
fof(familiar_or_not,conjecture,! [X] : ! [Y] : ( familiar(X,Y) | not_familiar(X,Y) | ~ person(X) | ~ person(Y) | ~ not_equal(X,Y) ) ).
fof(three_familiar,conjecture,! [X1] : ! [X2] : ! [X3] : ( ~ familiar(X1,X2) | ~ familiar(X2,X3) | ~ familiar(X3,X1) ) ).
fof(three_not_familiar,conjecture,! [X1] : ! [X2] : ! [X3] : ( ~ not_familiar(X1,X2) | ~ not_familiar(X2,X3) | ~ not_familiar(X3,X1) ) ).
