fof(axiom_1,conjecture,! [X] : not(X) = xor(X,truth) ).
fof(axiom_2,conjecture,! [X] : xor(X,falsehood) = X ).
fof(axiom_3,conjecture,! [X] : xor(X,X) = falsehood ).
fof(axiom_4,conjecture,! [X] : and_star(X,truth) = X ).
fof(axiom_5,conjecture,! [X] : and_star(X,falsehood) = falsehood ).
fof(axiom_6,conjecture,! [X] : and_star(xor(truth,X),X) = falsehood ).
fof(axiom_7,conjecture,! [X] : ! [Y] : xor(X,xor(truth,Y)) = xor(xor(X,truth),Y) ).
fof(axiom_8,conjecture,! [X] : ! [Y] : and_star(xor(and_star(xor(truth,X),Y),truth),Y) = and_star(xor(and_star(xor(truth,Y),X),truth),X) ).
fof(or_definition,conjecture,! [X] : ! [Y] : or(X,Y) = implies(not(X),Y) ).
fof(or_associativity,conjecture,! [X] : ! [Y] : ! [Z] : or(or(X,Y),Z) = or(X,or(Y,Z)) ).
fof(or_commutativity,conjecture,! [X] : ! [Y] : or(X,Y) = or(Y,X) ).
fof(and_definition,conjecture,! [X] : ! [Y] : and(X,Y) = not(or(not(X),not(Y))) ).
fof(and_associativity,conjecture,! [X] : ! [Y] : ! [Z] : and(and(X,Y),Z) = and(X,and(Y,Z)) ).
fof(and_commutativity,conjecture,! [X] : ! [Y] : and(X,Y) = and(Y,X) ).
fof(xor_definition,conjecture,! [X] : ! [Y] : xor(X,Y) = or(and(X,not(Y)),and(not(X),Y)) ).
fof(xor_commutativity,conjecture,! [X] : ! [Y] : xor(X,Y) = xor(Y,X) ).
fof(and_star_definition,conjecture,! [X] : ! [Y] : and_star(X,Y) = not(or(not(X),not(Y))) ).
fof(and_star_associativity,conjecture,! [X] : ! [Y] : ! [Z] : and_star(and_star(X,Y),Z) = and_star(X,and_star(Y,Z)) ).
fof(and_star_commutativity,conjecture,! [X] : ! [Y] : and_star(X,Y) = and_star(Y,X) ).
fof(false_definition,conjecture,not(truth) = falsehood ).
