fof(ax1,conjecture,! [U] : ( fellow(U) => man(U) ) ).
fof(ax2,conjecture,! [U] : ( man(U) => human(U) ) ).
fof(ax3,conjecture,! [U] : ( human(U) => organism(U) ) ).
fof(ax4,conjecture,! [U] : ( organism(U) => entity(U) ) ).
fof(ax5,conjecture,! [U] : ( organism(U) => ~ object(U) ) ).
fof(ax6,conjecture,! [U] : ( front(U) => nonhuman(U) ) ).
fof(ax7,conjecture,! [U] : ( seat(U) => furniture(U) ) ).
fof(ax8,conjecture,! [U] : ( furniture(U) => instrumentality(U) ) ).
fof(ax9,conjecture,! [U] : ( furniture(U) => ~ transport(U) ) ).
fof(ax10,conjecture,! [U] : ( street(U) => way(U) ) ).
fof(ax11,conjecture,! [U] : ( way(U) => artifact(U) ) ).
fof(ax12,conjecture,! [U] : ( way(U) => ~ instrumentality(U) ) ).
fof(ax13,conjecture,! [U] : ( chevy(U) => car(U) ) ).
fof(ax14,conjecture,! [U] : ( car(U) => vehicle(U) ) ).
fof(ax15,conjecture,! [U] : ( vehicle(U) => transport(U) ) ).
fof(ax16,conjecture,! [U] : ( transport(U) => instrumentality(U) ) ).
fof(ax17,conjecture,! [U] : ( instrumentality(U) => artifact(U) ) ).
fof(ax18,conjecture,! [U] : ( artifact(U) => object(U) ) ).
fof(ax19,conjecture,! [U] : ( artifact(U) => ~ location(U) ) ).
fof(ax20,conjecture,! [U] : ( event(U) => eventuality(U) ) ).
fof(ax21,conjecture,! [U] : ( hollywood(U) => city(U) ) ).
fof(ax22,conjecture,! [U] : ( city(U) => location(U) ) ).
fof(ax23,conjecture,! [U] : ( location(U) => object(U) ) ).
fof(ax24,conjecture,! [U] : ( object(U) => entity(U) ) ).
fof(ax25,conjecture,! [U] : ( old(U) => ~ new(U) ) ).
fof(ax26,conjecture,! [U] : ( eventuality(U) => ~ entity(U) ) ).
fof(ax27,conjecture,! [U] : ( abstraction(U) => ~ entity(U) ) ).
fof(ax28,conjecture,! [U] : ( abstraction(U) => ~ eventuality(U) ) ).
fof(ax29,conjecture,! [U] : ( male(U) => ~ female(U) ) ).
fof(ax30,conjecture,! [U] : ( man(U) => ~ woman(U) ) ).
fof(ax31,conjecture,! [U] : ( man(U) => male(U) ) ).
fof(ax32,conjecture,! [U] : ( male(U) => human(U) ) ).
fof(ax33,conjecture,! [U] : ( female(U) => human(U) ) ).
fof(ax34,conjecture,! [U] : ( woman(U) => female(U) ) ).
fof(ax35,conjecture,! [U] : ( drs(U) <=> proposition(U) ) ).
fof(ax36,conjecture,! [U] : ( nonhuman(U) => entity(U) ) ).
fof(ax37,conjecture,! [U] : ( human(U) => ~ nonhuman(U) ) ).
fof(ax38,conjecture,! [U] : ! [V] : ! [W] : ( ( have(U,V,W) & human(V) ) <=> ( owner(V) & of(V,W) ) ) ).
fof(ax39,conjecture,! [U] : ! [V] : ! [W] : ( ( have(U,V,W) & nonhuman(V) & nonhuman(W) ) => partof(W,V) ) ).
fof(ax40,conjecture,! [U] : ! [V] : ! [W] : ( ( event(U) & have(U,V,W) ) => of(V,W) ) ).
fof(ax41,conjecture,! [U] : ! [V] : ( of(V,U) => ? [W] : ( event(W) & have(W,U,V) ) ) ).
fof(ax42,conjecture,! [U] : ! [V] : ! [W] : ( ( partof(U,V) & partof(U,W) ) => V = W ) ).
fof(co1,conjecture,~(! [U] : ! [V] : ! [W] : ! [X] : ! [Y] : ! [Z] : ! [X1] : ! [X3] : ! [X4] : ( ( seat(U) & furniture(U) & front(U) & hollywood(V) & city(V) & event(W) & street(X) & way(X) & lonely(X) & chevy(Y) & car(Y) & white(Y) & dirty(Y) & old(Y) & barrel(W,Y) & down(W,X) & in(W,V) & fellow(Z) & man(Z) & young(Z) & fellow(X1) & man(X1) & young(X1) & Z = X3 & in(X3,U) & X1 = X4 & in(X4,U) ) => Z = X1 ) )).
