#!/bin/tcsh

unset noglob
cd Problems
foreach dir ( * )
    echo $dir
    foreach sat ($dir/Saturations/*)
        set satname=`basename $sat .ax`
        mkdir $dir/VerificationProblems/$satname
        set noglob
        foreach line ("`cat $dir/$dir.p`")
            set formula=`echo $line | sed -e 's/^...(\([^,]*\),.*/\1/'`
            echo "$dir $formula $sat"
            echo "include('Problems/$dir/Saturations/`basename $sat`')." >! $dir/VerificationProblems/$satname/${formula}.p
            echo $line >> $dir/VerificationProblems/$satname/${formula}.p
        end
        unset noglob
    end
end
