fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq4(A,A,B,C) = B ).
fof(ifeq_axiom_001,conjecture,! [A] : ! [B] : ! [C] : ifeq3(A,A,B,C) = B ).
fof(ifeq_axiom_002,conjecture,! [A] : ! [B] : ! [C] : ifeq2(A,A,B,C) = B ).
fof(ifeq_axiom_003,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(clause1,conjecture,! [U] : ! [V] : ifeq3(dance(U,V),true,event(U,V),true) = true ).
fof(clause2,conjecture,! [U] : ! [V] : ifeq3(event(U,V),true,eventuality(U,V),true) = true ).
fof(clause3,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,thing(U,V),true) = true ).
fof(clause4,conjecture,! [U] : ! [V] : ifeq3(thing(U,V),true,singleton(U,V),true) = true ).
fof(clause5,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,specific(U,V),true) = true ).
fof(clause6,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,nonexistent(U,V),true) = true ).
fof(clause7,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,unisex(U,V),true) = true ).
fof(clause8,conjecture,! [U] : ! [V] : ifeq3(desire_want(U,V),true,event(U,V),true) = true ).
fof(clause9,conjecture,! [U] : ! [V] : ifeq3(proposition(U,V),true,relation(U,V),true) = true ).
fof(clause10,conjecture,! [U] : ! [V] : ifeq3(relation(U,V),true,abstraction(U,V),true) = true ).
fof(clause11,conjecture,! [U] : ! [V] : ifeq3(abstraction(U,V),true,thing(U,V),true) = true ).
fof(clause12,conjecture,! [U] : ! [V] : ifeq3(abstraction(U,V),true,nonhuman(U,V),true) = true ).
fof(clause13,conjecture,! [U] : ! [V] : ifeq3(abstraction(U,V),true,general(U,V),true) = true ).
fof(clause14,conjecture,! [U] : ! [V] : ifeq3(abstraction(U,V),true,unisex(U,V),true) = true ).
fof(clause15,conjecture,! [U] : ! [V] : ifeq3(forename(U,V),true,relname(U,V),true) = true ).
fof(clause16,conjecture,! [U] : ! [V] : ifeq3(relname(U,V),true,relation(U,V),true) = true ).
fof(clause17,conjecture,! [U] : ! [V] : ifeq3(mia_forename(U,V),true,forename(U,V),true) = true ).
fof(clause18,conjecture,! [U] : ! [V] : ifeq3(woman(U,V),true,human_person(U,V),true) = true ).
fof(clause19,conjecture,! [U] : ! [V] : ifeq3(human_person(U,V),true,organism(U,V),true) = true ).
fof(clause20,conjecture,! [U] : ! [V] : ifeq3(organism(U,V),true,entity(U,V),true) = true ).
fof(clause21,conjecture,! [U] : ! [V] : ifeq3(entity(U,V),true,thing(U,V),true) = true ).
fof(clause22,conjecture,! [U] : ! [V] : ifeq3(entity(U,V),true,specific(U,V),true) = true ).
fof(clause23,conjecture,! [U] : ! [V] : ifeq3(entity(U,V),true,existent(U,V),true) = true ).
fof(clause24,conjecture,! [U] : ! [V] : ifeq3(organism(U,V),true,impartial(U,V),true) = true ).
fof(clause25,conjecture,! [U] : ! [V] : ifeq3(organism(U,V),true,living(U,V),true) = true ).
fof(clause26,conjecture,! [U] : ! [V] : ifeq3(human_person(U,V),true,human(U,V),true) = true ).
fof(clause27,conjecture,! [U] : ! [V] : ifeq3(human_person(U,V),true,animate(U,V),true) = true ).
fof(clause28,conjecture,! [U] : ! [V] : ifeq3(woman(U,V),true,female(U,V),true) = true ).
fof(clause29,conjecture,! [U] : ! [V] : ifeq3(vincent_forename(U,V),true,forename(U,V),true) = true ).
fof(clause30,conjecture,! [U] : ! [V] : ifeq3(man(U,V),true,human_person(U,V),true) = true ).
fof(clause31,conjecture,! [U] : ! [V] : ifeq3(man(U,V),true,male(U,V),true) = true ).
fof(clause38,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(dance(U,W),true,dance(V,W),true),true) = true ).
fof(clause39,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(event(U,W),true,event(V,W),true),true) = true ).
fof(clause40,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(eventuality(U,W),true,eventuality(V,W),true),true) = true ).
fof(clause41,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(thing(U,W),true,thing(V,W),true),true) = true ).
fof(clause42,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(singleton(U,W),true,singleton(V,W),true),true) = true ).
fof(clause43,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(specific(U,W),true,specific(V,W),true),true) = true ).
fof(clause44,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(nonexistent(U,W),true,nonexistent(V,W),true),true) = true ).
fof(clause45,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(unisex(U,W),true,unisex(V,W),true),true) = true ).
fof(clause46,conjecture,! [U] : ! [W] : ! [V] : ifeq3(present(U,W),true,ifeq3(accessible_world(U,V),true,present(V,W),true),true) = true ).
fof(clause47,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(desire_want(U,W),true,desire_want(V,W),true),true) = true ).
fof(clause48,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(proposition(U,W),true,proposition(V,W),true),true) = true ).
fof(clause49,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(relation(U,W),true,relation(V,W),true),true) = true ).
fof(clause50,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(abstraction(U,W),true,abstraction(V,W),true),true) = true ).
fof(clause51,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(nonhuman(U,W),true,nonhuman(V,W),true),true) = true ).
fof(clause52,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(general(U,W),true,general(V,W),true),true) = true ).
fof(clause53,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(forename(U,W),true,forename(V,W),true),true) = true ).
fof(clause54,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(relname(U,W),true,relname(V,W),true),true) = true ).
fof(clause55,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(mia_forename(U,W),true,mia_forename(V,W),true),true) = true ).
fof(clause56,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(woman(U,W),true,woman(V,W),true),true) = true ).
fof(clause57,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(human_person(U,W),true,human_person(V,W),true),true) = true ).
fof(clause58,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(organism(U,W),true,organism(V,W),true),true) = true ).
fof(clause59,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(entity(U,W),true,entity(V,W),true),true) = true ).
fof(clause60,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(existent(U,W),true,existent(V,W),true),true) = true ).
fof(clause61,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(impartial(U,W),true,impartial(V,W),true),true) = true ).
fof(clause62,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(living(U,W),true,living(V,W),true),true) = true ).
fof(clause63,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(human(U,W),true,human(V,W),true),true) = true ).
fof(clause64,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(animate(U,W),true,animate(V,W),true),true) = true ).
fof(clause65,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(female(U,W),true,female(V,W),true),true) = true ).
fof(clause66,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(vincent_forename(U,W),true,vincent_forename(V,W),true),true) = true ).
fof(clause67,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(man(U,W),true,man(V,W),true),true) = true ).
fof(clause68,conjecture,! [U] : ! [V] : ! [W] : ifeq3(accessible_world(U,V),true,ifeq3(male(U,W),true,male(V,W),true),true) = true ).
fof(clause69,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq3(agent(U,W,X),true,ifeq3(accessible_world(U,V),true,agent(V,W,X),true),true) = true ).
fof(clause70,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq3(theme(U,W,X),true,ifeq3(accessible_world(U,V),true,theme(V,W,X),true),true) = true ).
fof(clause71,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq3(of(U,W,X),true,ifeq3(accessible_world(U,V),true,of(V,W,X),true),true) = true ).
fof(clause72,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq4(of(U,W,X),true,ifeq4(of(U,V,X),true,ifeq4(entity(U,X),true,ifeq4(forename(U,W),true,ifeq4(forename(U,V),true,W,V),V),V),V),V) = V ).
fof(clause73,conjecture,! [U] : ! [Y] : ! [X] : ! [V] : ! [W] : ifeq4(theme(U,Y,X),true,ifeq4(theme(U,V,W),true,ifeq4(proposition(U,X),true,ifeq4(proposition(U,W),true,ifeq4(desire_want(U,Y),true,ifeq4(desire_want(U,V),true,X,W),W),W),W),W),W) = W ).
fof(clause74,conjecture,actual_world(skc8) = true ).
fof(clause75,conjecture,man(skc8,skc15) = true ).
fof(clause76,conjecture,event(skc10,skc13) = true ).
fof(clause77,conjecture,woman(skc8,skc12) = true ).
fof(clause78,conjecture,present(skc10,skc13) = true ).
fof(clause79,conjecture,dance(skc10,skc13) = true ).
fof(clause80,conjecture,forename(skc8,skc11) = true ).
fof(clause81,conjecture,mia_forename(skc8,skc11) = true ).
fof(clause82,conjecture,proposition(skc8,skc10) = true ).
fof(clause83,conjecture,accessible_world(skc8,skc10) = true ).
fof(clause84,conjecture,desire_want(skc8,skc9) = true ).
fof(clause85,conjecture,present(skc8,skc9) = true ).
fof(clause86,conjecture,forename(skc8,skc14) = true ).
fof(clause87,conjecture,vincent_forename(skc8,skc14) = true ).
fof(clause88,conjecture,of(skc8,skc14,skc15) = true ).
fof(clause89,conjecture,of(skc8,skc11,skc12) = true ).
fof(clause90,conjecture,agent(skc8,skc9,skc12) = true ).
fof(clause91,conjecture,agent(skc10,skc13,skc12) = true ).
fof(clause92,conjecture,theme(skc8,skc9,skc10) = true ).
fof(clause32,conjecture,! [U] : ! [V] : ifeq2(tuple2(unisex(U,V),male(U,V)),tuple2(true,true),a,b) = b ).
fof(clause33,conjecture,! [U] : ! [V] : ifeq2(tuple2(unisex(U,V),female(U,V)),tuple2(true,true),a,b) = b ).
fof(clause34,conjecture,! [U] : ! [V] : ifeq2(tuple2(specific(U,V),general(U,V)),tuple2(true,true),a,b) = b ).
fof(clause35,conjecture,! [U] : ! [V] : ifeq2(tuple2(nonhuman(U,V),human(U,V)),tuple2(true,true),a,b) = b ).
fof(clause36,conjecture,! [U] : ! [V] : ifeq2(tuple2(female(U,V),male(U,V)),tuple2(true,true),a,b) = b ).
fof(clause37,conjecture,! [U] : ! [V] : ifeq2(tuple2(nonexistent(U,V),existent(U,V)),tuple2(true,true),a,b) = b ).
fof(clause93,conjecture,! [V] : ! [W] : ! [U] : ifeq(tuple(dance(V,W),event(V,W),desire_want(skc8,U),proposition(skc8,V),accessible_world(skc8,V),present(V,W),present(skc8,U),agent(V,W,skc15),agent(skc8,U,skc15),theme(skc8,U,V)),tuple(true,true,true,true,true,true,true,true,true,true),a,b) = b ).
fof(goal,conjecture,a != b ).
