fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(n0_and_n1_reflexive_1,conjecture,equalish(n0,n0) = true ).
fof(n0_and_n1_reflexive,conjecture,equalish(n1,n1) = true ).
fof(n0_equal_n1,conjecture,ifeq(equalish(n0,n1),true,goal,true) = true ).
fof(n1_equal_n0,conjecture,ifeq(equalish(n1,n0),true,goal,true) = true ).
fof(relation_exists,conjecture,! [E] : ! [D] : ! [C] : ! [B] : ! [A] : ifeq(equalish(E,E),true,ifeq(equalish(D,D),true,ifeq(equalish(C,C),true,ifeq(equalish(B,B),true,ifeq(equalish(A,A),true,f(A,B,C,D,E,sK1_relation_exists_F(A,B,C,D,E)),true),true),true),true),true) = true ).
fof(relation_injective_4,conjecture,! [F] : ! [G] : ! [H] : ! [I] : ! [J] : ! [K] : ! [A] : ! [B] : ! [C] : ! [D] : ! [E] : ifeq(f(F,G,H,I,J,K),true,ifeq(f(A,B,C,D,E,K),true,equalish(E,J),true),true) = true ).
fof(relation_injective_3,conjecture,! [F] : ! [G] : ! [H] : ! [I] : ! [J] : ! [K] : ! [A] : ! [B] : ! [C] : ! [D] : ! [E] : ifeq(f(F,G,H,I,J,K),true,ifeq(f(A,B,C,D,E,K),true,equalish(D,I),true),true) = true ).
fof(relation_injective_2,conjecture,! [F] : ! [G] : ! [H] : ! [I] : ! [J] : ! [K] : ! [A] : ! [B] : ! [C] : ! [D] : ! [E] : ifeq(f(F,G,H,I,J,K),true,ifeq(f(A,B,C,D,E,K),true,equalish(C,H),true),true) = true ).
fof(relation_injective_1,conjecture,! [F] : ! [G] : ! [H] : ! [I] : ! [J] : ! [K] : ! [A] : ! [B] : ! [C] : ! [D] : ! [E] : ifeq(f(F,G,H,I,J,K),true,ifeq(f(A,B,C,D,E,K),true,equalish(B,G),true),true) = true ).
fof(relation_injective,conjecture,! [F] : ! [G] : ! [H] : ! [I] : ! [J] : ! [K] : ! [A] : ! [B] : ! [C] : ! [D] : ! [E] : ifeq(f(F,G,H,I,J,K),true,ifeq(f(A,B,C,D,E,K),true,equalish(A,F),true),true) = true ).
fof(goal_to_be_proved,conjecture,goal != true ).
