fof(ax1,conjecture,! [U] : ! [V] : ( woman(U,V) => female(U,V) ) ).
fof(ax2,conjecture,! [U] : ! [V] : ( human_person(U,V) => animate(U,V) ) ).
fof(ax3,conjecture,! [U] : ! [V] : ( human_person(U,V) => human(U,V) ) ).
fof(ax4,conjecture,! [U] : ! [V] : ( organism(U,V) => living(U,V) ) ).
fof(ax5,conjecture,! [U] : ! [V] : ( organism(U,V) => impartial(U,V) ) ).
fof(ax6,conjecture,! [U] : ! [V] : ( organism(U,V) => entity(U,V) ) ).
fof(ax7,conjecture,! [U] : ! [V] : ( human_person(U,V) => organism(U,V) ) ).
fof(ax8,conjecture,! [U] : ! [V] : ( woman(U,V) => human_person(U,V) ) ).
fof(ax9,conjecture,! [U] : ! [V] : ( mia_forename(U,V) => forename(U,V) ) ).
fof(ax10,conjecture,! [U] : ! [V] : ( abstraction(U,V) => unisex(U,V) ) ).
fof(ax11,conjecture,! [U] : ! [V] : ( abstraction(U,V) => general(U,V) ) ).
fof(ax12,conjecture,! [U] : ! [V] : ( abstraction(U,V) => nonhuman(U,V) ) ).
fof(ax13,conjecture,! [U] : ! [V] : ( abstraction(U,V) => thing(U,V) ) ).
fof(ax14,conjecture,! [U] : ! [V] : ( relation(U,V) => abstraction(U,V) ) ).
fof(ax15,conjecture,! [U] : ! [V] : ( relname(U,V) => relation(U,V) ) ).
fof(ax16,conjecture,! [U] : ! [V] : ( forename(U,V) => relname(U,V) ) ).
fof(ax17,conjecture,! [U] : ! [V] : ( object(U,V) => unisex(U,V) ) ).
fof(ax18,conjecture,! [U] : ! [V] : ( object(U,V) => impartial(U,V) ) ).
fof(ax19,conjecture,! [U] : ! [V] : ( object(U,V) => nonliving(U,V) ) ).
fof(ax20,conjecture,! [U] : ! [V] : ( entity(U,V) => existent(U,V) ) ).
fof(ax21,conjecture,! [U] : ! [V] : ( entity(U,V) => specific(U,V) ) ).
fof(ax22,conjecture,! [U] : ! [V] : ( entity(U,V) => thing(U,V) ) ).
fof(ax23,conjecture,! [U] : ! [V] : ( object(U,V) => entity(U,V) ) ).
fof(ax24,conjecture,! [U] : ! [V] : ( substance_matter(U,V) => object(U,V) ) ).
fof(ax25,conjecture,! [U] : ! [V] : ( food(U,V) => substance_matter(U,V) ) ).
fof(ax26,conjecture,! [U] : ! [V] : ( beverage(U,V) => food(U,V) ) ).
fof(ax27,conjecture,! [U] : ! [V] : ( shake_beverage(U,V) => beverage(U,V) ) ).
fof(ax28,conjecture,! [U] : ! [V] : ( order(U,V) => event(U,V) ) ).
fof(ax29,conjecture,! [U] : ! [V] : ( eventuality(U,V) => unisex(U,V) ) ).
fof(ax30,conjecture,! [U] : ! [V] : ( eventuality(U,V) => nonexistent(U,V) ) ).
fof(ax31,conjecture,! [U] : ! [V] : ( eventuality(U,V) => specific(U,V) ) ).
fof(ax32,conjecture,! [U] : ! [V] : ( thing(U,V) => singleton(U,V) ) ).
fof(ax33,conjecture,! [U] : ! [V] : ( eventuality(U,V) => thing(U,V) ) ).
fof(ax34,conjecture,! [U] : ! [V] : ( event(U,V) => eventuality(U,V) ) ).
fof(ax35,conjecture,! [U] : ! [V] : ( act(U,V) => event(U,V) ) ).
fof(ax36,conjecture,! [U] : ! [V] : ( order(U,V) => act(U,V) ) ).
fof(ax37,conjecture,! [U] : ! [V] : ( animate(U,V) => ~ nonliving(U,V) ) ).
fof(ax38,conjecture,! [U] : ! [V] : ( existent(U,V) => ~ nonexistent(U,V) ) ).
fof(ax39,conjecture,! [U] : ! [V] : ( nonhuman(U,V) => ~ human(U,V) ) ).
fof(ax40,conjecture,! [U] : ! [V] : ( nonliving(U,V) => ~ living(U,V) ) ).
fof(ax41,conjecture,! [U] : ! [V] : ( specific(U,V) => ~ general(U,V) ) ).
fof(ax42,conjecture,! [U] : ! [V] : ( unisex(U,V) => ~ female(U,V) ) ).
fof(ax43,conjecture,! [U] : ! [V] : ! [W] : ( ( entity(U,V) & forename(U,W) & of(U,W,V) ) => ~ ( ? [X] : ( forename(U,X) & X != W & of(U,X,V) ) ) ) ).
fof(ax44,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ( ( nonreflexive(U,V) & agent(U,V,W) & patient(U,V,X) ) => W != X ) ).
fof(co1,conjecture,~(~ ( ? [U] : ( actual_world(U) & ? [V] : ? [W] : ? [X] : ? [Y] : ( of(U,W,V) & woman(U,V) & mia_forename(U,W) & forename(U,W) & shake_beverage(U,X) & event(U,Y) & agent(U,Y,V) & patient(U,Y,X) & past(U,Y) & nonreflexive(U,Y) & order(U,Y) ) ) ) )).
