fof(left_identity,conjecture,! [X] : add(additive_identity,X) = X ).
fof(left_additive_inverse,conjecture,! [X] : add(additive_inverse(X),X) = additive_identity ).
fof(distribute1,conjecture,! [X] : ! [Y] : ! [Z] : multiply(X,add(Y,Z)) = add(multiply(X,Y),multiply(X,Z)) ).
fof(distribute2,conjecture,! [X] : ! [Y] : ! [Z] : multiply(add(X,Y),Z) = add(multiply(X,Z),multiply(Y,Z)) ).
fof(additive_inverse_identity,conjecture,additive_inverse(additive_identity) = additive_identity ).
fof(additive_inverse_additive_inverse,conjecture,! [X] : additive_inverse(additive_inverse(X)) = X ).
fof(multiply_additive_id1,conjecture,! [X] : multiply(X,additive_identity) = additive_identity ).
fof(multiply_additive_id2,conjecture,! [X] : multiply(additive_identity,X) = additive_identity ).
fof(distribute_additive_inverse,conjecture,! [X] : ! [Y] : additive_inverse(add(X,Y)) = add(additive_inverse(X),additive_inverse(Y)) ).
fof(multiply_additive_inverse1,conjecture,! [X] : ! [Y] : multiply(X,additive_inverse(Y)) = additive_inverse(multiply(X,Y)) ).
fof(multiply_additive_inverse2,conjecture,! [X] : ! [Y] : multiply(additive_inverse(X),Y) = additive_inverse(multiply(X,Y)) ).
fof(associative_addition,conjecture,! [X] : ! [Y] : ! [Z] : add(add(X,Y),Z) = add(X,add(Y,Z)) ).
fof(commutative_addition,conjecture,! [X] : ! [Y] : add(X,Y) = add(Y,X) ).
fof(associative_multiplication,conjecture,! [X] : ! [Y] : ! [Z] : multiply(multiply(X,Y),Z) = multiply(X,multiply(Y,Z)) ).
