include('Saturations/SWB024-10/Saturations/iProver-SAT---3.7.ax').
fof(testcase_premise_fullish_024_Cardinality_Restrictions_on_Complex_Properties_6,conjecture,iext(uri_owl_onProperty,sK1_testcase_premise_fullish_024_Cardinality_Restrictions_on_Complex_Properties_BNODE_z,uri_ex_hasAncestor) = true ).
