fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(simple_iext_property,conjecture,! [P] : ! [S] : ! [O] : ifeq(iext(P,S,O),true,ip(P),true) = true ).
fof(simple_ir,conjecture,! [X] : ir(X) = true ).
fof(simple_lv,conjecture,! [X] : ifeq(lv(X),true,ir(X),true) = true ).
fof(rdf_collection_first_type,conjecture,iext(uri_rdf_type,uri_rdf_first,uri_rdf_Property) = true ).
fof(rdf_collection_nil_type,conjecture,iext(uri_rdf_type,uri_rdf_nil,uri_rdf_List) = true ).
fof(rdf_collection_rest_type,conjecture,iext(uri_rdf_type,uri_rdf_rest,uri_rdf_Property) = true ).
fof(rdf_container_n_type_001,conjecture,iext(uri_rdf_type,uri_rdf__1,uri_rdf_Property) = true ).
fof(rdf_container_n_type_002,conjecture,iext(uri_rdf_type,uri_rdf__2,uri_rdf_Property) = true ).
fof(rdf_container_n_type_003,conjecture,iext(uri_rdf_type,uri_rdf__3,uri_rdf_Property) = true ).
fof(rdf_reification_object_type,conjecture,iext(uri_rdf_type,uri_rdf_object,uri_rdf_Property) = true ).
fof(rdf_reification_predicate_type,conjecture,iext(uri_rdf_type,uri_rdf_value,uri_rdf_Property) = true ).
fof(rdf_reification_subject_type,conjecture,iext(uri_rdf_type,uri_rdf_subject,uri_rdf_Property) = true ).
fof(rdf_type_ip_1,conjecture,! [P] : ifeq(ip(P),true,iext(uri_rdf_type,P,uri_rdf_Property),true) = true ).
fof(rdf_type_ip,conjecture,! [P] : ifeq(iext(uri_rdf_type,P,uri_rdf_Property),true,ip(P),true) = true ).
fof(rdf_type_type,conjecture,iext(uri_rdf_type,uri_rdf_type,uri_rdf_Property) = true ).
fof(rdf_value_type,conjecture,iext(uri_rdf_type,uri_rdf_type,uri_rdf_Property) = true ).
fof(rdfs_annotation_comment_domain,conjecture,iext(uri_rdfs_domain,uri_rdfs_comment,uri_rdfs_Resource) = true ).
fof(rdfs_annotation_comment_range,conjecture,iext(uri_rdfs_range,uri_rdfs_comment,uri_rdfs_Literal) = true ).
fof(rdfs_annotation_isdefinedby_domain,conjecture,iext(uri_rdfs_domain,uri_rdfs_isDefinedBy,uri_rdfs_Resource) = true ).
fof(rdfs_annotation_isdefinedby_range,conjecture,iext(uri_rdfs_range,uri_rdfs_isDefinedBy,uri_rdfs_Resource) = true ).
fof(rdfs_annotation_isdefinedby_sub,conjecture,iext(uri_rdfs_subPropertyOf,uri_rdfs_isDefinedBy,uri_rdfs_seeAlso) = true ).
fof(rdfs_annotation_label_domain,conjecture,iext(uri_rdfs_domain,uri_rdfs_label,uri_rdfs_Resource) = true ).
fof(rdfs_annotation_label_range,conjecture,iext(uri_rdfs_range,uri_rdfs_label,uri_rdfs_Literal) = true ).
fof(rdfs_annotation_seealso_domain,conjecture,iext(uri_rdfs_domain,uri_rdfs_seeAlso,uri_rdfs_Resource) = true ).
fof(rdfs_annotation_seealso_range,conjecture,iext(uri_rdfs_range,uri_rdfs_seeAlso,uri_rdfs_Resource) = true ).
fof(rdfs_cext_def_1,conjecture,! [C] : ! [X] : ifeq(icext(C,X),true,iext(uri_rdf_type,X,C),true) = true ).
fof(rdfs_cext_def,conjecture,! [X] : ! [C] : ifeq(iext(uri_rdf_type,X,C),true,icext(C,X),true) = true ).
fof(rdfs_class_instsub_resource,conjecture,! [C] : ifeq(ic(C),true,iext(uri_rdfs_subClassOf,C,uri_rdfs_Resource),true) = true ).
fof(rdfs_collection_first_domain,conjecture,iext(uri_rdfs_domain,uri_rdf_first,uri_rdf_List) = true ).
fof(rdfs_collection_first_range,conjecture,iext(uri_rdfs_range,uri_rdf_first,uri_rdfs_Resource) = true ).
fof(rdfs_collection_rest_domain,conjecture,iext(uri_rdfs_domain,uri_rdf_rest,uri_rdf_List) = true ).
fof(rdfs_collection_rest_range,conjecture,iext(uri_rdfs_range,uri_rdf_rest,uri_rdf_List) = true ).
fof(rdfs_container_alt_sub,conjecture,iext(uri_rdfs_subClassOf,uri_rdf_Alt,uri_rdfs_Container) = true ).
fof(rdfs_container_bag_sub,conjecture,iext(uri_rdfs_subClassOf,uri_rdf_Bag,uri_rdfs_Container) = true ).
fof(rdfs_container_containermembershipproperty_instsub_member,conjecture,! [P] : ifeq(icext(uri_rdfs_ContainerMembershipProperty,P),true,iext(uri_rdfs_subPropertyOf,P,uri_rdfs_member),true) = true ).
fof(rdfs_container_containermembershipproperty_sub,conjecture,iext(uri_rdfs_subClassOf,uri_rdfs_ContainerMembershipProperty,uri_rdf_Property) = true ).
fof(rdfs_container_member_domain,conjecture,iext(uri_rdfs_domain,uri_rdfs_member,uri_rdfs_Resource) = true ).
fof(rdfs_container_member_range,conjecture,iext(uri_rdfs_range,uri_rdfs_member,uri_rdfs_Resource) = true ).
fof(rdfs_container_n_domain_001,conjecture,iext(uri_rdfs_domain,uri_rdf__1,uri_rdfs_Resource) = true ).
fof(rdfs_container_n_domain_002,conjecture,iext(uri_rdfs_domain,uri_rdf__2,uri_rdfs_Resource) = true ).
fof(rdfs_container_n_domain_003,conjecture,iext(uri_rdfs_domain,uri_rdf__3,uri_rdfs_Resource) = true ).
fof(rdfs_container_n_range_001,conjecture,iext(uri_rdfs_range,uri_rdf__1,uri_rdfs_Resource) = true ).
fof(rdfs_container_n_range_002,conjecture,iext(uri_rdfs_range,uri_rdf__2,uri_rdfs_Resource) = true ).
fof(rdfs_container_n_range_003,conjecture,iext(uri_rdfs_range,uri_rdf__3,uri_rdfs_Resource) = true ).
fof(rdfs_container_n_type_001,conjecture,iext(uri_rdf_type,uri_rdf__1,uri_rdfs_ContainerMembershipProperty) = true ).
fof(rdfs_container_n_type_002,conjecture,iext(uri_rdf_type,uri_rdf__2,uri_rdfs_ContainerMembershipProperty) = true ).
fof(rdfs_container_n_type_003,conjecture,iext(uri_rdf_type,uri_rdf__3,uri_rdfs_ContainerMembershipProperty) = true ).
fof(rdfs_container_seq_sub,conjecture,iext(uri_rdfs_subClassOf,uri_rdfs_Seq,uri_rdfs_Container) = true ).
fof(rdfs_dat_xmlliteral_sub,conjecture,iext(uri_rdfs_subClassOf,uri_rdf_XMLLiteral,uri_rdfs_Literal) = true ).
fof(rdfs_dat_xmlliteral_type,conjecture,iext(uri_rdf_type,uri_rdf_XMLLiteral,uri_rdfs_Datatype) = true ).
fof(rdfs_datatype_instsub_literal,conjecture,! [D] : ifeq(icext(uri_rdfs_Datatype,D),true,iext(uri_rdfs_subClassOf,D,uri_rdfs_Literal),true) = true ).
fof(rdfs_datatype_sub,conjecture,iext(uri_rdfs_subClassOf,uri_rdfs_Datatype,uri_rdfs_Class) = true ).
fof(rdfs_domain_domain,conjecture,iext(uri_rdfs_domain,uri_rdfs_domain,uri_rdf_Property) = true ).
fof(rdfs_domain_main,conjecture,! [P] : ! [C] : ! [X] : ! [Y] : ifeq(iext(uri_rdfs_domain,P,C),true,ifeq(iext(P,X,Y),true,icext(C,X),true),true) = true ).
fof(rdfs_domain_range,conjecture,iext(uri_rdfs_range,uri_rdfs_domain,uri_rdfs_Class) = true ).
fof(rdfs_ic_def_1,conjecture,! [X] : ifeq(ic(X),true,icext(uri_rdfs_Class,X),true) = true ).
fof(rdfs_ic_def,conjecture,! [X] : ifeq(icext(uri_rdfs_Class,X),true,ic(X),true) = true ).
fof(rdfs_ir_def_1,conjecture,! [X] : ifeq(icext(uri_rdfs_Resource,X),true,ir(X),true) = true ).
fof(rdfs_ir_def,conjecture,! [X] : ifeq(ir(X),true,icext(uri_rdfs_Resource,X),true) = true ).
fof(rdfs_lv_def_1,conjecture,! [X] : ifeq(icext(uri_rdfs_Literal,X),true,lv(X),true) = true ).
fof(rdfs_lv_def,conjecture,! [X] : ifeq(lv(X),true,icext(uri_rdfs_Literal,X),true) = true ).
fof(rdfs_property_type,conjecture,iext(uri_rdf_type,uri_rdf_Property,uri_rdfs_Class) = true ).
fof(rdfs_range_domain,conjecture,iext(uri_rdfs_domain,uri_rdfs_range,uri_rdf_Property) = true ).
fof(rdfs_range_main,conjecture,! [P] : ! [C] : ! [X] : ! [Y] : ifeq(iext(uri_rdfs_range,P,C),true,ifeq(iext(P,X,Y),true,icext(C,Y),true),true) = true ).
fof(rdfs_range_range,conjecture,iext(uri_rdfs_range,uri_rdfs_range,uri_rdfs_Class) = true ).
fof(rdfs_reification_object_domain,conjecture,iext(uri_rdfs_domain,uri_rdf_object,uri_rdfs_Statement) = true ).
fof(rdfs_reification_object_range,conjecture,iext(uri_rdfs_range,uri_rdf_predicate,uri_rdfs_Resource) = true ).
fof(rdfs_reification_predicate_domain,conjecture,iext(uri_rdfs_domain,uri_rdf_predicate,uri_rdfs_Statement) = true ).
fof(rdfs_reification_predicate_range,conjecture,iext(uri_rdfs_range,uri_rdf_predicate,uri_rdfs_Resource) = true ).
fof(rdfs_reification_subject_domain,conjecture,iext(uri_rdfs_domain,uri_rdf_subject,uri_rdfs_Statement) = true ).
fof(rdfs_reification_subject_range,conjecture,iext(uri_rdfs_range,uri_rdf_subject,uri_rdfs_Resource) = true ).
fof(rdfs_subclassof_domain,conjecture,iext(uri_rdfs_domain,uri_rdfs_subClassOf,uri_rdfs_Class) = true ).
fof(rdfs_subclassof_main_2,conjecture,! [C] : ! [X] : ! [D] : ifeq(icext(C,X),true,ifeq(iext(uri_rdfs_subClassOf,C,D),true,icext(D,X),true),true) = true ).
fof(rdfs_subclassof_main_1,conjecture,! [C] : ! [D] : ifeq(iext(uri_rdfs_subClassOf,C,D),true,ic(D),true) = true ).
fof(rdfs_subclassof_main,conjecture,! [C] : ! [D] : ifeq(iext(uri_rdfs_subClassOf,C,D),true,ic(C),true) = true ).
fof(rdfs_subclassof_range,conjecture,iext(uri_rdfs_range,uri_rdfs_subClassOf,uri_rdfs_Class) = true ).
fof(rdfs_subclassof_reflex,conjecture,! [C] : ifeq(ic(C),true,iext(uri_rdfs_subClassOf,C,C),true) = true ).
fof(rdfs_subclassof_trans,conjecture,! [D] : ! [E] : ! [C] : ifeq(iext(uri_rdfs_subClassOf,D,E),true,ifeq(iext(uri_rdfs_subClassOf,C,D),true,iext(uri_rdfs_subClassOf,C,E),true),true) = true ).
fof(rdfs_subpropertyof_domain,conjecture,iext(uri_rdfs_domain,uri_rdfs_subPropertyOf,uri_rdf_Property) = true ).
fof(rdfs_subpropertyof_main_2,conjecture,! [P] : ! [Q] : ifeq(iext(uri_rdfs_subPropertyOf,P,Q),true,ip(Q),true) = true ).
fof(rdfs_subpropertyof_main_1,conjecture,! [P] : ! [Q] : ifeq(iext(uri_rdfs_subPropertyOf,P,Q),true,ip(P),true) = true ).
fof(rdfs_subpropertyof_main,conjecture,! [P] : ! [Q] : ! [X] : ! [Y] : ifeq(iext(uri_rdfs_subPropertyOf,P,Q),true,ifeq(iext(P,X,Y),true,iext(Q,X,Y),true),true) = true ).
fof(rdfs_subpropertyof_range,conjecture,iext(uri_rdfs_range,uri_rdfs_subPropertyOf,uri_rdf_Property) = true ).
fof(rdfs_subpropertyof_reflex,conjecture,! [P] : ifeq(ip(P),true,iext(uri_rdfs_subPropertyOf,P,P),true) = true ).
fof(rdfs_subpropertyof_trans,conjecture,! [Q] : ! [R] : ! [P] : ifeq(iext(uri_rdfs_subPropertyOf,Q,R),true,ifeq(iext(uri_rdfs_subPropertyOf,P,Q),true,iext(uri_rdfs_subPropertyOf,P,R),true),true) = true ).
fof(rdfs_type_domain,conjecture,iext(uri_rdfs_domain,uri_rdf_type,uri_rdfs_Resource) = true ).
fof(rdfs_type_range,conjecture,iext(uri_rdfs_range,uri_rdf_type,uri_rdfs_Class) = true ).
fof(rdfs_value_domain,conjecture,iext(uri_rdfs_domain,uri_rdf_value,uri_rdfs_Resource) = true ).
fof(rdfs_value_range,conjecture,iext(uri_rdfs_range,uri_rdf_value,uri_rdfs_Resource) = true ).
fof(testcase_premise_fullish_018_Modified_Logical_Vocabulary_Semantics_1,conjecture,iext(uri_rdfs_domain,uri_owl_sameAs,uri_ex_Person) = true ).
fof(testcase_premise_fullish_018_Modified_Logical_Vocabulary_Semantics,conjecture,iext(uri_owl_sameAs,uri_ex_w,uri_ex_u) = true ).
fof(testcase_conclusion_fullish_018_Modified_Logical_Vocabulary_Semantics,conjecture,iext(uri_rdf_type,uri_ex_u,uri_ex_Person) != true ).
