fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq2(A,A,B,C) = B ).
fof(ifeq_axiom_001,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(mp7_first_movers_exist_17,conjecture,finite_set(first_movers) = true ).
fof(mp_stable_first_movers_18,conjecture,! [A] : ifeq(environment(A),true,ifeq(stable(A),true,in_environment(A,appear(first_movers,A)),true),true) = true ).
fof(mp_contracting_time_19,conjecture,! [A] : ! [B] : ifeq(finite_set(A),true,ifeq(contracts_from(B,A),true,greater(sk1(B,A),B),true),true) = true ).
fof(mp_contracting_time_20,conjecture,! [A] : ! [B] : ifeq2(finite_set(A),true,ifeq2(contracts_from(B,A),true,cardinality_at_time(s,t2),zero),zero) = zero ).
fof(mp_long_stable_environments_21,conjecture,! [C] : ! [B] : ! [A] : ifeq(greater(C,B),true,ifeq(in_environment(A,B),true,ifeq(environment(A),true,ifeq(stable(A),true,in_environment(A,C),true),true),true),true) = true ).
fof(mp_greater_transitivity_22,conjecture,! [B] : ! [C] : ! [A] : ifeq(greater(B,C),true,ifeq(greater(A,B),true,greater(A,C),true),true) = true ).
fof(l9_23,conjecture,! [A] : ifeq(environment(A),true,ifeq(stable(A),true,greater(sk2(A),appear(efficient_producers,A)),true),true) = true ).
fof(l9_24,conjecture,! [A] : ifeq(environment(A),true,ifeq(stable(A),true,contracts_from(sk2(A),first_movers),true),true) = true ).
fof(a13_25,conjecture,! [A] : ifeq(environment(A),true,greater(appear(efficient_producers,e),appear(first_movers,A)),true) = true ).
fof(prove_t7_26,conjecture,environment(sk3) = true ).
fof(prove_t7_27,conjecture,stable(sk3) = true ).
fof(prove_t7_28,conjecture,! [A] : tuple(cardinality_at_time(first_movers,to),in_environment(sk3,A),greater(A,appear(first_movers,sk3))) != tuple(zero,true,true) ).
