fof(ax1,conjecture,! [U] : ! [V] : ( artifact(U,V) => object(U,V) ) ).
fof(ax2,conjecture,! [U] : ! [V] : ( building(U,V) => artifact(U,V) ) ).
fof(ax3,conjecture,! [U] : ! [V] : ( restaurant(U,V) => building(U,V) ) ).
fof(ax4,conjecture,! [U] : ! [V] : ( customer(U,V) => human_person(U,V) ) ).
fof(ax5,conjecture,! [U] : ! [V] : ( human_person(U,V) => animate(U,V) ) ).
fof(ax6,conjecture,! [U] : ! [V] : ( human_person(U,V) => human(U,V) ) ).
fof(ax7,conjecture,! [U] : ! [V] : ( organism(U,V) => living(U,V) ) ).
fof(ax8,conjecture,! [U] : ! [V] : ( organism(U,V) => impartial(U,V) ) ).
fof(ax9,conjecture,! [U] : ! [V] : ( organism(U,V) => entity(U,V) ) ).
fof(ax10,conjecture,! [U] : ! [V] : ( human_person(U,V) => organism(U,V) ) ).
fof(ax11,conjecture,! [U] : ! [V] : ( object(U,V) => unisex(U,V) ) ).
fof(ax12,conjecture,! [U] : ! [V] : ( object(U,V) => impartial(U,V) ) ).
fof(ax13,conjecture,! [U] : ! [V] : ( object(U,V) => nonliving(U,V) ) ).
fof(ax14,conjecture,! [U] : ! [V] : ( entity(U,V) => existent(U,V) ) ).
fof(ax15,conjecture,! [U] : ! [V] : ( entity(U,V) => specific(U,V) ) ).
fof(ax16,conjecture,! [U] : ! [V] : ( entity(U,V) => thing(U,V) ) ).
fof(ax17,conjecture,! [U] : ! [V] : ( object(U,V) => entity(U,V) ) ).
fof(ax18,conjecture,! [U] : ! [V] : ( substance_matter(U,V) => object(U,V) ) ).
fof(ax19,conjecture,! [U] : ! [V] : ( food(U,V) => substance_matter(U,V) ) ).
fof(ax20,conjecture,! [U] : ! [V] : ( beverage(U,V) => food(U,V) ) ).
fof(ax21,conjecture,! [U] : ! [V] : ( coffee(U,V) => beverage(U,V) ) ).
fof(ax22,conjecture,! [U] : ! [V] : ( drink(U,V) => event(U,V) ) ).
fof(ax23,conjecture,! [U] : ! [V] : ( eventuality(U,V) => unisex(U,V) ) ).
fof(ax24,conjecture,! [U] : ! [V] : ( eventuality(U,V) => nonexistent(U,V) ) ).
fof(ax25,conjecture,! [U] : ! [V] : ( eventuality(U,V) => specific(U,V) ) ).
fof(ax26,conjecture,! [U] : ! [V] : ( thing(U,V) => singleton(U,V) ) ).
fof(ax27,conjecture,! [U] : ! [V] : ( eventuality(U,V) => thing(U,V) ) ).
fof(ax28,conjecture,! [U] : ! [V] : ( event(U,V) => eventuality(U,V) ) ).
fof(ax29,conjecture,! [U] : ! [V] : ( see(U,V) => event(U,V) ) ).
fof(ax30,conjecture,! [U] : ! [V] : ( animate(U,V) => ~ nonliving(U,V) ) ).
fof(ax31,conjecture,! [U] : ! [V] : ( existent(U,V) => ~ nonexistent(U,V) ) ).
fof(ax32,conjecture,! [U] : ! [V] : ( nonliving(U,V) => ~ living(U,V) ) ).
fof(ax33,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ( ( drink(U,V) & agent(U,V,W) & patient(U,V,X) ) => beverage(U,X) ) ).
fof(ax34,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ( ( nonreflexive(U,V) & agent(U,V,W) & patient(U,V,X) ) => W != X ) ).
fof(co1,conjecture,~(~ ( ? [U] : ( actual_world(U) & ? [V] : ? [W] : ? [X] : ( coffee(U,V) & human_person(U,W) & event(U,X) & agent(U,X,W) & patient(U,X,V) & past(U,X) & nonreflexive(U,X) & drink(U,X) & ! [Y] : ! [Z] : ( ( customer(U,Y) & restaurant(U,Z) & in(U,Y,Z) ) => ? [X1] : ( event(U,X1) & agent(U,X1,Y) & patient(U,X1,W) & past(U,X1) & nonreflexive(U,X1) & see(U,X1) ) ) ) ) ) )).
