fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq3(A,A,B,C) = B ).
fof(ifeq_axiom_001,conjecture,! [A] : ! [B] : ! [C] : ifeq2(A,A,B,C) = B ).
fof(ifeq_axiom_002,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(clause1,conjecture,! [U] : ! [V] : ifeq3(see(U,V),true,event(U,V),true) = true ).
fof(clause2,conjecture,! [U] : ! [V] : ifeq3(event(U,V),true,eventuality(U,V),true) = true ).
fof(clause3,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,thing(U,V),true) = true ).
fof(clause4,conjecture,! [U] : ! [V] : ifeq3(thing(U,V),true,singleton(U,V),true) = true ).
fof(clause5,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,specific(U,V),true) = true ).
fof(clause6,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,nonexistent(U,V),true) = true ).
fof(clause7,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,unisex(U,V),true) = true ).
fof(clause8,conjecture,! [U] : ! [V] : ifeq3(drink(U,V),true,event(U,V),true) = true ).
fof(clause9,conjecture,! [U] : ! [V] : ifeq3(coffee(U,V),true,beverage(U,V),true) = true ).
fof(clause10,conjecture,! [U] : ! [V] : ifeq3(beverage(U,V),true,food(U,V),true) = true ).
fof(clause11,conjecture,! [U] : ! [V] : ifeq3(food(U,V),true,substance_matter(U,V),true) = true ).
fof(clause12,conjecture,! [U] : ! [V] : ifeq3(substance_matter(U,V),true,object(U,V),true) = true ).
fof(clause13,conjecture,! [U] : ! [V] : ifeq3(object(U,V),true,entity(U,V),true) = true ).
fof(clause14,conjecture,! [U] : ! [V] : ifeq3(entity(U,V),true,thing(U,V),true) = true ).
fof(clause15,conjecture,! [U] : ! [V] : ifeq3(entity(U,V),true,specific(U,V),true) = true ).
fof(clause16,conjecture,! [U] : ! [V] : ifeq3(entity(U,V),true,existent(U,V),true) = true ).
fof(clause17,conjecture,! [U] : ! [V] : ifeq3(object(U,V),true,nonliving(U,V),true) = true ).
fof(clause18,conjecture,! [U] : ! [V] : ifeq3(object(U,V),true,impartial(U,V),true) = true ).
fof(clause19,conjecture,! [U] : ! [V] : ifeq3(object(U,V),true,unisex(U,V),true) = true ).
fof(clause20,conjecture,! [U] : ! [V] : ifeq3(human_person(U,V),true,organism(U,V),true) = true ).
fof(clause21,conjecture,! [U] : ! [V] : ifeq3(organism(U,V),true,entity(U,V),true) = true ).
fof(clause22,conjecture,! [U] : ! [V] : ifeq3(organism(U,V),true,impartial(U,V),true) = true ).
fof(clause23,conjecture,! [U] : ! [V] : ifeq3(organism(U,V),true,living(U,V),true) = true ).
fof(clause24,conjecture,! [U] : ! [V] : ifeq3(human_person(U,V),true,human(U,V),true) = true ).
fof(clause25,conjecture,! [U] : ! [V] : ifeq3(human_person(U,V),true,animate(U,V),true) = true ).
fof(clause26,conjecture,! [U] : ! [V] : ifeq3(customer(U,V),true,human_person(U,V),true) = true ).
fof(clause27,conjecture,! [U] : ! [V] : ifeq3(restaurant(U,V),true,building(U,V),true) = true ).
fof(clause28,conjecture,! [U] : ! [V] : ifeq3(building(U,V),true,artifact(U,V),true) = true ).
fof(clause29,conjecture,! [U] : ! [V] : ifeq3(artifact(U,V),true,object(U,V),true) = true ).
fof(clause34,conjecture,! [U] : ! [V] : ! [X] : ! [W] : ifeq3(agent(U,V,X),true,ifeq3(patient(U,V,W),true,ifeq3(drink(U,V),true,beverage(U,W),true),true),true) = true ).
fof(clause35,conjecture,actual_world(skc5) = true ).
fof(clause36,conjecture,restaurant(skc5,skc8) = true ).
fof(clause37,conjecture,human_person(skc5,skc7) = true ).
fof(clause38,conjecture,drink(skc5,skc6) = true ).
fof(clause39,conjecture,nonreflexive(skc5,skc6) = true ).
fof(clause40,conjecture,past(skc5,skc6) = true ).
fof(clause41,conjecture,event(skc5,skc6) = true ).
fof(clause42,conjecture,coffee(skc5,skc10) = true ).
fof(clause43,conjecture,patient(skc5,skc6,skc10) = true ).
fof(clause44,conjecture,agent(skc5,skc6,skc7) = true ).
fof(clause45,conjecture,! [U] : ! [V] : ifeq3(in(skc5,U,skc8),true,ifeq3(customer(skc5,U),true,see(skc5,skf1(V)),true),true) = true ).
fof(clause46,conjecture,! [U] : ! [V] : ifeq3(in(skc5,U,skc8),true,ifeq3(customer(skc5,U),true,nonreflexive(skc5,skf1(V)),true),true) = true ).
fof(clause47,conjecture,! [U] : ! [V] : ifeq3(in(skc5,U,skc8),true,ifeq3(customer(skc5,U),true,past(skc5,skf1(V)),true),true) = true ).
fof(clause48,conjecture,! [U] : ! [V] : ifeq3(in(skc5,U,skc8),true,ifeq3(customer(skc5,U),true,event(skc5,skf1(V)),true),true) = true ).
fof(clause49,conjecture,! [U] : ! [V] : ifeq3(in(skc5,U,skc8),true,ifeq3(customer(skc5,U),true,patient(skc5,skf1(V),skc7),true),true) = true ).
fof(clause50,conjecture,! [U] : ifeq3(in(skc5,U,skc8),true,ifeq3(customer(skc5,U),true,agent(skc5,skf1(U),U),true),true) = true ).
fof(clause30,conjecture,! [U] : ! [V] : ifeq2(tuple2(nonliving(U,V),living(U,V)),tuple2(true,true),a,b) = b ).
fof(clause31,conjecture,! [U] : ! [V] : ifeq2(tuple2(nonexistent(U,V),existent(U,V)),tuple2(true,true),a,b) = b ).
fof(clause32,conjecture,! [U] : ! [V] : ifeq2(tuple2(nonliving(U,V),animate(U,V)),tuple2(true,true),a,b) = b ).
fof(clause33,conjecture,! [U] : ! [V] : ! [W] : ifeq(tuple(patient(U,V,W),nonreflexive(U,V),agent(U,V,W)),tuple(true,true,true),a,b) = b ).
fof(goal,conjecture,a != b ).
