fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq3(A,A,B,C) = B ).
fof(ifeq_axiom_001,conjecture,! [A] : ! [B] : ! [C] : ifeq2(A,A,B,C) = B ).
fof(ifeq_axiom_002,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(a1_1_3,conjecture,! [A] : ! [N] : ! [L] : ! [C] : ifeq3(accept_number(A,N),true,ifeq3(accept_leader(A,L),true,ifeq3(accept_city(A,C),true,accept_team(A,L,C,N),true),true),true) = true ).
fof(a1_1_2,conjecture,! [A] : ! [L] : ! [C] : ! [N] : ifeq3(accept_team(A,L,C,N),true,accept_number(A,N),true) = true ).
fof(a1_1_1,conjecture,! [A] : ! [L] : ! [C] : ! [N] : ifeq3(accept_team(A,L,C,N),true,accept_leader(A,L),true) = true ).
fof(a1_1,conjecture,! [A] : ! [L] : ! [C] : ! [N] : ifeq3(accept_team(A,L,C,N),true,accept_city(A,C),true) = true ).
fof(a1_2,conjecture,! [M] : ! [N] : ! [A] : ifeq3(less(M,N),true,ifeq3(accept_number(A,N),true,accept_number(A,M),true),true) = true ).
fof(a1_3,conjecture,! [A] : ! [P] : ! [N] : ! [M] : ifeq3(accept_population(A,P,N),true,ifeq3(less(M,N),true,accept_population(A,P,M),true),true) = true ).
fof(a1_4_1,conjecture,! [A] : ! [L] : ! [C] : ifeq3(the_agent_in_all_proposed_teams(A,L,C),true,accept_leader(A,L),true) = true ).
fof(a1_4,conjecture,! [A] : ! [L] : ! [C] : ifeq3(the_agent_in_all_proposed_teams(A,L,C),true,accept_city(A,C),true) = true ).
fof(a1_5,conjecture,! [A] : ! [L] : ! [C] : ifeq3(any_agent_in_all_proposed_teams(A,L,C),true,accept_leader(A,L),true) = true ).
fof(a1_7,conjecture,! [A] : ! [N] : ifeq3(min_number_of_proposed_agents(A,N),true,accept_number(A,N),true) = true ).
fof(a2_1_5,conjecture,! [A] : ifeq3(accept_population(A,other,n4),true,ifeq3(accept_population(A,native,n4),true,ifeq3(accept_population(A,muslim,n7),true,ifeq3(accept_population(A,atheist,n65),true,ifeq3(accept_population(A,christian,n20),true,accept_city(A,suffertown),true),true),true),true),true) = true ).
fof(a2_1_4,conjecture,! [A] : ifeq3(accept_city(A,suffertown),true,accept_population(A,other,n4),true) = true ).
fof(a2_1_3,conjecture,! [A] : ifeq3(accept_city(A,suffertown),true,accept_population(A,native,n4),true) = true ).
fof(a2_1_2,conjecture,! [A] : ifeq3(accept_city(A,suffertown),true,accept_population(A,muslim,n7),true) = true ).
fof(a2_1_1,conjecture,! [A] : ifeq3(accept_city(A,suffertown),true,accept_population(A,atheist,n65),true) = true ).
fof(a2_1,conjecture,! [A] : ifeq3(accept_city(A,suffertown),true,accept_population(A,christian,n20),true) = true ).
fof(a2_2_5,conjecture,! [A] : ifeq3(accept_population(A,other,n9),true,ifeq3(accept_population(A,native,n1),true,ifeq3(accept_population(A,muslim,n3),true,ifeq3(accept_population(A,atheist,n54),true,ifeq3(accept_population(A,christian,n23),true,accept_city(A,centraltown),true),true),true),true),true) = true ).
fof(a2_2_4,conjecture,! [A] : ifeq3(accept_city(A,centraltown),true,accept_population(A,other,n9),true) = true ).
fof(a2_2_3,conjecture,! [A] : ifeq3(accept_city(A,centraltown),true,accept_population(A,native,n1),true) = true ).
fof(a2_2_2,conjecture,! [A] : ifeq3(accept_city(A,centraltown),true,accept_population(A,muslim,n3),true) = true ).
fof(a2_2_1,conjecture,! [A] : ifeq3(accept_city(A,centraltown),true,accept_population(A,atheist,n54),true) = true ).
fof(a2_2,conjecture,! [A] : ifeq3(accept_city(A,centraltown),true,accept_population(A,christian,n23),true) = true ).
fof(a2_3_5,conjecture,! [A] : ifeq3(accept_population(A,other,n1),true,ifeq3(accept_population(A,native,n1),true,ifeq3(accept_population(A,muslim,n60),true,ifeq3(accept_population(A,atheist,n30),true,ifeq3(accept_population(A,christian,n8),true,accept_city(A,sunnysideport),true),true),true),true),true) = true ).
fof(a2_3_4,conjecture,! [A] : ifeq3(accept_city(A,sunnysideport),true,accept_population(A,other,n1),true) = true ).
fof(a2_3_3,conjecture,! [A] : ifeq3(accept_city(A,sunnysideport),true,accept_population(A,native,n1),true) = true ).
fof(a2_3_2,conjecture,! [A] : ifeq3(accept_city(A,sunnysideport),true,accept_population(A,muslim,n60),true) = true ).
fof(a2_3_1,conjecture,! [A] : ifeq3(accept_city(A,sunnysideport),true,accept_population(A,atheist,n30),true) = true ).
fof(a2_3,conjecture,! [A] : ifeq3(accept_city(A,sunnysideport),true,accept_population(A,christian,n8),true) = true ).
fof(a2_4_5,conjecture,! [A] : ifeq3(accept_population(A,other,n4),true,ifeq3(accept_population(A,native,n10),true,ifeq3(accept_population(A,muslim,n1),true,ifeq3(accept_population(A,atheist,n70),true,ifeq3(accept_population(A,christian,n15),true,accept_city(A,centrallakecity),true),true),true),true),true) = true ).
fof(a2_4_4,conjecture,! [A] : ifeq3(accept_city(A,centrallakecity),true,accept_population(A,other,n4),true) = true ).
fof(a2_4_3,conjecture,! [A] : ifeq3(accept_city(A,centrallakecity),true,accept_population(A,native,n10),true) = true ).
fof(a2_4_2,conjecture,! [A] : ifeq3(accept_city(A,centrallakecity),true,accept_population(A,muslim,n1),true) = true ).
fof(a2_4_1,conjecture,! [A] : ifeq3(accept_city(A,centrallakecity),true,accept_population(A,atheist,n70),true) = true ).
fof(a2_4,conjecture,! [A] : ifeq3(accept_city(A,centrallakecity),true,accept_population(A,christian,n15),true) = true ).
fof(a2_5_5,conjecture,! [A] : ifeq3(accept_population(A,other,n4),true,ifeq3(accept_population(A,native,n11),true,ifeq3(accept_population(A,muslim,n1),true,ifeq3(accept_population(A,atheist,n68),true,ifeq3(accept_population(A,christian,n16),true,accept_city(A,stjosephburgh),true),true),true),true),true) = true ).
fof(a2_5_4,conjecture,! [A] : ifeq3(accept_city(A,stjosephburgh),true,accept_population(A,other,n4),true) = true ).
fof(a2_5_3,conjecture,! [A] : ifeq3(accept_city(A,stjosephburgh),true,accept_population(A,native,n11),true) = true ).
fof(a2_5_2,conjecture,! [A] : ifeq3(accept_city(A,stjosephburgh),true,accept_population(A,muslim,n1),true) = true ).
fof(a2_5_1,conjecture,! [A] : ifeq3(accept_city(A,stjosephburgh),true,accept_population(A,atheist,n68),true) = true ).
fof(a2_5,conjecture,! [A] : ifeq3(accept_city(A,stjosephburgh),true,accept_population(A,christian,n16),true) = true ).
fof(a2_6_5,conjecture,! [A] : ifeq3(accept_population(A,other,n2),true,ifeq3(accept_population(A,native,n15),true,ifeq3(accept_population(A,muslim,n0),true,ifeq3(accept_population(A,atheist,n70),true,ifeq3(accept_population(A,christian,n13),true,accept_city(A,northport),true),true),true),true),true) = true ).
fof(a2_6_4,conjecture,! [A] : ifeq3(accept_city(A,northport),true,accept_population(A,other,n2),true) = true ).
fof(a2_6_3,conjecture,! [A] : ifeq3(accept_city(A,northport),true,accept_population(A,native,n15),true) = true ).
fof(a2_6_2,conjecture,! [A] : ifeq3(accept_city(A,northport),true,accept_population(A,muslim,n0),true) = true ).
fof(a2_6_1,conjecture,! [A] : ifeq3(accept_city(A,northport),true,accept_population(A,atheist,n70),true) = true ).
fof(a2_6,conjecture,! [A] : ifeq3(accept_city(A,northport),true,accept_population(A,christian,n13),true) = true ).
fof(a2_7_5,conjecture,! [A] : ifeq3(accept_population(A,other,n0),true,ifeq3(accept_population(A,native,n85),true,ifeq3(accept_population(A,muslim,n0),true,ifeq3(accept_population(A,atheist,n12),true,ifeq3(accept_population(A,christian,n3),true,accept_city(A,coastvillage),true),true),true),true),true) = true ).
fof(a2_7_4,conjecture,! [A] : ifeq3(accept_city(A,coastvillage),true,accept_population(A,other,n0),true) = true ).
fof(a2_7_3,conjecture,! [A] : ifeq3(accept_city(A,coastvillage),true,accept_population(A,native,n85),true) = true ).
fof(a2_7_2,conjecture,! [A] : ifeq3(accept_city(A,coastvillage),true,accept_population(A,muslim,n0),true) = true ).
fof(a2_7_1,conjecture,! [A] : ifeq3(accept_city(A,coastvillage),true,accept_population(A,atheist,n12),true) = true ).
fof(a2_7,conjecture,! [A] : ifeq3(accept_city(A,coastvillage),true,accept_population(A,christian,n3),true) = true ).
fof(a2_8_5,conjecture,! [A] : ifeq3(accept_population(A,other,n0),true,ifeq3(accept_population(A,native,n100),true,ifeq3(accept_population(A,muslim,n0),true,ifeq3(accept_population(A,atheist,n0),true,ifeq3(accept_population(A,christian,n0),true,accept_city(A,sunsetpoint),true),true),true),true),true) = true ).
fof(a2_8_4,conjecture,! [A] : ifeq3(accept_city(A,sunsetpoint),true,accept_population(A,other,n0),true) = true ).
fof(a2_8_3,conjecture,! [A] : ifeq3(accept_city(A,sunsetpoint),true,accept_population(A,native,n100),true) = true ).
fof(a2_8_2,conjecture,! [A] : ifeq3(accept_city(A,sunsetpoint),true,accept_population(A,muslim,n0),true) = true ).
fof(a2_8_1,conjecture,! [A] : ifeq3(accept_city(A,sunsetpoint),true,accept_population(A,atheist,n0),true) = true ).
fof(a2_8,conjecture,! [A] : ifeq3(accept_city(A,sunsetpoint),true,accept_population(A,christian,n0),true) = true ).
fof(a2_9_5,conjecture,! [A] : ifeq3(accept_population(A,other,n0),true,ifeq3(accept_population(A,native,n0),true,ifeq3(accept_population(A,muslim,n1),true,ifeq3(accept_population(A,atheist,n75),true,ifeq3(accept_population(A,christian,n24),true,accept_city(A,towna),true),true),true),true),true) = true ).
fof(a2_9_4,conjecture,! [A] : ifeq3(accept_city(A,towna),true,accept_population(A,other,n0),true) = true ).
fof(a2_9_3,conjecture,! [A] : ifeq3(accept_city(A,towna),true,accept_population(A,native,n0),true) = true ).
fof(a2_9_2,conjecture,! [A] : ifeq3(accept_city(A,towna),true,accept_population(A,muslim,n1),true) = true ).
fof(a2_9_1,conjecture,! [A] : ifeq3(accept_city(A,towna),true,accept_population(A,atheist,n75),true) = true ).
fof(a2_9,conjecture,! [A] : ifeq3(accept_city(A,towna),true,accept_population(A,christian,n24),true) = true ).
fof(a2_10_5,conjecture,! [A] : ifeq3(accept_population(A,other,n0),true,ifeq3(accept_population(A,native,n0),true,ifeq3(accept_population(A,muslim,n0),true,ifeq3(accept_population(A,atheist,n75),true,ifeq3(accept_population(A,christian,n25),true,accept_city(A,citya),true),true),true),true),true) = true ).
fof(a2_10_4,conjecture,! [A] : ifeq3(accept_city(A,citya),true,accept_population(A,other,n0),true) = true ).
fof(a2_10_3,conjecture,! [A] : ifeq3(accept_city(A,citya),true,accept_population(A,native,n0),true) = true ).
fof(a2_10_2,conjecture,! [A] : ifeq3(accept_city(A,citya),true,accept_population(A,muslim,n0),true) = true ).
fof(a2_10_1,conjecture,! [A] : ifeq3(accept_city(A,citya),true,accept_population(A,atheist,n75),true) = true ).
fof(a2_10,conjecture,! [A] : ifeq3(accept_city(A,citya),true,accept_population(A,christian,n25),true) = true ).
fof(a2_11_5,conjecture,! [A] : ifeq3(accept_population(A,other,n2),true,ifeq3(accept_population(A,native,n0),true,ifeq3(accept_population(A,muslim,n8),true,ifeq3(accept_population(A,atheist,n70),true,ifeq3(accept_population(A,christian,n20),true,accept_city(A,townb),true),true),true),true),true) = true ).
fof(a2_11_4,conjecture,! [A] : ifeq3(accept_city(A,townb),true,accept_population(A,other,n2),true) = true ).
fof(a2_11_3,conjecture,! [A] : ifeq3(accept_city(A,townb),true,accept_population(A,native,n0),true) = true ).
fof(a2_11_2,conjecture,! [A] : ifeq3(accept_city(A,townb),true,accept_population(A,muslim,n8),true) = true ).
fof(a2_11_1,conjecture,! [A] : ifeq3(accept_city(A,townb),true,accept_population(A,atheist,n70),true) = true ).
fof(a2_11,conjecture,! [A] : ifeq3(accept_city(A,townb),true,accept_population(A,christian,n20),true) = true ).
fof(a2_12_5,conjecture,! [A] : ifeq3(accept_population(A,other,n1),true,ifeq3(accept_population(A,native,n0),true,ifeq3(accept_population(A,muslim,n1),true,ifeq3(accept_population(A,atheist,n78),true,ifeq3(accept_population(A,christian,n20),true,accept_city(A,cityb),true),true),true),true),true) = true ).
fof(a2_12_4,conjecture,! [A] : ifeq3(accept_city(A,cityb),true,accept_population(A,other,n1),true) = true ).
fof(a2_12_3,conjecture,! [A] : ifeq3(accept_city(A,cityb),true,accept_population(A,native,n0),true) = true ).
fof(a2_12_2,conjecture,! [A] : ifeq3(accept_city(A,cityb),true,accept_population(A,muslim,n1),true) = true ).
fof(a2_12_1,conjecture,! [A] : ifeq3(accept_city(A,cityb),true,accept_population(A,atheist,n78),true) = true ).
fof(a2_12,conjecture,! [A] : ifeq3(accept_city(A,cityb),true,accept_population(A,christian,n20),true) = true ).
fof(a2_13_5,conjecture,! [A] : ifeq3(accept_population(A,other,n5),true,ifeq3(accept_population(A,native,n0),true,ifeq3(accept_population(A,muslim,n65),true,ifeq3(accept_population(A,atheist,n30),true,ifeq3(accept_population(A,christian,n0),true,accept_city(A,townc),true),true),true),true),true) = true ).
fof(a2_13_4,conjecture,! [A] : ifeq3(accept_city(A,townc),true,accept_population(A,other,n5),true) = true ).
fof(a2_13_3,conjecture,! [A] : ifeq3(accept_city(A,townc),true,accept_population(A,native,n0),true) = true ).
fof(a2_13_2,conjecture,! [A] : ifeq3(accept_city(A,townc),true,accept_population(A,muslim,n65),true) = true ).
fof(a2_13_1,conjecture,! [A] : ifeq3(accept_city(A,townc),true,accept_population(A,atheist,n30),true) = true ).
fof(a2_13,conjecture,! [A] : ifeq3(accept_city(A,townc),true,accept_population(A,christian,n0),true) = true ).
fof(event_1,conjecture,accept_team(countryahumanitarianorganization,countryacivilorganization,cityb,n6) = true ).
fof(event_2,conjecture,accept_team(countryahumanitarianorganization,countryacivilorganization,towna,n6) = true ).
fof(event_3,conjecture,accept_team(countryahumanitarianorganization,countryacivilorganization,coastvillage,n6) = true ).
fof(event_4,conjecture,accept_team(countryahumanitarianorganization,countryafirstaidorganization,coastvillage,n6) = true ).
fof(event_5,conjecture,the_agent_in_all_proposed_teams(countryahumanitarianorganization,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_6,conjecture,any_agent_in_all_proposed_teams(countryahumanitarianorganization,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_7,conjecture,accept_team(countryccivilorganization,countrybhumanitarianorganization,cityb,n2) = true ).
fof(event_8,conjecture,accept_team(muslimcountrybhumanitarianorganization,countrybhumanitarianorganization,cityb,n4) = true ).
fof(event_11,conjecture,the_agent_not_in_any_proposed_teams(muslimcountrybhumanitarianorganization,countryacivilorganization,towna) = true ).
fof(event_12,conjecture,any_agent_in_all_proposed_teams(muslimcountrybhumanitarianorganization,countryacivilorganization,towna) = true ).
fof(event_13,conjecture,accept_team(muslimcountrybhumanitarianorganization,christiancountrychumanitarianorganization,coastvillage,n5) = true ).
fof(event_14,conjecture,accept_team(countryamedicalorganization,countryacivilorganization,cityb,n6) = true ).
fof(event_15,conjecture,accept_team(christiancountrychumanitarianorganization,countrybhumanitarianorganization,cityb,n4) = true ).
fof(event_16,conjecture,accept_team(countryafirstaidorganization,countryacivilorganization,cityb,n6) = true ).
fof(event_17,conjecture,accept_number(countrybhumanitarianorganization,n4) = true ).
fof(event_18,conjecture,accept_team(countrybcivilorganization,countrybhumanitarianorganization,cityb,n4) = true ).
fof(event_19,conjecture,accept_team(christiansufferterrahumanitarianorganization,countryacivilorganization,cityb,n6) = true ).
fof(event_20,conjecture,accept_team(sufferterragovernment,countryacivilorganization,cityb,n6) = true ).
fof(event_21,conjecture,accept_number(countrybhumanitarianorganization,n1) = true ).
fof(event_22,conjecture,the_agent_in_all_proposed_teams(countrybhumanitarianorganization,countryacivilorganization,towna) = true ).
fof(event_23,conjecture,any_agent_in_all_proposed_teams(countrybhumanitarianorganization,countryacivilorganization,towna) = true ).
fof(event_24,conjecture,accept_team(countrybhumanitarianorganization,christiancountrychumanitarianorganization,coastvillage,n5) = true ).
fof(event_25,conjecture,accept_team(countrybhumanitarianorganization,christiancountrychumanitarianorganization,coastvillage,n6) = true ).
fof(event_26,conjecture,accept_team(christiansufferterrahumanitarianorganization,countryacivilorganization,towna,n6) = true ).
fof(event_27,conjecture,accept_team(countryamedicalorganization,countryacivilorganization,towna,n6) = true ).
fof(event_28,conjecture,accept_number(countryahumanitarianorganization,n2) = true ).
fof(event_37,conjecture,the_agent_not_in_any_proposed_teams(countryamedicalorganization,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_38,conjecture,any_agent_in_all_proposed_teams(countryamedicalorganization,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_39,conjecture,accept_team(countryccivilorganization,countrycmedicalorganization,towna,n4) = true ).
fof(event_41,conjecture,the_agent_in_all_proposed_teams(countryccivilorganization,countryacivilorganization,towna) = true ).
fof(event_42,conjecture,any_agent_in_all_proposed_teams(countryccivilorganization,countryacivilorganization,towna) = true ).
fof(event_43,conjecture,accept_team(countrybcivilorganization,countrycmedicalorganization,towna,n4) = true ).
fof(event_44,conjecture,accept_team(countrybcivilorganization,countrycmedicalorganization,towna,n5) = true ).
fof(event_45,conjecture,accept_number(countrybcivilorganization,n5) = true ).
fof(event_46,conjecture,the_agent_in_all_proposed_teams(countrybcivilorganization,countryacivilorganization,towna) = true ).
fof(event_47,conjecture,any_agent_in_all_proposed_teams(countrybcivilorganization,countryacivilorganization,towna) = true ).
fof(event_48,conjecture,accept_team(sufferterragovernment,countryacivilorganization,towna,n6) = true ).
fof(event_49,conjecture,the_agent_in_all_proposed_teams(countrycmedicalorganization,countryacivilorganization,towna) = true ).
fof(event_50,conjecture,any_agent_in_all_proposed_teams(countrycmedicalorganization,countryacivilorganization,towna) = true ).
fof(event_51,conjecture,accept_team(countrycmedicalorganization,christiancountrychumanitarianorganization,coastvillage,n5) = true ).
fof(event_52,conjecture,accept_number(countrycmedicalorganization,n4) = true ).
fof(event_53,conjecture,accept_team(christiancountrychumanitarianorganization,countrycmedicalorganization,towna,n4) = true ).
fof(event_54,conjecture,accept_number(countrycmedicalorganization,n5) = true ).
fof(event_55,conjecture,accept_team(christiancountrychumanitarianorganization,countrycmedicalorganization,towna,n5) = true ).
fof(event_56,conjecture,the_agent_in_all_proposed_teams(christiancountrychumanitarianorganization,countryacivilorganization,towna) = true ).
fof(event_57,conjecture,any_agent_in_all_proposed_teams(christiancountrychumanitarianorganization,countryacivilorganization,towna) = true ).
fof(event_58,conjecture,accept_team(countryafirstaidorganization,countryacivilorganization,towna,n6) = true ).
fof(event_59,conjecture,accept_number(countryacivilorganization,n2) = true ).
fof(event_60,conjecture,accept_team(countryacivilorganization,countryahumanitarianorganization,coastvillage,n5) = true ).
fof(event_61,conjecture,accept_team(countryacivilorganization,countryahumanitarianorganization,coastvillage,n6) = true ).
fof(event_62,conjecture,accept_team(countryacivilorganization,countryafirstaidorganization,coastvillage,n6) = true ).
fof(event_63,conjecture,the_agent_in_all_proposed_teams(countryacivilorganization,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_64,conjecture,any_agent_in_all_proposed_teams(countryacivilorganization,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_65,conjecture,accept_number(countryafirstaidorganization,n2) = true ).
fof(event_66,conjecture,accept_team(countryafirstaidorganization,countryahumanitarianorganization,coastvillage,n5) = true ).
fof(event_67,conjecture,accept_team(countryafirstaidorganization,countryahumanitarianorganization,coastvillage,n6) = true ).
fof(event_68,conjecture,accept_team(countryafirstaidorganization,countryacivilorganization,coastvillage,n6) = true ).
fof(event_69,conjecture,the_agent_in_all_proposed_teams(countryafirstaidorganization,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_70,conjecture,any_agent_in_all_proposed_teams(countryafirstaidorganization,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_73,conjecture,accept_number(christiancountrychumanitarianorganization,n5) = true ).
fof(event_74,conjecture,accept_team(countrybcivilorganization,christiancountrychumanitarianorganization,coastvillage,n5) = true ).
fof(event_75,conjecture,accept_team(countrybcivilorganization,christiancountrychumanitarianorganization,coastvillage,n6) = true ).
fof(event_76,conjecture,accept_team(countrybcivilorganization,muslimcountrybhumanitarianorganization,townc,n6) = true ).
fof(event_77,conjecture,accept_team(countrybcivilorganization,countrybhumanitarianorganization,townc,n6) = true ).
fof(event_78,conjecture,accept_team(countrybcivilorganization,christiancountrychumanitarianorganization,townc,n6) = true ).
fof(event_79,conjecture,accept_team(countrybcivilorganization,countrycmedicalorganization,townc,n6) = true ).
fof(event_80,conjecture,the_agent_in_all_proposed_teams(countrybcivilorganization,countryahumanitarianorganization,townc) = true ).
fof(event_81,conjecture,any_agent_in_all_proposed_teams(countrybcivilorganization,countryahumanitarianorganization,townc) = true ).
fof(event_82,conjecture,accept_team(sufferterragovernment,countryahumanitarianorganization,coastvillage,n5) = true ).
fof(event_83,conjecture,accept_team(sufferterragovernment,countryahumanitarianorganization,coastvillage,n6) = true ).
fof(event_84,conjecture,accept_team(sufferterragovernment,countryacivilorganization,coastvillage,n6) = true ).
fof(event_85,conjecture,accept_team(sufferterragovernment,countryafirstaidorganization,coastvillage,n6) = true ).
fof(event_86,conjecture,the_agent_in_all_proposed_teams(sufferterragovernment,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_87,conjecture,any_agent_in_all_proposed_teams(sufferterragovernment,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_88,conjecture,accept_number(christiansufferterrahumanitarianorganization,n2) = true ).
fof(event_89,conjecture,accept_number(countryahumanitarianorganization,n5) = true ).
fof(event_90,conjecture,accept_team(christiansufferterrahumanitarianorganization,countryahumanitarianorganization,coastvillage,n5) = true ).
fof(event_91,conjecture,accept_team(christiansufferterrahumanitarianorganization,countryahumanitarianorganization,coastvillage,n6) = true ).
fof(event_92,conjecture,accept_team(christiansufferterrahumanitarianorganization,countryacivilorganization,coastvillage,n6) = true ).
fof(event_93,conjecture,accept_team(christiansufferterrahumanitarianorganization,countryafirstaidorganization,coastvillage,n6) = true ).
fof(event_94,conjecture,the_agent_in_all_proposed_teams(christiansufferterrahumanitarianorganization,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_95,conjecture,any_agent_in_all_proposed_teams(christiansufferterrahumanitarianorganization,christiancountrychumanitarianorganization,coastvillage) = true ).
fof(event_96,conjecture,accept_team(countrycmedicalorganization,christiancountrychumanitarianorganization,coastvillage,n6) = true ).
fof(event_97,conjecture,accept_team(muslimcountrybhumanitarianorganization,christiancountrychumanitarianorganization,coastvillage,n6) = true ).
fof(event_98,conjecture,accept_number(muslimcountrybhumanitarianorganization,n3) = true ).
fof(event_99,conjecture,accept_team(muslimcountrybhumanitarianorganization,countryccivilorganization,townc,n4) = true ).
fof(event_100,conjecture,accept_team(muslimcountrybhumanitarianorganization,countrybcivilorganization,townc,n6) = true ).
fof(event_101,conjecture,accept_team(muslimcountrybhumanitarianorganization,countrybhumanitarianorganization,townc,n6) = true ).
fof(event_102,conjecture,accept_team(muslimcountrybhumanitarianorganization,christiancountrychumanitarianorganization,townc,n6) = true ).
fof(event_103,conjecture,accept_team(muslimcountrybhumanitarianorganization,countrycmedicalorganization,townc,n6) = true ).
fof(event_104,conjecture,the_agent_in_all_proposed_teams(muslimcountrybhumanitarianorganization,countryahumanitarianorganization,townc) = true ).
fof(event_105,conjecture,any_agent_in_all_proposed_teams(muslimcountrybhumanitarianorganization,countryahumanitarianorganization,townc) = true ).
fof(event_106,conjecture,accept_team(countryacivilorganization,countryahumanitarianorganization,townc,n6) = true ).
fof(event_107,conjecture,accept_team(countryafirstaidorganization,countryahumanitarianorganization,townc,n6) = true ).
fof(event_108,conjecture,accept_team(christiancountrychumanitarianorganization,countryccivilorganization,townc,n4) = true ).
fof(event_109,conjecture,accept_team(christiancountrychumanitarianorganization,muslimcountrybhumanitarianorganization,townc,n6) = true ).
fof(event_110,conjecture,accept_team(christiancountrychumanitarianorganization,countrybcivilorganization,townc,n6) = true ).
fof(event_111,conjecture,accept_team(christiancountrychumanitarianorganization,countrybhumanitarianorganization,townc,n6) = true ).
fof(event_112,conjecture,accept_team(christiancountrychumanitarianorganization,countrycmedicalorganization,townc,n6) = true ).
fof(event_113,conjecture,the_agent_in_all_proposed_teams(christiancountrychumanitarianorganization,countryahumanitarianorganization,townc) = true ).
fof(event_114,conjecture,any_agent_in_all_proposed_teams(christiancountrychumanitarianorganization,countryahumanitarianorganization,townc) = true ).
fof(event_120,conjecture,the_agent_in_all_proposed_teams(countryccivilorganization,countryahumanitarianorganization,townc) = true ).
fof(event_121,conjecture,any_agent_in_all_proposed_teams(countryccivilorganization,countryahumanitarianorganization,townc) = true ).
fof(event_122,conjecture,accept_team(countrybhumanitarianorganization,countrybcivilorganization,townc,n2) = true ).
fof(event_123,conjecture,accept_team(countrybhumanitarianorganization,muslimcountrybhumanitarianorganization,townc,n6) = true ).
fof(event_124,conjecture,accept_team(sufferterragovernment,countryahumanitarianorganization,townc,n6) = true ).
fof(event_125,conjecture,accept_team(christiansufferterrahumanitarianorganization,countryahumanitarianorganization,townc,n6) = true ).
fof(event_126,conjecture,accept_team(countryamedicalorganization,countryahumanitarianorganization,townc,n6) = true ).
fof(event_127,conjecture,accept_team(countrycmedicalorganization,countryccivilorganization,townc,n4) = true ).
fof(event_128,conjecture,accept_team(countrycmedicalorganization,muslimcountrybhumanitarianorganization,townc,n6) = true ).
fof(event_129,conjecture,accept_team(countrycmedicalorganization,countrybcivilorganization,townc,n6) = true ).
fof(event_130,conjecture,accept_team(countrycmedicalorganization,countrybhumanitarianorganization,townc,n6) = true ).
fof(event_131,conjecture,accept_team(countrycmedicalorganization,christiancountrychumanitarianorganization,townc,n6) = true ).
fof(event_132,conjecture,the_agent_in_all_proposed_teams(countrycmedicalorganization,countryahumanitarianorganization,townc) = true ).
fof(event_133,conjecture,any_agent_in_all_proposed_teams(countrycmedicalorganization,countryahumanitarianorganization,townc) = true ).
fof(event_134,conjecture,accept_team(countrybhumanitarianorganization,countrybcivilorganization,townc,n6) = true ).
fof(event_135,conjecture,accept_team(countrybhumanitarianorganization,christiancountrychumanitarianorganization,townc,n6) = true ).
fof(event_136,conjecture,accept_team(countrybhumanitarianorganization,countrycmedicalorganization,townc,n6) = true ).
fof(event_137,conjecture,the_agent_in_all_proposed_teams(countrybhumanitarianorganization,countryahumanitarianorganization,townc) = true ).
fof(event_138,conjecture,any_agent_in_all_proposed_teams(countrybhumanitarianorganization,countryahumanitarianorganization,townc) = true ).
fof(event_139,conjecture,accept_team(christiansufferterrahumanitarianorganization,countryahumanitarianorganization,cityb,n6) = true ).
fof(event_140,conjecture,accept_number(christiansufferterrahumanitarianorganization,n6) = true ).
fof(event_141,conjecture,the_agent_in_all_proposed_teams(christiansufferterrahumanitarianorganization,countrybhumanitarianorganization,cityb) = true ).
fof(event_142,conjecture,any_agent_in_all_proposed_teams(christiansufferterrahumanitarianorganization,countrybhumanitarianorganization,cityb) = true ).
fof(event_145,conjecture,accept_team(sufferterragovernment,countryahumanitarianorganization,cityb,n6) = true ).
fof(event_146,conjecture,the_agent_in_all_proposed_teams(sufferterragovernment,countrybhumanitarianorganization,cityb) = true ).
fof(event_147,conjecture,any_agent_in_all_proposed_teams(sufferterragovernment,countrybhumanitarianorganization,cityb) = true ).
fof(event_148,conjecture,accept_team(countryafirstaidorganization,countryahumanitarianorganization,cityb,n6) = true ).
fof(event_149,conjecture,accept_number(countryafirstaidorganization,n6) = true ).
fof(event_150,conjecture,the_agent_in_all_proposed_teams(countryafirstaidorganization,countrybhumanitarianorganization,cityb) = true ).
fof(event_151,conjecture,any_agent_in_all_proposed_teams(countryafirstaidorganization,countrybhumanitarianorganization,cityb) = true ).
fof(event_152,conjecture,accept_team(countryafirstaidorganization,sufferterragovernment,towna,n5) = true ).
fof(event_153,conjecture,accept_team(countryafirstaidorganization,sufferterragovernment,towna,n6) = true ).
fof(event_154,conjecture,accept_team(countrycmedicalorganization,countrybhumanitarianorganization,cityb,n5) = true ).
fof(event_155,conjecture,accept_team(countrycmedicalorganization,countrybhumanitarianorganization,cityb,n6) = true ).
fof(event_156,conjecture,accept_team(countryamedicalorganization,countryahumanitarianorganization,cityb,n6) = true ).
fof(event_157,conjecture,accept_number(countryamedicalorganization,n6) = true ).
fof(event_158,conjecture,the_agent_in_all_proposed_teams(countryamedicalorganization,countrybhumanitarianorganization,cityb) = true ).
fof(event_159,conjecture,any_agent_in_all_proposed_teams(countryamedicalorganization,countrybhumanitarianorganization,cityb) = true ).
fof(event_160,conjecture,accept_team(countrybcivilorganization,countrybhumanitarianorganization,cityb,n5) = true ).
fof(event_161,conjecture,accept_team(countrybcivilorganization,countrybhumanitarianorganization,cityb,n6) = true ).
fof(event_162,conjecture,accept_team(christiancountrychumanitarianorganization,countrybhumanitarianorganization,cityb,n5) = true ).
fof(event_163,conjecture,accept_team(christiancountrychumanitarianorganization,countrybhumanitarianorganization,cityb,n6) = true ).
fof(event_164,conjecture,the_agent_in_all_proposed_teams(countryahumanitarianorganization,countrybhumanitarianorganization,cityb) = true ).
fof(event_165,conjecture,any_agent_in_all_proposed_teams(countryahumanitarianorganization,countrybhumanitarianorganization,cityb) = true ).
fof(event_166,conjecture,accept_number(countryahumanitarianorganization,n6) = true ).
fof(event_167,conjecture,accept_team(countryacivilorganization,countryahumanitarianorganization,cityb,n6) = true ).
fof(event_168,conjecture,accept_number(countryacivilorganization,n6) = true ).
fof(event_169,conjecture,the_agent_in_all_proposed_teams(countryacivilorganization,countrybhumanitarianorganization,cityb) = true ).
fof(event_170,conjecture,any_agent_in_all_proposed_teams(countryacivilorganization,countrybhumanitarianorganization,cityb) = true ).
fof(event_171,conjecture,accept_number(countrybhumanitarianorganization,n5) = true ).
fof(event_172,conjecture,accept_team(muslimcountrybhumanitarianorganization,countrybhumanitarianorganization,cityb,n5) = true ).
fof(event_173,conjecture,accept_team(muslimcountrybhumanitarianorganization,countrybhumanitarianorganization,cityb,n6) = true ).
fof(event_183,conjecture,accept_number(muslimcountrybhumanitarianorganization,n2) = true ).
fof(event_188,conjecture,accept_team(countryamedicalorganization,sufferterragovernment,towna,n5) = true ).
fof(event_189,conjecture,accept_team(countryamedicalorganization,sufferterragovernment,towna,n6) = true ).
fof(event_190,conjecture,accept_team(countryahumanitarianorganization,sufferterragovernment,towna,n5) = true ).
fof(event_191,conjecture,accept_team(countryahumanitarianorganization,sufferterragovernment,towna,n6) = true ).
fof(event_192,conjecture,accept_number(christiancountrychumanitarianorganization,n2) = true ).
fof(event_193,conjecture,accept_team(countrybhumanitarianorganization,countrybcivilorganization,towna,n3) = true ).
fof(event_194,conjecture,accept_team(countrybhumanitarianorganization,christiancountrychumanitarianorganization,towna,n3) = true ).
fof(event_195,conjecture,accept_team(countrybhumanitarianorganization,countrycmedicalorganization,towna,n3) = true ).
fof(event_196,conjecture,accept_team(countrybhumanitarianorganization,countryccivilorganization,towna,n3) = true ).
fof(event_197,conjecture,accept_number(countrybhumanitarianorganization,n2) = true ).
fof(event_198,conjecture,accept_team(countrybhumanitarianorganization,countrybcivilorganization,towna,n6) = true ).
fof(event_199,conjecture,accept_team(countrybhumanitarianorganization,christiancountrychumanitarianorganization,towna,n6) = true ).
fof(event_200,conjecture,accept_team(countrybhumanitarianorganization,countrycmedicalorganization,towna,n6) = true ).
fof(event_201,conjecture,the_agent_in_all_proposed_teams(countrybhumanitarianorganization,sufferterragovernment,towna) = true ).
fof(event_202,conjecture,any_agent_in_all_proposed_teams(countrybhumanitarianorganization,sufferterragovernment,towna) = true ).
fof(event_203,conjecture,accept_number(countrybcivilorganization,n2) = true ).
fof(event_204,conjecture,accept_number(countrybcivilorganization,n3) = true ).
fof(event_205,conjecture,accept_team(countrybcivilorganization,countryccivilorganization,towna,n4) = true ).
fof(event_206,conjecture,accept_team(countrybcivilorganization,countrybhumanitarianorganization,towna,n6) = true ).
fof(event_207,conjecture,accept_team(countrybcivilorganization,christiancountrychumanitarianorganization,towna,n6) = true ).
fof(event_208,conjecture,accept_team(countrybcivilorganization,countrycmedicalorganization,towna,n6) = true ).
fof(event_209,conjecture,the_agent_in_all_proposed_teams(countrybcivilorganization,sufferterragovernment,towna) = true ).
fof(event_210,conjecture,any_agent_in_all_proposed_teams(countrybcivilorganization,sufferterragovernment,towna) = true ).
fof(event_211,conjecture,accept_number(sufferterragovernment,n2) = true ).
fof(event_214,conjecture,accept_number(countryccivilorganization,n2) = true ).
fof(event_215,conjecture,accept_number(countryccivilorganization,n3) = true ).
fof(event_220,conjecture,the_agent_in_all_proposed_teams(countryccivilorganization,sufferterragovernment,towna) = true ).
fof(event_221,conjecture,any_agent_in_all_proposed_teams(countryccivilorganization,sufferterragovernment,towna) = true ).
fof(event_222,conjecture,accept_number(sufferterragovernment,n5) = true ).
fof(event_223,conjecture,accept_team(countryacivilorganization,sufferterragovernment,towna,n5) = true ).
fof(event_224,conjecture,accept_number(sufferterragovernment,n6) = true ).
fof(event_225,conjecture,accept_team(countryacivilorganization,sufferterragovernment,towna,n6) = true ).
fof(event_226,conjecture,accept_number(countrycmedicalorganization,n2) = true ).
fof(event_227,conjecture,accept_number(countrycmedicalorganization,n3) = true ).
fof(event_228,conjecture,accept_team(countrycmedicalorganization,countryccivilorganization,towna,n4) = true ).
fof(event_229,conjecture,accept_team(countrycmedicalorganization,countrybcivilorganization,towna,n6) = true ).
fof(event_230,conjecture,accept_team(countrycmedicalorganization,countrybhumanitarianorganization,towna,n6) = true ).
fof(event_231,conjecture,accept_team(countrycmedicalorganization,christiancountrychumanitarianorganization,towna,n6) = true ).
fof(event_232,conjecture,the_agent_in_all_proposed_teams(countrycmedicalorganization,sufferterragovernment,towna) = true ).
fof(event_233,conjecture,any_agent_in_all_proposed_teams(countrycmedicalorganization,sufferterragovernment,towna) = true ).
fof(event_234,conjecture,accept_number(christiancountrychumanitarianorganization,n3) = true ).
fof(event_235,conjecture,accept_number(countryccivilorganization,n4) = true ).
fof(event_236,conjecture,accept_team(christiancountrychumanitarianorganization,countryccivilorganization,towna,n4) = true ).
fof(event_237,conjecture,accept_number(countrybcivilorganization,n6) = true ).
fof(event_238,conjecture,accept_team(christiancountrychumanitarianorganization,countrybcivilorganization,towna,n6) = true ).
fof(event_239,conjecture,accept_number(countrybhumanitarianorganization,n6) = true ).
fof(event_240,conjecture,accept_team(christiancountrychumanitarianorganization,countrybhumanitarianorganization,towna,n6) = true ).
fof(event_241,conjecture,accept_team(christiancountrychumanitarianorganization,countrycmedicalorganization,towna,n6) = true ).
fof(event_242,conjecture,accept_number(christiancountrychumanitarianorganization,n6) = true ).
fof(event_243,conjecture,the_agent_in_all_proposed_teams(christiancountrychumanitarianorganization,sufferterragovernment,towna) = true ).
fof(event_244,conjecture,any_agent_in_all_proposed_teams(christiancountrychumanitarianorganization,sufferterragovernment,towna) = true ).
fof(event_245,conjecture,accept_number(countrycmedicalorganization,n6) = true ).
fof(event_247,conjecture,accept_number(muslimcountrybhumanitarianorganization,n6) = true ).
fof(event_248,conjecture,the_agent_not_in_any_proposed_teams(muslimcountrybhumanitarianorganization,sufferterragovernment,towna) = true ).
fof(event_249,conjecture,any_agent_in_all_proposed_teams(muslimcountrybhumanitarianorganization,sufferterragovernment,towna) = true ).
fof(deduced_1,conjecture,accept_leader(christiancountrychumanitarianorganization,countryacivilorganization) = true ).
fof(deduced_2,conjecture,accept_leader(christiancountrychumanitarianorganization,muslimcountrybhumanitarianorganization) = true ).
fof(deduced_3,conjecture,accept_population(christiancountrychumanitarianorganization,other,n5) = true ).
fof(deduced_4,conjecture,accept_population(christiancountrychumanitarianorganization,muslim,n65) = true ).
fof(deduced_5,conjecture,accept_population(christiancountrychumanitarianorganization,christian,n0) = true ).
fof(deduced_6,conjecture,accept_population(christiancountrychumanitarianorganization,atheist,n30) = true ).
fof(deduced_7,conjecture,accept_city(christiancountrychumanitarianorganization,townc) = true ).
fof(deduced_8,conjecture,accept_leader(christiancountrychumanitarianorganization,countryahumanitarianorganization) = true ).
fof(deduced_9,conjecture,accept_population(christiancountrychumanitarianorganization,other,n1) = true ).
fof(deduced_10,conjecture,accept_population(christiancountrychumanitarianorganization,christian,n20) = true ).
fof(deduced_11,conjecture,accept_population(christiancountrychumanitarianorganization,atheist,n78) = true ).
fof(deduced_12,conjecture,accept_city(christiancountrychumanitarianorganization,cityb) = true ).
fof(deduced_14,conjecture,accept_leader(countryamedicalorganization,christiancountrychumanitarianorganization) = true ).
fof(deduced_15,conjecture,accept_population(countryamedicalorganization,other,n5) = true ).
fof(deduced_16,conjecture,accept_population(countryamedicalorganization,muslim,n65) = true ).
fof(deduced_17,conjecture,accept_population(countryamedicalorganization,christian,n0) = true ).
fof(deduced_18,conjecture,accept_population(countryamedicalorganization,atheist,n30) = true ).
fof(deduced_19,conjecture,accept_leader(countryamedicalorganization,countryahumanitarianorganization) = true ).
fof(deduced_20,conjecture,accept_city(countryamedicalorganization,townc) = true ).
fof(deduced_21,conjecture,accept_leader(countryahumanitarianorganization,countryamedicalorganization) = true ).
fof(deduced_22,conjecture,accept_leader(countryahumanitarianorganization,countryafirstaidorganization) = true ).
fof(deduced_23,conjecture,accept_population(countryahumanitarianorganization,native,n85) = true ).
fof(deduced_24,conjecture,accept_population(countryahumanitarianorganization,muslim,n0) = true ).
fof(deduced_25,conjecture,accept_population(countryahumanitarianorganization,christian,n3) = true ).
fof(deduced_26,conjecture,accept_population(countryahumanitarianorganization,atheist,n12) = true ).
fof(deduced_27,conjecture,accept_city(countryahumanitarianorganization,coastvillage) = true ).
fof(deduced_28,conjecture,accept_leader(countryahumanitarianorganization,christiancountrychumanitarianorganization) = true ).
fof(deduced_29,conjecture,accept_leader(countryafirstaidorganization,countryamedicalorganization) = true ).
fof(deduced_30,conjecture,accept_leader(christiansufferterrahumanitarianorganization,countryamedicalorganization) = true ).
fof(deduced_31,conjecture,accept_leader(countrycmedicalorganization,countryacivilorganization) = true ).
fof(deduced_32,conjecture,accept_population(countrycmedicalorganization,native,n85) = true ).
fof(deduced_33,conjecture,accept_population(countrycmedicalorganization,muslim,n0) = true ).
fof(deduced_34,conjecture,accept_population(countrycmedicalorganization,christian,n3) = true ).
fof(deduced_35,conjecture,accept_population(countrycmedicalorganization,atheist,n12) = true ).
fof(deduced_36,conjecture,accept_city(countrycmedicalorganization,coastvillage) = true ).
fof(deduced_37,conjecture,accept_leader(countrybcivilorganization,countryacivilorganization) = true ).
fof(deduced_38,conjecture,accept_population(countrybcivilorganization,native,n85) = true ).
fof(deduced_39,conjecture,accept_population(countrybcivilorganization,muslim,n0) = true ).
fof(deduced_40,conjecture,accept_population(countrybcivilorganization,christian,n3) = true ).
fof(deduced_41,conjecture,accept_population(countrybcivilorganization,atheist,n12) = true ).
fof(deduced_42,conjecture,accept_city(countrybcivilorganization,coastvillage) = true ).
fof(deduced_43,conjecture,accept_leader(countrybcivilorganization,muslimcountrybhumanitarianorganization) = true ).
fof(deduced_44,conjecture,accept_population(countrybcivilorganization,other,n5) = true ).
fof(deduced_45,conjecture,accept_population(countrybcivilorganization,muslim,n65) = true ).
fof(deduced_46,conjecture,accept_population(countrybcivilorganization,christian,n0) = true ).
fof(deduced_47,conjecture,accept_population(countrybcivilorganization,atheist,n30) = true ).
fof(deduced_48,conjecture,accept_city(countrybcivilorganization,townc) = true ).
fof(deduced_49,conjecture,accept_leader(countrybcivilorganization,countryahumanitarianorganization) = true ).
fof(deduced_50,conjecture,accept_population(countrybcivilorganization,other,n1) = true ).
fof(deduced_51,conjecture,accept_population(countrybcivilorganization,christian,n20) = true ).
fof(deduced_52,conjecture,accept_population(countrybcivilorganization,atheist,n78) = true ).
fof(deduced_53,conjecture,accept_city(countrybcivilorganization,cityb) = true ).
fof(deduced_54,conjecture,accept_leader(sufferterragovernment,countryamedicalorganization) = true ).
fof(deduced_55,conjecture,accept_population(sufferterragovernment,christian,n24) = true ).
fof(deduced_56,conjecture,accept_population(sufferterragovernment,atheist,n75) = true ).
fof(deduced_57,conjecture,accept_city(sufferterragovernment,towna) = true ).
fof(deduced_59,conjecture,accept_population(countryccivilorganization,other,n1) = true ).
fof(deduced_60,conjecture,accept_population(countryccivilorganization,christian,n20) = true ).
fof(deduced_61,conjecture,accept_population(countryccivilorganization,atheist,n78) = true ).
fof(deduced_63,conjecture,accept_leader(countryccivilorganization,countrybhumanitarianorganization) = true ).
fof(deduced_64,conjecture,accept_city(countryccivilorganization,cityb) = true ).
fof(deduced_65,conjecture,accept_leader(countryccivilorganization,countryacivilorganization) = true ).
fof(deduced_66,conjecture,accept_leader(countryacivilorganization,countryamedicalorganization) = true ).
fof(deduced_67,conjecture,accept_leader(countryacivilorganization,countryafirstaidorganization) = true ).
fof(deduced_68,conjecture,accept_population(countryacivilorganization,native,n85) = true ).
fof(deduced_69,conjecture,accept_population(countryacivilorganization,muslim,n0) = true ).
fof(deduced_70,conjecture,accept_population(countryacivilorganization,christian,n3) = true ).
fof(deduced_71,conjecture,accept_population(countryacivilorganization,atheist,n12) = true ).
fof(deduced_72,conjecture,accept_city(countryacivilorganization,coastvillage) = true ).
fof(deduced_73,conjecture,accept_leader(countryacivilorganization,christiancountrychumanitarianorganization) = true ).
fof(deduced_74,conjecture,accept_population(countryacivilorganization,other,n5) = true ).
fof(deduced_75,conjecture,accept_population(countryacivilorganization,muslim,n65) = true ).
fof(deduced_76,conjecture,accept_population(countryacivilorganization,christian,n0) = true ).
fof(deduced_77,conjecture,accept_population(countryacivilorganization,atheist,n30) = true ).
fof(deduced_78,conjecture,accept_leader(countryacivilorganization,countryahumanitarianorganization) = true ).
fof(deduced_79,conjecture,accept_city(countryacivilorganization,townc) = true ).
fof(deduced_80,conjecture,accept_population(christiansufferterrahumanitarianorganization,christian,n24) = true ).
fof(deduced_81,conjecture,accept_population(christiansufferterrahumanitarianorganization,atheist,n75) = true ).
fof(deduced_83,conjecture,accept_city(christiansufferterrahumanitarianorganization,towna) = true ).
fof(deduced_84,conjecture,accept_leader(christiansufferterrahumanitarianorganization,countryafirstaidorganization) = true ).
fof(deduced_85,conjecture,accept_population(christiansufferterrahumanitarianorganization,other,n0) = true ).
fof(deduced_86,conjecture,accept_population(christiansufferterrahumanitarianorganization,native,n85) = true ).
fof(deduced_87,conjecture,accept_population(christiansufferterrahumanitarianorganization,muslim,n0) = true ).
fof(deduced_88,conjecture,accept_population(christiansufferterrahumanitarianorganization,christian,n3) = true ).
fof(deduced_89,conjecture,accept_population(christiansufferterrahumanitarianorganization,atheist,n12) = true ).
fof(deduced_90,conjecture,accept_city(christiansufferterrahumanitarianorganization,coastvillage) = true ).
fof(deduced_91,conjecture,accept_leader(christiansufferterrahumanitarianorganization,christiancountrychumanitarianorganization) = true ).
fof(deduced_92,conjecture,accept_leader(muslimcountrybhumanitarianorganization,countryacivilorganization) = true ).
fof(deduced_93,conjecture,accept_population(muslimcountrybhumanitarianorganization,other,n0) = true ).
fof(deduced_94,conjecture,accept_population(muslimcountrybhumanitarianorganization,native,n85) = true ).
fof(deduced_95,conjecture,accept_population(muslimcountrybhumanitarianorganization,muslim,n0) = true ).
fof(deduced_96,conjecture,accept_population(muslimcountrybhumanitarianorganization,christian,n3) = true ).
fof(deduced_97,conjecture,accept_population(muslimcountrybhumanitarianorganization,atheist,n12) = true ).
fof(deduced_98,conjecture,accept_city(muslimcountrybhumanitarianorganization,coastvillage) = true ).
fof(deduced_99,conjecture,accept_population(countryafirstaidorganization,native,n85) = true ).
fof(deduced_100,conjecture,accept_population(countryafirstaidorganization,muslim,n0) = true ).
fof(deduced_101,conjecture,accept_population(countryafirstaidorganization,christian,n3) = true ).
fof(deduced_102,conjecture,accept_population(countryafirstaidorganization,atheist,n12) = true ).
fof(deduced_103,conjecture,accept_city(countryafirstaidorganization,coastvillage) = true ).
fof(deduced_104,conjecture,accept_leader(countryafirstaidorganization,christiancountrychumanitarianorganization) = true ).
fof(deduced_105,conjecture,accept_population(countryafirstaidorganization,other,n5) = true ).
fof(deduced_106,conjecture,accept_population(countryafirstaidorganization,muslim,n65) = true ).
fof(deduced_107,conjecture,accept_population(countryafirstaidorganization,christian,n0) = true ).
fof(deduced_108,conjecture,accept_population(countryafirstaidorganization,atheist,n30) = true ).
fof(deduced_109,conjecture,accept_leader(countryafirstaidorganization,countryahumanitarianorganization) = true ).
fof(deduced_110,conjecture,accept_city(countryafirstaidorganization,townc) = true ).
fof(deduced_111,conjecture,accept_leader(countryafirstaidorganization,countryacivilorganization) = true ).
fof(deduced_112,conjecture,accept_population(countryafirstaidorganization,other,n1) = true ).
fof(deduced_113,conjecture,accept_population(countryafirstaidorganization,christian,n20) = true ).
fof(deduced_114,conjecture,accept_population(countryafirstaidorganization,atheist,n78) = true ).
fof(deduced_115,conjecture,accept_city(countryafirstaidorganization,cityb) = true ).
fof(deduced_116,conjecture,accept_leader(countryafirstaidorganization,countrybhumanitarianorganization) = true ).
fof(deduced_117,conjecture,accept_leader(countrybhumanitarianorganization,countryacivilorganization) = true ).
fof(deduced_118,conjecture,accept_population(countrybhumanitarianorganization,native,n85) = true ).
fof(deduced_119,conjecture,accept_population(countrybhumanitarianorganization,muslim,n0) = true ).
fof(deduced_120,conjecture,accept_population(countrybhumanitarianorganization,christian,n3) = true ).
fof(deduced_121,conjecture,accept_population(countrybhumanitarianorganization,atheist,n12) = true ).
fof(deduced_122,conjecture,accept_city(countrybhumanitarianorganization,coastvillage) = true ).
fof(deduced_123,conjecture,accept_leader(countrybhumanitarianorganization,muslimcountrybhumanitarianorganization) = true ).
fof(deduced_124,conjecture,accept_population(countrybhumanitarianorganization,other,n5) = true ).
fof(deduced_125,conjecture,accept_population(countrybhumanitarianorganization,muslim,n65) = true ).
fof(deduced_126,conjecture,accept_population(countrybhumanitarianorganization,christian,n0) = true ).
fof(deduced_127,conjecture,accept_population(countrybhumanitarianorganization,atheist,n30) = true ).
fof(deduced_128,conjecture,accept_city(countrybhumanitarianorganization,townc) = true ).
fof(deduced_129,conjecture,accept_leader(countrybhumanitarianorganization,countryahumanitarianorganization) = true ).
fof(deduced_130,conjecture,accept_leader(countrybhumanitarianorganization,countryccivilorganization) = true ).
fof(deduced_131,conjecture,accept_leader(countrybhumanitarianorganization,countrybcivilorganization) = true ).
fof(deduced_132,conjecture,accept_leader(countrybhumanitarianorganization,christiancountrychumanitarianorganization) = true ).
fof(deduced_133,conjecture,accept_leader(countrybhumanitarianorganization,countrycmedicalorganization) = true ).
fof(deduced_134,conjecture,accept_population(countrybhumanitarianorganization,other,n0) = true ).
fof(deduced_135,conjecture,accept_population(countrybhumanitarianorganization,native,n0) = true ).
fof(deduced_136,conjecture,accept_population(countrybhumanitarianorganization,muslim,n1) = true ).
fof(deduced_137,conjecture,accept_population(countrybhumanitarianorganization,christian,n24) = true ).
fof(deduced_138,conjecture,accept_population(countrybhumanitarianorganization,atheist,n75) = true ).
fof(deduced_139,conjecture,accept_city(countrybhumanitarianorganization,towna) = true ).
fof(deduced_140,conjecture,accept_leader(countrybhumanitarianorganization,sufferterragovernment) = true ).
fof(deduced_141,conjecture,accept_leader(sufferterragovernment,countryafirstaidorganization) = true ).
fof(deduced_142,conjecture,accept_population(sufferterragovernment,other,n0) = true ).
fof(deduced_143,conjecture,accept_population(sufferterragovernment,native,n85) = true ).
fof(deduced_144,conjecture,accept_population(sufferterragovernment,muslim,n0) = true ).
fof(deduced_145,conjecture,accept_population(sufferterragovernment,christian,n3) = true ).
fof(deduced_146,conjecture,accept_population(sufferterragovernment,atheist,n12) = true ).
fof(deduced_147,conjecture,accept_city(sufferterragovernment,coastvillage) = true ).
fof(deduced_148,conjecture,accept_leader(sufferterragovernment,christiancountrychumanitarianorganization) = true ).
fof(deduced_149,conjecture,accept_population(sufferterragovernment,other,n5) = true ).
fof(deduced_150,conjecture,accept_population(sufferterragovernment,muslim,n65) = true ).
fof(deduced_151,conjecture,accept_population(sufferterragovernment,christian,n0) = true ).
fof(deduced_152,conjecture,accept_population(sufferterragovernment,atheist,n30) = true ).
fof(deduced_153,conjecture,accept_leader(sufferterragovernment,countryahumanitarianorganization) = true ).
fof(deduced_154,conjecture,accept_city(sufferterragovernment,townc) = true ).
fof(deduced_155,conjecture,accept_leader(muslimcountrybhumanitarianorganization,countryccivilorganization) = true ).
fof(deduced_156,conjecture,accept_leader(muslimcountrybhumanitarianorganization,countrybcivilorganization) = true ).
fof(deduced_157,conjecture,accept_population(christiansufferterrahumanitarianorganization,other,n5) = true ).
fof(deduced_158,conjecture,accept_population(christiansufferterrahumanitarianorganization,muslim,n65) = true ).
fof(deduced_159,conjecture,accept_population(christiansufferterrahumanitarianorganization,christian,n0) = true ).
fof(deduced_160,conjecture,accept_population(christiansufferterrahumanitarianorganization,atheist,n30) = true ).
fof(deduced_161,conjecture,accept_leader(christiansufferterrahumanitarianorganization,countryahumanitarianorganization) = true ).
fof(deduced_162,conjecture,accept_city(christiansufferterrahumanitarianorganization,townc) = true ).
fof(deduced_163,conjecture,accept_leader(christiansufferterrahumanitarianorganization,countryacivilorganization) = true ).
fof(deduced_164,conjecture,accept_number(christiansufferterrahumanitarianorganization,n5) = true ).
fof(deduced_165,conjecture,accept_number(christiansufferterrahumanitarianorganization,n4) = true ).
fof(deduced_166,conjecture,accept_number(christiansufferterrahumanitarianorganization,n3) = true ).
fof(deduced_167,conjecture,accept_number(christiansufferterrahumanitarianorganization,n2) = true ).
fof(deduced_168,conjecture,accept_number(christiansufferterrahumanitarianorganization,n1) = true ).
fof(deduced_169,conjecture,accept_number(christiansufferterrahumanitarianorganization,n6) = true ).
fof(deduced_170,conjecture,accept_population(christiansufferterrahumanitarianorganization,other,n1) = true ).
fof(deduced_171,conjecture,accept_population(christiansufferterrahumanitarianorganization,native,n0) = true ).
fof(deduced_172,conjecture,accept_population(christiansufferterrahumanitarianorganization,muslim,n1) = true ).
fof(deduced_173,conjecture,accept_population(christiansufferterrahumanitarianorganization,christian,n20) = true ).
fof(deduced_174,conjecture,accept_population(christiansufferterrahumanitarianorganization,atheist,n78) = true ).
fof(deduced_175,conjecture,accept_city(christiansufferterrahumanitarianorganization,cityb) = true ).
fof(deduced_176,conjecture,accept_leader(christiansufferterrahumanitarianorganization,countrybhumanitarianorganization) = true ).
fof(deduced_177,conjecture,accept_population(countryccivilorganization,other,n5) = true ).
fof(deduced_178,conjecture,accept_population(countryccivilorganization,muslim,n65) = true ).
fof(deduced_179,conjecture,accept_population(countryccivilorganization,christian,n0) = true ).
fof(deduced_180,conjecture,accept_population(countryccivilorganization,atheist,n30) = true ).
fof(deduced_181,conjecture,accept_city(countryccivilorganization,townc) = true ).
fof(deduced_182,conjecture,accept_leader(countryccivilorganization,countryahumanitarianorganization) = true ).
fof(deduced_183,conjecture,accept_leader(countrycmedicalorganization,muslimcountrybhumanitarianorganization) = true ).
fof(deduced_184,conjecture,accept_population(countrycmedicalorganization,other,n5) = true ).
fof(deduced_185,conjecture,accept_population(countrycmedicalorganization,muslim,n65) = true ).
fof(deduced_186,conjecture,accept_population(countrycmedicalorganization,christian,n0) = true ).
fof(deduced_187,conjecture,accept_population(countrycmedicalorganization,atheist,n30) = true ).
fof(deduced_188,conjecture,accept_city(countrycmedicalorganization,townc) = true ).
fof(deduced_189,conjecture,accept_leader(countrycmedicalorganization,countryahumanitarianorganization) = true ).
fof(deduced_190,conjecture,accept_population(countrycmedicalorganization,other,n1) = true ).
fof(deduced_191,conjecture,accept_population(countrycmedicalorganization,christian,n20) = true ).
fof(deduced_192,conjecture,accept_population(countrycmedicalorganization,atheist,n78) = true ).
fof(deduced_193,conjecture,accept_city(countrycmedicalorganization,cityb) = true ).
fof(deduced_194,conjecture,accept_leader(muslimcountrybhumanitarianorganization,countrycmedicalorganization) = true ).
fof(deduced_195,conjecture,accept_leader(muslimcountrybhumanitarianorganization,christiancountrychumanitarianorganization) = true ).
fof(deduced_196,conjecture,accept_population(muslimcountrybhumanitarianorganization,other,n5) = true ).
fof(deduced_197,conjecture,accept_population(muslimcountrybhumanitarianorganization,muslim,n65) = true ).
fof(deduced_198,conjecture,accept_population(muslimcountrybhumanitarianorganization,christian,n0) = true ).
fof(deduced_199,conjecture,accept_population(muslimcountrybhumanitarianorganization,atheist,n30) = true ).
fof(deduced_200,conjecture,accept_city(muslimcountrybhumanitarianorganization,townc) = true ).
fof(deduced_201,conjecture,accept_leader(muslimcountrybhumanitarianorganization,countryahumanitarianorganization) = true ).
fof(deduced_202,conjecture,accept_population(muslimcountrybhumanitarianorganization,other,n1) = true ).
fof(deduced_203,conjecture,accept_population(muslimcountrybhumanitarianorganization,native,n0) = true ).
fof(deduced_204,conjecture,accept_population(muslimcountrybhumanitarianorganization,muslim,n1) = true ).
fof(deduced_205,conjecture,accept_population(muslimcountrybhumanitarianorganization,christian,n20) = true ).
fof(deduced_206,conjecture,accept_population(muslimcountrybhumanitarianorganization,atheist,n78) = true ).
fof(deduced_207,conjecture,accept_leader(muslimcountrybhumanitarianorganization,countrybhumanitarianorganization) = true ).
fof(deduced_208,conjecture,accept_city(muslimcountrybhumanitarianorganization,cityb) = true ).
fof(deduced_209,conjecture,accept_leader(countryamedicalorganization,countryacivilorganization) = true ).
fof(deduced_210,conjecture,accept_population(countryamedicalorganization,other,n1) = true ).
fof(deduced_211,conjecture,accept_population(countryamedicalorganization,christian,n20) = true ).
fof(deduced_212,conjecture,accept_population(countryamedicalorganization,atheist,n78) = true ).
fof(deduced_213,conjecture,accept_city(countryamedicalorganization,cityb) = true ).
fof(deduced_214,conjecture,accept_leader(countryamedicalorganization,countrybhumanitarianorganization) = true ).
fof(deduced_215,conjecture,accept_number(countryamedicalorganization,n5) = true ).
fof(deduced_216,conjecture,accept_number(countryamedicalorganization,n4) = true ).
fof(deduced_217,conjecture,accept_number(countryamedicalorganization,n3) = true ).
fof(deduced_218,conjecture,accept_number(countryamedicalorganization,n2) = true ).
fof(deduced_219,conjecture,accept_number(countryamedicalorganization,n1) = true ).
fof(deduced_220,conjecture,accept_population(countryamedicalorganization,other,n0) = true ).
fof(deduced_221,conjecture,accept_population(countryamedicalorganization,native,n0) = true ).
fof(deduced_222,conjecture,accept_population(countryamedicalorganization,muslim,n1) = true ).
fof(deduced_223,conjecture,accept_population(countryamedicalorganization,christian,n24) = true ).
fof(deduced_224,conjecture,accept_population(countryamedicalorganization,atheist,n75) = true ).
fof(deduced_225,conjecture,accept_number(countryamedicalorganization,n6) = true ).
fof(deduced_226,conjecture,accept_leader(countryamedicalorganization,sufferterragovernment) = true ).
fof(deduced_227,conjecture,accept_city(countryamedicalorganization,towna) = true ).
fof(deduced_228,conjecture,accept_population(countryacivilorganization,other,n1) = true ).
fof(deduced_229,conjecture,accept_population(countryacivilorganization,christian,n20) = true ).
fof(deduced_230,conjecture,accept_population(countryacivilorganization,atheist,n78) = true ).
fof(deduced_231,conjecture,accept_city(countryacivilorganization,cityb) = true ).
fof(deduced_232,conjecture,accept_leader(countryacivilorganization,countrybhumanitarianorganization) = true ).
fof(deduced_233,conjecture,accept_leader(countryahumanitarianorganization,countryacivilorganization) = true ).
fof(deduced_234,conjecture,accept_population(countryahumanitarianorganization,other,n1) = true ).
fof(deduced_235,conjecture,accept_population(countryahumanitarianorganization,christian,n20) = true ).
fof(deduced_236,conjecture,accept_population(countryahumanitarianorganization,atheist,n78) = true ).
fof(deduced_237,conjecture,accept_city(countryahumanitarianorganization,cityb) = true ).
fof(deduced_238,conjecture,accept_leader(countryahumanitarianorganization,countrybhumanitarianorganization) = true ).
fof(deduced_239,conjecture,accept_number(countryahumanitarianorganization,n5) = true ).
fof(deduced_240,conjecture,accept_number(countryahumanitarianorganization,n4) = true ).
fof(deduced_241,conjecture,accept_number(countryahumanitarianorganization,n3) = true ).
fof(deduced_242,conjecture,accept_number(countryahumanitarianorganization,n2) = true ).
fof(deduced_243,conjecture,accept_number(countryahumanitarianorganization,n1) = true ).
fof(deduced_244,conjecture,accept_population(countryahumanitarianorganization,other,n0) = true ).
fof(deduced_245,conjecture,accept_population(countryahumanitarianorganization,native,n0) = true ).
fof(deduced_246,conjecture,accept_population(countryahumanitarianorganization,muslim,n1) = true ).
fof(deduced_247,conjecture,accept_population(countryahumanitarianorganization,christian,n24) = true ).
fof(deduced_248,conjecture,accept_population(countryahumanitarianorganization,atheist,n75) = true ).
fof(deduced_249,conjecture,accept_number(countryahumanitarianorganization,n6) = true ).
fof(deduced_250,conjecture,accept_leader(countryahumanitarianorganization,sufferterragovernment) = true ).
fof(deduced_251,conjecture,accept_city(countryahumanitarianorganization,towna) = true ).
fof(deduced_252,conjecture,accept_leader(sufferterragovernment,countryacivilorganization) = true ).
fof(deduced_253,conjecture,accept_population(sufferterragovernment,other,n1) = true ).
fof(deduced_254,conjecture,accept_population(sufferterragovernment,native,n0) = true ).
fof(deduced_255,conjecture,accept_population(sufferterragovernment,muslim,n1) = true ).
fof(deduced_256,conjecture,accept_population(sufferterragovernment,christian,n20) = true ).
fof(deduced_257,conjecture,accept_population(sufferterragovernment,atheist,n78) = true ).
fof(deduced_258,conjecture,accept_city(sufferterragovernment,cityb) = true ).
fof(deduced_259,conjecture,accept_leader(sufferterragovernment,countrybhumanitarianorganization) = true ).
fof(deduced_260,conjecture,accept_population(countryccivilorganization,other,n0) = true ).
fof(deduced_261,conjecture,accept_population(countryccivilorganization,native,n0) = true ).
fof(deduced_262,conjecture,accept_population(countryccivilorganization,muslim,n1) = true ).
fof(deduced_263,conjecture,accept_population(countryccivilorganization,christian,n24) = true ).
fof(deduced_264,conjecture,accept_population(countryccivilorganization,atheist,n75) = true ).
fof(deduced_265,conjecture,accept_city(countryccivilorganization,towna) = true ).
fof(deduced_266,conjecture,accept_leader(countryccivilorganization,sufferterragovernment) = true ).
fof(deduced_267,conjecture,accept_number(countryafirstaidorganization,n5) = true ).
fof(deduced_268,conjecture,accept_number(countryafirstaidorganization,n4) = true ).
fof(deduced_269,conjecture,accept_number(countryafirstaidorganization,n3) = true ).
fof(deduced_270,conjecture,accept_number(countryafirstaidorganization,n2) = true ).
fof(deduced_271,conjecture,accept_number(countryafirstaidorganization,n1) = true ).
fof(deduced_272,conjecture,accept_population(countryafirstaidorganization,other,n0) = true ).
fof(deduced_273,conjecture,accept_population(countryafirstaidorganization,native,n0) = true ).
fof(deduced_274,conjecture,accept_population(countryafirstaidorganization,muslim,n1) = true ).
fof(deduced_275,conjecture,accept_population(countryafirstaidorganization,christian,n24) = true ).
fof(deduced_276,conjecture,accept_population(countryafirstaidorganization,atheist,n75) = true ).
fof(deduced_277,conjecture,accept_number(countryafirstaidorganization,n6) = true ).
fof(deduced_278,conjecture,accept_leader(countryafirstaidorganization,sufferterragovernment) = true ).
fof(deduced_279,conjecture,accept_city(countryafirstaidorganization,towna) = true ).
fof(deduced_280,conjecture,accept_leader(countrycmedicalorganization,countryccivilorganization) = true ).
fof(deduced_281,conjecture,accept_leader(countrycmedicalorganization,countrybcivilorganization) = true ).
fof(deduced_282,conjecture,accept_leader(countrycmedicalorganization,countrybhumanitarianorganization) = true ).
fof(deduced_283,conjecture,accept_leader(countrycmedicalorganization,christiancountrychumanitarianorganization) = true ).
fof(deduced_284,conjecture,accept_population(countrycmedicalorganization,other,n0) = true ).
fof(deduced_285,conjecture,accept_population(countrycmedicalorganization,native,n0) = true ).
fof(deduced_286,conjecture,accept_population(countrycmedicalorganization,muslim,n1) = true ).
fof(deduced_287,conjecture,accept_population(countrycmedicalorganization,christian,n24) = true ).
fof(deduced_288,conjecture,accept_population(countrycmedicalorganization,atheist,n75) = true ).
fof(deduced_289,conjecture,accept_city(countrycmedicalorganization,towna) = true ).
fof(deduced_290,conjecture,accept_leader(countrycmedicalorganization,sufferterragovernment) = true ).
fof(deduced_291,conjecture,accept_leader(countrybcivilorganization,countryccivilorganization) = true ).
fof(deduced_292,conjecture,accept_leader(countrybcivilorganization,countrybhumanitarianorganization) = true ).
fof(deduced_293,conjecture,accept_leader(countrybcivilorganization,christiancountrychumanitarianorganization) = true ).
fof(deduced_294,conjecture,accept_leader(countrybcivilorganization,countrycmedicalorganization) = true ).
fof(deduced_295,conjecture,accept_population(countrybcivilorganization,other,n0) = true ).
fof(deduced_296,conjecture,accept_population(countrybcivilorganization,native,n0) = true ).
fof(deduced_297,conjecture,accept_population(countrybcivilorganization,muslim,n1) = true ).
fof(deduced_298,conjecture,accept_population(countrybcivilorganization,christian,n24) = true ).
fof(deduced_299,conjecture,accept_population(countrybcivilorganization,atheist,n75) = true ).
fof(deduced_300,conjecture,accept_city(countrybcivilorganization,towna) = true ).
fof(deduced_301,conjecture,accept_leader(countrybcivilorganization,sufferterragovernment) = true ).
fof(deduced_302,conjecture,accept_number(sufferterragovernment,n5) = true ).
fof(deduced_303,conjecture,accept_number(sufferterragovernment,n4) = true ).
fof(deduced_304,conjecture,accept_number(sufferterragovernment,n3) = true ).
fof(deduced_305,conjecture,accept_number(sufferterragovernment,n2) = true ).
fof(deduced_306,conjecture,accept_number(sufferterragovernment,n1) = true ).
fof(deduced_307,conjecture,accept_number(sufferterragovernment,n6) = true ).
fof(deduced_308,conjecture,accept_number(countryacivilorganization,n5) = true ).
fof(deduced_309,conjecture,accept_number(countryacivilorganization,n4) = true ).
fof(deduced_310,conjecture,accept_number(countryacivilorganization,n3) = true ).
fof(deduced_311,conjecture,accept_number(countryacivilorganization,n2) = true ).
fof(deduced_312,conjecture,accept_number(countryacivilorganization,n1) = true ).
fof(deduced_313,conjecture,accept_population(countryacivilorganization,other,n0) = true ).
fof(deduced_314,conjecture,accept_population(countryacivilorganization,native,n0) = true ).
fof(deduced_315,conjecture,accept_population(countryacivilorganization,muslim,n1) = true ).
fof(deduced_316,conjecture,accept_population(countryacivilorganization,christian,n24) = true ).
fof(deduced_317,conjecture,accept_population(countryacivilorganization,atheist,n75) = true ).
fof(deduced_318,conjecture,accept_number(countryacivilorganization,n6) = true ).
fof(deduced_319,conjecture,accept_leader(countryacivilorganization,sufferterragovernment) = true ).
fof(deduced_320,conjecture,accept_city(countryacivilorganization,towna) = true ).
fof(deduced_321,conjecture,accept_number(countryccivilorganization,n3) = true ).
fof(deduced_322,conjecture,accept_number(countryccivilorganization,n2) = true ).
fof(deduced_323,conjecture,accept_number(countryccivilorganization,n1) = true ).
fof(deduced_324,conjecture,accept_number(countryccivilorganization,n4) = true ).
fof(deduced_325,conjecture,accept_leader(christiancountrychumanitarianorganization,countryccivilorganization) = true ).
fof(deduced_326,conjecture,accept_number(countrybcivilorganization,n5) = true ).
fof(deduced_327,conjecture,accept_number(countrybcivilorganization,n4) = true ).
fof(deduced_328,conjecture,accept_number(countrybcivilorganization,n3) = true ).
fof(deduced_329,conjecture,accept_number(countrybcivilorganization,n2) = true ).
fof(deduced_330,conjecture,accept_number(countrybcivilorganization,n1) = true ).
fof(deduced_331,conjecture,accept_number(countrybcivilorganization,n6) = true ).
fof(deduced_332,conjecture,accept_leader(christiancountrychumanitarianorganization,countrybcivilorganization) = true ).
fof(deduced_333,conjecture,accept_number(countrybhumanitarianorganization,n5) = true ).
fof(deduced_334,conjecture,accept_number(countrybhumanitarianorganization,n4) = true ).
fof(deduced_335,conjecture,accept_number(countrybhumanitarianorganization,n3) = true ).
fof(deduced_336,conjecture,accept_number(countrybhumanitarianorganization,n2) = true ).
fof(deduced_337,conjecture,accept_number(countrybhumanitarianorganization,n1) = true ).
fof(deduced_338,conjecture,accept_number(countrybhumanitarianorganization,n6) = true ).
fof(deduced_339,conjecture,accept_leader(christiancountrychumanitarianorganization,countrybhumanitarianorganization) = true ).
fof(deduced_340,conjecture,accept_leader(christiancountrychumanitarianorganization,countrycmedicalorganization) = true ).
fof(deduced_341,conjecture,accept_number(christiancountrychumanitarianorganization,n5) = true ).
fof(deduced_342,conjecture,accept_number(christiancountrychumanitarianorganization,n4) = true ).
fof(deduced_343,conjecture,accept_number(christiancountrychumanitarianorganization,n3) = true ).
fof(deduced_344,conjecture,accept_number(christiancountrychumanitarianorganization,n2) = true ).
fof(deduced_345,conjecture,accept_number(christiancountrychumanitarianorganization,n1) = true ).
fof(deduced_346,conjecture,accept_number(christiancountrychumanitarianorganization,n6) = true ).
fof(deduced_347,conjecture,accept_population(christiancountrychumanitarianorganization,other,n0) = true ).
fof(deduced_348,conjecture,accept_population(christiancountrychumanitarianorganization,native,n0) = true ).
fof(deduced_349,conjecture,accept_population(christiancountrychumanitarianorganization,muslim,n1) = true ).
fof(deduced_350,conjecture,accept_population(christiancountrychumanitarianorganization,christian,n24) = true ).
fof(deduced_351,conjecture,accept_population(christiancountrychumanitarianorganization,atheist,n75) = true ).
fof(deduced_352,conjecture,accept_city(christiancountrychumanitarianorganization,towna) = true ).
fof(deduced_353,conjecture,accept_leader(christiancountrychumanitarianorganization,sufferterragovernment) = true ).
fof(deduced_354,conjecture,accept_number(countrycmedicalorganization,n5) = true ).
fof(deduced_355,conjecture,accept_number(countrycmedicalorganization,n4) = true ).
fof(deduced_356,conjecture,accept_number(countrycmedicalorganization,n3) = true ).
fof(deduced_357,conjecture,accept_number(countrycmedicalorganization,n2) = true ).
fof(deduced_358,conjecture,accept_number(countrycmedicalorganization,n1) = true ).
fof(deduced_359,conjecture,accept_number(countrycmedicalorganization,n6) = true ).
fof(deduced_360,conjecture,accept_number(muslimcountrybhumanitarianorganization,n5) = true ).
fof(deduced_361,conjecture,accept_number(muslimcountrybhumanitarianorganization,n4) = true ).
fof(deduced_362,conjecture,accept_number(muslimcountrybhumanitarianorganization,n3) = true ).
fof(deduced_363,conjecture,accept_number(muslimcountrybhumanitarianorganization,n2) = true ).
fof(deduced_364,conjecture,accept_number(muslimcountrybhumanitarianorganization,n1) = true ).
fof(deduced_365,conjecture,accept_number(muslimcountrybhumanitarianorganization,n6) = true ).
fof(deduced_367,conjecture,accept_leader(muslimcountrybhumanitarianorganization,sufferterragovernment) = true ).
fof(a1_6,conjecture,! [A] : ! [C] : ! [L] : ifeq(tuple(accept_city(A,C),accept_leader(A,L),the_agent_not_in_any_proposed_teams(A,L,C)),tuple(true,true,true),a,b) = b ).
fof(event_9,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countrycmedicalorganization,towna,n4),true,a,b) = b ).
fof(event_10,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countrycmedicalorganization,towna,n5),true,a,b) = b ).
fof(event_29,conjecture,ifeq2(accept_team(countryamedicalorganization,countryahumanitarianorganization,coastvillage,n2),true,a,b) = b ).
fof(event_30,conjecture,ifeq2(accept_team(countryamedicalorganization,countryafirstaidorganization,coastvillage,n2),true,a,b) = b ).
fof(event_31,conjecture,ifeq2(accept_team(countryamedicalorganization,countryacivilorganization,coastvillage,n2),true,a,b) = b ).
fof(event_32,conjecture,ifeq2(accept_team(countryamedicalorganization,christiansufferterrahumanitarianorganization,coastvillage,n2),true,a,b) = b ).
fof(event_33,conjecture,ifeq2(accept_team(countryamedicalorganization,sufferterragovernment,coastvillage,n2),true,a,b) = b ).
fof(event_34,conjecture,ifeq2(accept_team(countryamedicalorganization,countryahumanitarianorganization,coastvillage,n6),true,a,b) = b ).
fof(event_35,conjecture,ifeq2(accept_team(countryamedicalorganization,countryacivilorganization,coastvillage,n6),true,a,b) = b ).
fof(event_36,conjecture,ifeq2(accept_team(countryamedicalorganization,countryafirstaidorganization,coastvillage,n6),true,a,b) = b ).
fof(event_40,conjecture,ifeq2(accept_team(countryccivilorganization,countrycmedicalorganization,towna,n5),true,a,b) = b ).
fof(event_71,conjecture,ifeq2(accept_team(countryccivilorganization,christiancountrychumanitarianorganization,coastvillage,n5),true,a,b) = b ).
fof(event_72,conjecture,ifeq2(accept_team(countryccivilorganization,christiancountrychumanitarianorganization,coastvillage,n6),true,a,b) = b ).
fof(event_115,conjecture,ifeq2(accept_team(countryccivilorganization,muslimcountrybhumanitarianorganization,townc,n6),true,a,b) = b ).
fof(event_116,conjecture,ifeq2(accept_team(countryccivilorganization,countrybcivilorganization,townc,n6),true,a,b) = b ).
fof(event_117,conjecture,ifeq2(accept_team(countryccivilorganization,countrybhumanitarianorganization,townc,n6),true,a,b) = b ).
fof(event_118,conjecture,ifeq2(accept_team(countryccivilorganization,christiancountrychumanitarianorganization,townc,n6),true,a,b) = b ).
fof(event_119,conjecture,ifeq2(accept_team(countryccivilorganization,countrycmedicalorganization,townc,n6),true,a,b) = b ).
fof(event_143,conjecture,ifeq2(accept_team(countryccivilorganization,countrybhumanitarianorganization,cityb,n5),true,a,b) = b ).
fof(event_144,conjecture,ifeq2(accept_team(countryccivilorganization,countrybhumanitarianorganization,cityb,n6),true,a,b) = b ).
fof(event_174,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countrybcivilorganization,towna,n2),true,a,b) = b ).
fof(event_175,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countrycmedicalorganization,towna,n2),true,a,b) = b ).
fof(event_176,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,christiancountrychumanitarianorganization,towna,n2),true,a,b) = b ).
fof(event_177,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countryccivilorganization,towna,n2),true,a,b) = b ).
fof(event_178,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countrybcivilorganization,towna,n3),true,a,b) = b ).
fof(event_179,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,christiancountrychumanitarianorganization,towna,n3),true,a,b) = b ).
fof(event_180,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countrycmedicalorganization,towna,n3),true,a,b) = b ).
fof(event_181,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countryccivilorganization,towna,n3),true,a,b) = b ).
fof(event_182,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countrybhumanitarianorganization,towna,n2),true,a,b) = b ).
fof(event_184,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countryccivilorganization,towna,n4),true,a,b) = b ).
fof(event_185,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countrybcivilorganization,towna,n6),true,a,b) = b ).
fof(event_186,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countrybhumanitarianorganization,towna,n6),true,a,b) = b ).
fof(event_187,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,christiancountrychumanitarianorganization,towna,n6),true,a,b) = b ).
fof(event_212,conjecture,ifeq2(accept_team(christiansufferterrahumanitarianorganization,sufferterragovernment,towna,n2),true,a,b) = b ).
fof(event_213,conjecture,ifeq2(accept_team(christiansufferterrahumanitarianorganization,sufferterragovernment,towna,n6),true,a,b) = b ).
fof(event_216,conjecture,ifeq2(accept_team(countryccivilorganization,countrybcivilorganization,towna,n6),true,a,b) = b ).
fof(event_217,conjecture,ifeq2(accept_team(countryccivilorganization,countrybhumanitarianorganization,towna,n6),true,a,b) = b ).
fof(event_218,conjecture,ifeq2(accept_team(countryccivilorganization,christiancountrychumanitarianorganization,towna,n6),true,a,b) = b ).
fof(event_219,conjecture,ifeq2(accept_team(countryccivilorganization,countrycmedicalorganization,towna,n6),true,a,b) = b ).
fof(event_246,conjecture,ifeq2(accept_team(muslimcountrybhumanitarianorganization,countrycmedicalorganization,towna,n6),true,a,b) = b ).
fof(deduced_13,conjecture,ifeq2(accept_city(countryamedicalorganization,coastvillage),true,a,b) = b ).
fof(deduced_58,conjecture,ifeq2(accept_number(countryccivilorganization,n5),true,a,b) = b ).
fof(deduced_62,conjecture,ifeq2(accept_number(countryccivilorganization,n6),true,a,b) = b ).
fof(deduced_82,conjecture,ifeq2(accept_leader(christiansufferterrahumanitarianorganization,sufferterragovernment),true,a,b) = b ).
fof(deduced_366,conjecture,ifeq2(accept_city(muslimcountrybhumanitarianorganization,towna),true,a,b) = b ).
fof(goal,conjecture,a != b ).
