fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq3(A,A,B,C) = B ).
fof(ifeq_axiom_001,conjecture,! [A] : ! [B] : ! [C] : ifeq2(A,A,B,C) = B ).
fof(ifeq_axiom_002,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(clause1,conjecture,! [U] : ! [V] : ifeq2(smoke(U,V),true,event(U,V),true) = true ).
fof(clause2,conjecture,! [U] : ! [V] : ifeq2(event(U,V),true,eventuality(U,V),true) = true ).
fof(clause3,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,thing(U,V),true) = true ).
fof(clause4,conjecture,! [U] : ! [V] : ifeq2(thing(U,V),true,singleton(U,V),true) = true ).
fof(clause5,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,specific(U,V),true) = true ).
fof(clause6,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,nonexistent(U,V),true) = true ).
fof(clause7,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,unisex(U,V),true) = true ).
fof(clause8,conjecture,! [U] : ! [V] : ifeq2(proposition(U,V),true,relation(U,V),true) = true ).
fof(clause9,conjecture,! [U] : ! [V] : ifeq2(relation(U,V),true,abstraction(U,V),true) = true ).
fof(clause10,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,thing(U,V),true) = true ).
fof(clause11,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,nonhuman(U,V),true) = true ).
fof(clause12,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,general(U,V),true) = true ).
fof(clause13,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,unisex(U,V),true) = true ).
fof(clause14,conjecture,! [U] : ! [V] : ifeq2(state(U,V),true,eventuality(U,V),true) = true ).
fof(clause15,conjecture,! [U] : ! [V] : ifeq2(state(U,V),true,event(U,V),true) = true ).
fof(clause16,conjecture,! [U] : ! [V] : ifeq2(man(U,V),true,human_person(U,V),true) = true ).
fof(clause17,conjecture,! [U] : ! [V] : ifeq2(human_person(U,V),true,organism(U,V),true) = true ).
fof(clause18,conjecture,! [U] : ! [V] : ifeq2(organism(U,V),true,entity(U,V),true) = true ).
fof(clause19,conjecture,! [U] : ! [V] : ifeq2(entity(U,V),true,thing(U,V),true) = true ).
fof(clause20,conjecture,! [U] : ! [V] : ifeq2(entity(U,V),true,specific(U,V),true) = true ).
fof(clause21,conjecture,! [U] : ! [V] : ifeq2(entity(U,V),true,existent(U,V),true) = true ).
fof(clause22,conjecture,! [U] : ! [V] : ifeq2(organism(U,V),true,impartial(U,V),true) = true ).
fof(clause23,conjecture,! [U] : ! [V] : ifeq2(organism(U,V),true,living(U,V),true) = true ).
fof(clause24,conjecture,! [U] : ! [V] : ifeq2(human_person(U,V),true,human(U,V),true) = true ).
fof(clause25,conjecture,! [U] : ! [V] : ifeq2(human_person(U,V),true,animate(U,V),true) = true ).
fof(clause26,conjecture,! [U] : ! [V] : ifeq2(man(U,V),true,male(U,V),true) = true ).
fof(clause27,conjecture,! [U] : ! [V] : ifeq2(forename(U,V),true,relname(U,V),true) = true ).
fof(clause28,conjecture,! [U] : ! [V] : ifeq2(relname(U,V),true,relation(U,V),true) = true ).
fof(clause29,conjecture,! [U] : ! [V] : ifeq2(vincent_forename(U,V),true,forename(U,V),true) = true ).
fof(clause30,conjecture,! [U] : ! [V] : ifeq2(jules_forename(U,V),true,forename(U,V),true) = true ).
fof(clause35,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ifeq3(be(U,V,W,X),true,W,X) = X ).
fof(clause36,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(smoke(U,W),true,smoke(V,W),true),true) = true ).
fof(clause37,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(event(U,W),true,event(V,W),true),true) = true ).
fof(clause38,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(eventuality(U,W),true,eventuality(V,W),true),true) = true ).
fof(clause39,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(thing(U,W),true,thing(V,W),true),true) = true ).
fof(clause40,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(singleton(U,W),true,singleton(V,W),true),true) = true ).
fof(clause41,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(specific(U,W),true,specific(V,W),true),true) = true ).
fof(clause42,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(nonexistent(U,W),true,nonexistent(V,W),true),true) = true ).
fof(clause43,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(unisex(U,W),true,unisex(V,W),true),true) = true ).
fof(clause44,conjecture,! [U] : ! [W] : ! [V] : ifeq2(present(U,W),true,ifeq2(accessible_world(U,V),true,present(V,W),true),true) = true ).
fof(clause45,conjecture,! [U] : ! [W] : ! [V] : ifeq2(think_believe_consider(U,W),true,ifeq2(accessible_world(U,V),true,think_believe_consider(V,W),true),true) = true ).
fof(clause46,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(proposition(U,W),true,proposition(V,W),true),true) = true ).
fof(clause47,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(relation(U,W),true,relation(V,W),true),true) = true ).
fof(clause48,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(abstraction(U,W),true,abstraction(V,W),true),true) = true ).
fof(clause49,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(nonhuman(U,W),true,nonhuman(V,W),true),true) = true ).
fof(clause50,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(general(U,W),true,general(V,W),true),true) = true ).
fof(clause51,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(state(U,W),true,state(V,W),true),true) = true ).
fof(clause52,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(man(U,W),true,man(V,W),true),true) = true ).
fof(clause53,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(human_person(U,W),true,human_person(V,W),true),true) = true ).
fof(clause54,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(organism(U,W),true,organism(V,W),true),true) = true ).
fof(clause55,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(entity(U,W),true,entity(V,W),true),true) = true ).
fof(clause56,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(existent(U,W),true,existent(V,W),true),true) = true ).
fof(clause57,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(impartial(U,W),true,impartial(V,W),true),true) = true ).
fof(clause58,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(living(U,W),true,living(V,W),true),true) = true ).
fof(clause59,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(human(U,W),true,human(V,W),true),true) = true ).
fof(clause60,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(animate(U,W),true,animate(V,W),true),true) = true ).
fof(clause61,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(male(U,W),true,male(V,W),true),true) = true ).
fof(clause62,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(forename(U,W),true,forename(V,W),true),true) = true ).
fof(clause63,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(relname(U,W),true,relname(V,W),true),true) = true ).
fof(clause64,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(vincent_forename(U,W),true,vincent_forename(V,W),true),true) = true ).
fof(clause65,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(jules_forename(U,W),true,jules_forename(V,W),true),true) = true ).
fof(clause66,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq2(agent(U,W,X),true,ifeq2(accessible_world(U,V),true,agent(V,W,X),true),true) = true ).
fof(clause67,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq2(theme(U,W,X),true,ifeq2(accessible_world(U,V),true,theme(V,W,X),true),true) = true ).
fof(clause68,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq2(of(U,W,X),true,ifeq2(accessible_world(U,V),true,of(V,W,X),true),true) = true ).
fof(clause69,conjecture,! [U] : ! [W] : ! [X] : ! [Y] : ! [V] : ifeq2(be(U,W,X,Y),true,ifeq2(accessible_world(U,V),true,be(V,W,X,Y),true),true) = true ).
fof(clause70,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq3(of(U,W,X),true,ifeq3(of(U,V,X),true,ifeq3(forename(U,W),true,ifeq3(forename(U,V),true,ifeq3(entity(U,X),true,W,V),V),V),V),V) = V ).
fof(clause71,conjecture,! [U] : ! [Y] : ! [W] : ! [X] : ! [V] : ! [Z] : ifeq3(theme(U,Y,W),true,ifeq3(theme(U,X,V),true,ifeq3(agent(U,Y,Z),true,ifeq3(agent(U,X,Z),true,ifeq3(think_believe_consider(U,Y),true,ifeq3(think_believe_consider(U,X),true,ifeq3(proposition(U,W),true,ifeq3(proposition(U,V),true,V,W),W),W),W),W),W),W),W) = W ).
fof(clause72,conjecture,actual_world(skc14) = true ).
fof(clause73,conjecture,man(skc14,skc27) = true ).
fof(clause74,conjecture,vincent_forename(skc14,skc26) = true ).
fof(clause75,conjecture,forename(skc14,skc26) = true ).
fof(clause76,conjecture,think_believe_consider(skc14,skc25) = true ).
fof(clause77,conjecture,present(skc14,skc25) = true ).
fof(clause78,conjecture,event(skc14,skc25) = true ).
fof(clause79,conjecture,event(skc15,skc22) = true ).
fof(clause80,conjecture,forename(skc14,skc21) = true ).
fof(clause81,conjecture,jules_forename(skc14,skc21) = true ).
fof(clause82,conjecture,man(skc14,skc20) = true ).
fof(clause83,conjecture,present(skc15,skc22) = true ).
fof(clause84,conjecture,smoke(skc15,skc22) = true ).
fof(clause85,conjecture,jules_forename(skc14,skc23) = true ).
fof(clause86,conjecture,forename(skc14,skc23) = true ).
fof(clause87,conjecture,man(skc14,skc18) = true ).
fof(clause88,conjecture,forename(skc14,skc17) = true ).
fof(clause89,conjecture,vincent_forename(skc14,skc17) = true ).
fof(clause90,conjecture,event(skc14,skc16) = true ).
fof(clause91,conjecture,present(skc14,skc16) = true ).
fof(clause92,conjecture,think_believe_consider(skc14,skc16) = true ).
fof(clause93,conjecture,accessible_world(skc14,skc15) = true ).
fof(clause94,conjecture,proposition(skc14,skc15) = true ).
fof(clause95,conjecture,state(skc14,skc19) = true ).
fof(clause96,conjecture,proposition(skc14,skc24) = true ).
fof(clause97,conjecture,accessible_world(skc14,skc24) = true ).
fof(clause98,conjecture,agent(skc14,skc25,skc27) = true ).
fof(clause99,conjecture,of(skc14,skc26,skc27) = true ).
fof(clause100,conjecture,theme(skc14,skc25,skc24) = true ).
fof(clause101,conjecture,of(skc14,skc23,skc20) = true ).
fof(clause102,conjecture,of(skc14,skc21,skc20) = true ).
fof(clause103,conjecture,agent(skc15,skc22,skc20) = true ).
fof(clause104,conjecture,of(skc14,skc17,skc18) = true ).
fof(clause105,conjecture,agent(skc14,skc16,skc18) = true ).
fof(clause106,conjecture,theme(skc14,skc16,skc15) = true ).
fof(clause107,conjecture,be(skc14,skc19,skc20,skc20) = true ).
fof(clause108,conjecture,! [U] : ! [V] : ifeq2(man(skc24,U),true,smoke(skc24,skf1(V)),true) = true ).
fof(clause109,conjecture,! [U] : ! [V] : ifeq2(man(skc24,U),true,present(skc24,skf1(V)),true) = true ).
fof(clause110,conjecture,! [U] : ! [V] : ifeq2(man(skc24,U),true,event(skc24,skf1(V)),true) = true ).
fof(clause111,conjecture,! [U] : ifeq2(man(skc24,U),true,agent(skc24,skf1(U),U),true) = true ).
fof(clause31,conjecture,! [U] : ! [V] : ifeq(tuple(unisex(U,V),male(U,V)),tuple(true,true),a,b) = b ).
fof(clause32,conjecture,! [U] : ! [V] : ifeq(tuple(specific(U,V),general(U,V)),tuple(true,true),a,b) = b ).
fof(clause33,conjecture,! [U] : ! [V] : ifeq(tuple(nonhuman(U,V),human(U,V)),tuple(true,true),a,b) = b ).
fof(clause34,conjecture,! [U] : ! [V] : ifeq(tuple(nonexistent(U,V),existent(U,V)),tuple(true,true),a,b) = b ).
fof(goal,conjecture,a != b ).
