fof(ax1,conjecture,! [U] : ! [V] : ( man(U,V) => male(U,V) ) ).
fof(ax2,conjecture,! [U] : ! [V] : ( man(U,V) => human_person(U,V) ) ).
fof(ax3,conjecture,! [U] : ! [V] : ( vincent_forename(U,V) => forename(U,V) ) ).
fof(ax4,conjecture,! [U] : ! [V] : ( woman(U,V) => female(U,V) ) ).
fof(ax5,conjecture,! [U] : ! [V] : ( human_person(U,V) => animate(U,V) ) ).
fof(ax6,conjecture,! [U] : ! [V] : ( human_person(U,V) => human(U,V) ) ).
fof(ax7,conjecture,! [U] : ! [V] : ( organism(U,V) => living(U,V) ) ).
fof(ax8,conjecture,! [U] : ! [V] : ( organism(U,V) => impartial(U,V) ) ).
fof(ax9,conjecture,! [U] : ! [V] : ( entity(U,V) => existent(U,V) ) ).
fof(ax10,conjecture,! [U] : ! [V] : ( entity(U,V) => specific(U,V) ) ).
fof(ax11,conjecture,! [U] : ! [V] : ( entity(U,V) => thing(U,V) ) ).
fof(ax12,conjecture,! [U] : ! [V] : ( organism(U,V) => entity(U,V) ) ).
fof(ax13,conjecture,! [U] : ! [V] : ( human_person(U,V) => organism(U,V) ) ).
fof(ax14,conjecture,! [U] : ! [V] : ( woman(U,V) => human_person(U,V) ) ).
fof(ax15,conjecture,! [U] : ! [V] : ( mia_forename(U,V) => forename(U,V) ) ).
fof(ax16,conjecture,! [U] : ! [V] : ( relname(U,V) => relation(U,V) ) ).
fof(ax17,conjecture,! [U] : ! [V] : ( forename(U,V) => relname(U,V) ) ).
fof(ax18,conjecture,! [U] : ! [V] : ( abstraction(U,V) => unisex(U,V) ) ).
fof(ax19,conjecture,! [U] : ! [V] : ( abstraction(U,V) => general(U,V) ) ).
fof(ax20,conjecture,! [U] : ! [V] : ( abstraction(U,V) => nonhuman(U,V) ) ).
fof(ax21,conjecture,! [U] : ! [V] : ( abstraction(U,V) => thing(U,V) ) ).
fof(ax22,conjecture,! [U] : ! [V] : ( relation(U,V) => abstraction(U,V) ) ).
fof(ax23,conjecture,! [U] : ! [V] : ( proposition(U,V) => relation(U,V) ) ).
fof(ax24,conjecture,! [U] : ! [V] : ( desire_want(U,V) => event(U,V) ) ).
fof(ax25,conjecture,! [U] : ! [V] : ( eventuality(U,V) => unisex(U,V) ) ).
fof(ax26,conjecture,! [U] : ! [V] : ( eventuality(U,V) => nonexistent(U,V) ) ).
fof(ax27,conjecture,! [U] : ! [V] : ( eventuality(U,V) => specific(U,V) ) ).
fof(ax28,conjecture,! [U] : ! [V] : ( thing(U,V) => singleton(U,V) ) ).
fof(ax29,conjecture,! [U] : ! [V] : ( eventuality(U,V) => thing(U,V) ) ).
fof(ax30,conjecture,! [U] : ! [V] : ( event(U,V) => eventuality(U,V) ) ).
fof(ax31,conjecture,! [U] : ! [V] : ( dance(U,V) => event(U,V) ) ).
fof(ax32,conjecture,! [U] : ! [V] : ( existent(U,V) => ~ nonexistent(U,V) ) ).
fof(ax33,conjecture,! [U] : ! [V] : ( male(U,V) => ~ female(U,V) ) ).
fof(ax34,conjecture,! [U] : ! [V] : ( nonhuman(U,V) => ~ human(U,V) ) ).
fof(ax35,conjecture,! [U] : ! [V] : ( specific(U,V) => ~ general(U,V) ) ).
fof(ax36,conjecture,! [U] : ! [V] : ( unisex(U,V) => ~ female(U,V) ) ).
fof(ax37,conjecture,! [U] : ! [V] : ( unisex(U,V) => ~ male(U,V) ) ).
fof(ax38,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & male(V,U) ) => male(W,U) ) ).
fof(ax39,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & man(V,U) ) => man(W,U) ) ).
fof(ax40,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & vincent_forename(V,U) ) => vincent_forename(W,U) ) ).
fof(ax41,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ( ( accessible_world(W,X) & of(W,U,V) ) => of(X,U,V) ) ).
fof(ax42,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & female(V,U) ) => female(W,U) ) ).
fof(ax43,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & animate(V,U) ) => animate(W,U) ) ).
fof(ax44,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & human(V,U) ) => human(W,U) ) ).
fof(ax45,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & living(V,U) ) => living(W,U) ) ).
fof(ax46,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & impartial(V,U) ) => impartial(W,U) ) ).
fof(ax47,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & existent(V,U) ) => existent(W,U) ) ).
fof(ax48,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & entity(V,U) ) => entity(W,U) ) ).
fof(ax49,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & organism(V,U) ) => organism(W,U) ) ).
fof(ax50,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & human_person(V,U) ) => human_person(W,U) ) ).
fof(ax51,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & woman(V,U) ) => woman(W,U) ) ).
fof(ax52,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & mia_forename(V,U) ) => mia_forename(W,U) ) ).
fof(ax53,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & relname(V,U) ) => relname(W,U) ) ).
fof(ax54,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & forename(V,U) ) => forename(W,U) ) ).
fof(ax55,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & general(V,U) ) => general(W,U) ) ).
fof(ax56,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & nonhuman(V,U) ) => nonhuman(W,U) ) ).
fof(ax57,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & abstraction(V,U) ) => abstraction(W,U) ) ).
fof(ax58,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & relation(V,U) ) => relation(W,U) ) ).
fof(ax59,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & proposition(V,U) ) => proposition(W,U) ) ).
fof(ax60,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ( ( accessible_world(W,X) & theme(W,U,V) ) => theme(X,U,V) ) ).
fof(ax61,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & desire_want(V,U) ) => desire_want(W,U) ) ).
fof(ax62,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ( ( accessible_world(W,X) & agent(W,U,V) ) => agent(X,U,V) ) ).
fof(ax63,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & present(V,U) ) => present(W,U) ) ).
fof(ax64,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & unisex(V,U) ) => unisex(W,U) ) ).
fof(ax65,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & nonexistent(V,U) ) => nonexistent(W,U) ) ).
fof(ax66,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & specific(V,U) ) => specific(W,U) ) ).
fof(ax67,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & singleton(V,U) ) => singleton(W,U) ) ).
fof(ax68,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & thing(V,U) ) => thing(W,U) ) ).
fof(ax69,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & eventuality(V,U) ) => eventuality(W,U) ) ).
fof(ax70,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & event(V,U) ) => event(W,U) ) ).
fof(ax71,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & dance(V,U) ) => dance(W,U) ) ).
fof(ax72,conjecture,! [U] : ! [V] : ! [W] : ( ( entity(U,V) & forename(U,W) & of(U,W,V) ) => ~ ( ? [X] : ( forename(U,X) & X != W & of(U,X,V) ) ) ) ).
fof(ax73,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ! [Y] : ( ( desire_want(U,V) & proposition(U,X) & theme(U,V,X) & desire_want(U,W) & proposition(U,Y) & theme(U,W,Y) ) => X = Y ) ).
fof(co1,conjecture,~(~ ( ? [U] : ( actual_world(U) & ? [V] : ? [W] : ? [X] : ? [Y] : ? [Z] : ? [X1] : ( of(U,W,V) & man(U,V) & vincent_forename(U,W) & forename(U,W) & of(U,Y,X) & woman(U,X) & mia_forename(U,Y) & forename(U,Y) & proposition(U,Z) & present(U,X1) & theme(U,X1,Z) & desire_want(U,X1) & agent(U,X1,X) & accessible_world(U,Z) & ? [X2] : ( event(Z,X2) & agent(Z,X2,X) & present(Z,X2) & dance(Z,X2) ) & ~ ( ? [X3] : ? [X4] : ( proposition(U,X3) & present(U,X4) & theme(U,X4,X3) & desire_want(U,X4) & agent(U,X4,V) & accessible_world(U,X3) & ? [X5] : ( event(X3,X5) & agent(X3,X5,V) & present(X3,X5) & dance(X3,X5) ) ) ) ) ) ) )).
