fof(wajsberg_1,conjecture,! [X] : implies(truth,X) = X ).
fof(wajsberg_2,conjecture,! [X] : ! [Y] : ! [Z] : implies(implies(X,Y),implies(implies(Y,Z),implies(X,Z))) = truth ).
fof(wajsberg_3,conjecture,! [X] : ! [Y] : implies(implies(X,Y),Y) = implies(implies(Y,X),X) ).
fof(wajsberg_4,conjecture,! [X] : ! [Y] : implies(implies(not(X),not(Y)),implies(Y,X)) = truth ).
fof(or_definition,conjecture,! [X] : ! [Y] : or(X,Y) = implies(not(X),Y) ).
fof(or_associativity,conjecture,! [X] : ! [Y] : ! [Z] : or(or(X,Y),Z) = or(X,or(Y,Z)) ).
fof(or_commutativity,conjecture,! [X] : ! [Y] : or(X,Y) = or(Y,X) ).
fof(and_definition,conjecture,! [X] : ! [Y] : and(X,Y) = not(or(not(X),not(Y))) ).
fof(and_associativity,conjecture,! [X] : ! [Y] : ! [Z] : and(and(X,Y),Z) = and(X,and(Y,Z)) ).
fof(and_commutativity,conjecture,! [X] : ! [Y] : and(X,Y) = and(Y,X) ).
