fof(ax1,conjecture,! [U] : ! [V] : ( jules_forename(U,V) => forename(U,V) ) ).
fof(ax2,conjecture,! [U] : ! [V] : ( vincent_forename(U,V) => forename(U,V) ) ).
fof(ax3,conjecture,! [U] : ! [V] : ( relname(U,V) => relation(U,V) ) ).
fof(ax4,conjecture,! [U] : ! [V] : ( forename(U,V) => relname(U,V) ) ).
fof(ax5,conjecture,! [U] : ! [V] : ( man(U,V) => male(U,V) ) ).
fof(ax6,conjecture,! [U] : ! [V] : ( human_person(U,V) => animate(U,V) ) ).
fof(ax7,conjecture,! [U] : ! [V] : ( human_person(U,V) => human(U,V) ) ).
fof(ax8,conjecture,! [U] : ! [V] : ( organism(U,V) => living(U,V) ) ).
fof(ax9,conjecture,! [U] : ! [V] : ( organism(U,V) => impartial(U,V) ) ).
fof(ax10,conjecture,! [U] : ! [V] : ( entity(U,V) => existent(U,V) ) ).
fof(ax11,conjecture,! [U] : ! [V] : ( entity(U,V) => specific(U,V) ) ).
fof(ax12,conjecture,! [U] : ! [V] : ( entity(U,V) => thing(U,V) ) ).
fof(ax13,conjecture,! [U] : ! [V] : ( organism(U,V) => entity(U,V) ) ).
fof(ax14,conjecture,! [U] : ! [V] : ( human_person(U,V) => organism(U,V) ) ).
fof(ax15,conjecture,! [U] : ! [V] : ( man(U,V) => human_person(U,V) ) ).
fof(ax16,conjecture,! [U] : ! [V] : ( state(U,V) => event(U,V) ) ).
fof(ax17,conjecture,! [U] : ! [V] : ( state(U,V) => eventuality(U,V) ) ).
fof(ax18,conjecture,! [U] : ! [V] : ( abstraction(U,V) => unisex(U,V) ) ).
fof(ax19,conjecture,! [U] : ! [V] : ( abstraction(U,V) => general(U,V) ) ).
fof(ax20,conjecture,! [U] : ! [V] : ( abstraction(U,V) => nonhuman(U,V) ) ).
fof(ax21,conjecture,! [U] : ! [V] : ( abstraction(U,V) => thing(U,V) ) ).
fof(ax22,conjecture,! [U] : ! [V] : ( relation(U,V) => abstraction(U,V) ) ).
fof(ax23,conjecture,! [U] : ! [V] : ( proposition(U,V) => relation(U,V) ) ).
fof(ax24,conjecture,! [U] : ! [V] : ( eventuality(U,V) => unisex(U,V) ) ).
fof(ax25,conjecture,! [U] : ! [V] : ( eventuality(U,V) => nonexistent(U,V) ) ).
fof(ax26,conjecture,! [U] : ! [V] : ( eventuality(U,V) => specific(U,V) ) ).
fof(ax27,conjecture,! [U] : ! [V] : ( thing(U,V) => singleton(U,V) ) ).
fof(ax28,conjecture,! [U] : ! [V] : ( eventuality(U,V) => thing(U,V) ) ).
fof(ax29,conjecture,! [U] : ! [V] : ( event(U,V) => eventuality(U,V) ) ).
fof(ax30,conjecture,! [U] : ! [V] : ( smoke(U,V) => event(U,V) ) ).
fof(ax31,conjecture,! [U] : ! [V] : ( existent(U,V) => ~ nonexistent(U,V) ) ).
fof(ax32,conjecture,! [U] : ! [V] : ( nonhuman(U,V) => ~ human(U,V) ) ).
fof(ax33,conjecture,! [U] : ! [V] : ( specific(U,V) => ~ general(U,V) ) ).
fof(ax34,conjecture,! [U] : ! [V] : ( unisex(U,V) => ~ male(U,V) ) ).
fof(ax35,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & jules_forename(V,U) ) => jules_forename(W,U) ) ).
fof(ax36,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ( ( accessible_world(W,X) & of(W,U,V) ) => of(X,U,V) ) ).
fof(ax37,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & vincent_forename(V,U) ) => vincent_forename(W,U) ) ).
fof(ax38,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & relname(V,U) ) => relname(W,U) ) ).
fof(ax39,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & forename(V,U) ) => forename(W,U) ) ).
fof(ax40,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & male(V,U) ) => male(W,U) ) ).
fof(ax41,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & animate(V,U) ) => animate(W,U) ) ).
fof(ax42,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & human(V,U) ) => human(W,U) ) ).
fof(ax43,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & living(V,U) ) => living(W,U) ) ).
fof(ax44,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & impartial(V,U) ) => impartial(W,U) ) ).
fof(ax45,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & existent(V,U) ) => existent(W,U) ) ).
fof(ax46,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & entity(V,U) ) => entity(W,U) ) ).
fof(ax47,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & organism(V,U) ) => organism(W,U) ) ).
fof(ax48,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & human_person(V,U) ) => human_person(W,U) ) ).
fof(ax49,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & man(V,U) ) => man(W,U) ) ).
fof(ax50,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & state(V,U) ) => state(W,U) ) ).
fof(ax51,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ! [Y] : ( ( accessible_world(X,Y) & be(X,U,V,W) ) => be(Y,U,V,W) ) ).
fof(ax52,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & general(V,U) ) => general(W,U) ) ).
fof(ax53,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & nonhuman(V,U) ) => nonhuman(W,U) ) ).
fof(ax54,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & abstraction(V,U) ) => abstraction(W,U) ) ).
fof(ax55,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & relation(V,U) ) => relation(W,U) ) ).
fof(ax56,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & proposition(V,U) ) => proposition(W,U) ) ).
fof(ax57,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ( ( accessible_world(W,X) & theme(W,U,V) ) => theme(X,U,V) ) ).
fof(ax58,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & think_believe_consider(V,U) ) => think_believe_consider(W,U) ) ).
fof(ax59,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ( ( accessible_world(W,X) & agent(W,U,V) ) => agent(X,U,V) ) ).
fof(ax60,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & present(V,U) ) => present(W,U) ) ).
fof(ax61,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & unisex(V,U) ) => unisex(W,U) ) ).
fof(ax62,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & nonexistent(V,U) ) => nonexistent(W,U) ) ).
fof(ax63,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & specific(V,U) ) => specific(W,U) ) ).
fof(ax64,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & singleton(V,U) ) => singleton(W,U) ) ).
fof(ax65,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & thing(V,U) ) => thing(W,U) ) ).
fof(ax66,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & eventuality(V,U) ) => eventuality(W,U) ) ).
fof(ax67,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & event(V,U) ) => event(W,U) ) ).
fof(ax68,conjecture,! [U] : ! [V] : ! [W] : ( ( accessible_world(V,W) & smoke(V,U) ) => smoke(W,U) ) ).
fof(ax69,conjecture,! [U] : ! [V] : ! [W] : ( ( entity(U,V) & forename(U,W) & of(U,W,V) ) => ~ ( ? [X] : ( forename(U,X) & X != W & of(U,X,V) ) ) ) ).
fof(ax70,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ( be(U,V,W,X) => W = X ) ).
fof(ax71,conjecture,! [U] : ! [V] : ! [W] : ! [X] : ! [Y] : ! [Z] : ( ( think_believe_consider(U,V) & proposition(U,Y) & theme(U,V,Y) & agent(U,V,X) & think_believe_consider(U,W) & proposition(U,Z) & theme(U,W,Z) & agent(U,W,X) ) => Y = Z ) ).
fof(co1,conjecture,~(~ ( ? [U] : ( actual_world(U) & ? [V] : ? [W] : ? [X] : ? [Y] : ? [Z] : ? [X1] : ? [X2] : ? [X3] : ? [X4] : ? [X5] : ? [X6] : ? [X7] : ( of(U,W,V) & man(U,V) & vincent_forename(U,W) & forename(U,W) & of(U,X,Y) & jules_forename(U,X) & forename(U,X) & of(U,Z,Y) & man(U,Y) & vincent_forename(U,Z) & forename(U,Z) & proposition(U,X2) & agent(U,X1,Y) & theme(U,X1,X2) & event(U,X1) & present(U,X1) & think_believe_consider(U,X1) & accessible_world(U,X2) & ! [X8] : ( man(X2,X8) => ? [X9] : ( event(X2,X9) & agent(X2,X9,X8) & present(X2,X9) & smoke(X2,X9) ) ) & of(U,X3,X4) & man(U,X4) & jules_forename(U,X3) & forename(U,X3) & man(U,X4) & state(U,X5) & be(U,X5,X4,X4) & proposition(U,X7) & agent(U,X6,V) & theme(U,X6,X7) & event(U,X6) & present(U,X6) & think_believe_consider(U,X6) & accessible_world(U,X7) & ? [X10] : ( event(X7,X10) & agent(X7,X10,Y) & present(X7,X10) & smoke(X7,X10) ) ) ) ) )).
