fof(left_identity,conjecture,! [X] : multiply(identity,X) = X ).
fof(left_inverse,conjecture,! [X] : multiply(inverse(X),X) = identity ).
fof(associativity,conjecture,! [X] : ! [Y] : ! [Z] : multiply(multiply(X,Y),Z) = multiply(X,multiply(Y,Z)) ).
fof(symmetry_of_glb,conjecture,! [X] : ! [Y] : greatest_lower_bound(X,Y) = greatest_lower_bound(Y,X) ).
fof(symmetry_of_lub,conjecture,! [X] : ! [Y] : least_upper_bound(X,Y) = least_upper_bound(Y,X) ).
fof(associativity_of_glb,conjecture,! [X] : ! [Y] : ! [Z] : greatest_lower_bound(X,greatest_lower_bound(Y,Z)) = greatest_lower_bound(greatest_lower_bound(X,Y),Z) ).
fof(associativity_of_lub,conjecture,! [X] : ! [Y] : ! [Z] : least_upper_bound(X,least_upper_bound(Y,Z)) = least_upper_bound(least_upper_bound(X,Y),Z) ).
fof(idempotence_of_lub,conjecture,! [X] : least_upper_bound(X,X) = X ).
fof(idempotence_of_gld,conjecture,! [X] : greatest_lower_bound(X,X) = X ).
fof(lub_absorbtion,conjecture,! [X] : ! [Y] : least_upper_bound(X,greatest_lower_bound(X,Y)) = X ).
fof(glb_absorbtion,conjecture,! [X] : ! [Y] : greatest_lower_bound(X,least_upper_bound(X,Y)) = X ).
fof(monotony_lub1,conjecture,! [X] : ! [Y] : ! [Z] : multiply(X,least_upper_bound(Y,Z)) = least_upper_bound(multiply(X,Y),multiply(X,Z)) ).
fof(monotony_glb1,conjecture,! [X] : ! [Y] : ! [Z] : multiply(X,greatest_lower_bound(Y,Z)) = greatest_lower_bound(multiply(X,Y),multiply(X,Z)) ).
fof(monotony_lub2,conjecture,! [Y] : ! [Z] : ! [X] : multiply(least_upper_bound(Y,Z),X) = least_upper_bound(multiply(Y,X),multiply(Z,X)) ).
fof(monotony_glb2,conjecture,! [Y] : ! [Z] : ! [X] : multiply(greatest_lower_bound(Y,Z),X) = greatest_lower_bound(multiply(Y,X),multiply(Z,X)) ).
