fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq4(A,A,B,C) = B ).
fof(ifeq_axiom_001,conjecture,! [A] : ! [B] : ! [C] : ifeq3(A,A,B,C) = B ).
fof(ifeq_axiom_002,conjecture,! [A] : ! [B] : ! [C] : ifeq2(A,A,B,C) = B ).
fof(ifeq_axiom_003,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(clause1,conjecture,! [U] : ! [V] : ifeq3(order(U,V),true,act(U,V),true) = true ).
fof(clause2,conjecture,! [U] : ! [V] : ifeq3(act(U,V),true,event(U,V),true) = true ).
fof(clause3,conjecture,! [U] : ! [V] : ifeq3(event(U,V),true,eventuality(U,V),true) = true ).
fof(clause4,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,thing(U,V),true) = true ).
fof(clause5,conjecture,! [U] : ! [V] : ifeq3(thing(U,V),true,singleton(U,V),true) = true ).
fof(clause6,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,specific(U,V),true) = true ).
fof(clause7,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,nonexistent(U,V),true) = true ).
fof(clause8,conjecture,! [U] : ! [V] : ifeq3(eventuality(U,V),true,unisex(U,V),true) = true ).
fof(clause9,conjecture,! [U] : ! [V] : ifeq3(order(U,V),true,event(U,V),true) = true ).
fof(clause10,conjecture,! [U] : ! [V] : ifeq3(shake_beverage(U,V),true,beverage(U,V),true) = true ).
fof(clause11,conjecture,! [U] : ! [V] : ifeq3(beverage(U,V),true,food(U,V),true) = true ).
fof(clause12,conjecture,! [U] : ! [V] : ifeq3(food(U,V),true,substance_matter(U,V),true) = true ).
fof(clause13,conjecture,! [U] : ! [V] : ifeq3(substance_matter(U,V),true,object(U,V),true) = true ).
fof(clause14,conjecture,! [U] : ! [V] : ifeq3(object(U,V),true,entity(U,V),true) = true ).
fof(clause15,conjecture,! [U] : ! [V] : ifeq3(entity(U,V),true,thing(U,V),true) = true ).
fof(clause16,conjecture,! [U] : ! [V] : ifeq3(entity(U,V),true,specific(U,V),true) = true ).
fof(clause17,conjecture,! [U] : ! [V] : ifeq3(entity(U,V),true,existent(U,V),true) = true ).
fof(clause18,conjecture,! [U] : ! [V] : ifeq3(object(U,V),true,nonliving(U,V),true) = true ).
fof(clause19,conjecture,! [U] : ! [V] : ifeq3(object(U,V),true,impartial(U,V),true) = true ).
fof(clause20,conjecture,! [U] : ! [V] : ifeq3(object(U,V),true,unisex(U,V),true) = true ).
fof(clause21,conjecture,! [U] : ! [V] : ifeq3(forename(U,V),true,relname(U,V),true) = true ).
fof(clause22,conjecture,! [U] : ! [V] : ifeq3(relname(U,V),true,relation(U,V),true) = true ).
fof(clause23,conjecture,! [U] : ! [V] : ifeq3(relation(U,V),true,abstraction(U,V),true) = true ).
fof(clause24,conjecture,! [U] : ! [V] : ifeq3(abstraction(U,V),true,thing(U,V),true) = true ).
fof(clause25,conjecture,! [U] : ! [V] : ifeq3(abstraction(U,V),true,nonhuman(U,V),true) = true ).
fof(clause26,conjecture,! [U] : ! [V] : ifeq3(abstraction(U,V),true,general(U,V),true) = true ).
fof(clause27,conjecture,! [U] : ! [V] : ifeq3(abstraction(U,V),true,unisex(U,V),true) = true ).
fof(clause28,conjecture,! [U] : ! [V] : ifeq3(mia_forename(U,V),true,forename(U,V),true) = true ).
fof(clause29,conjecture,! [U] : ! [V] : ifeq3(woman(U,V),true,human_person(U,V),true) = true ).
fof(clause30,conjecture,! [U] : ! [V] : ifeq3(human_person(U,V),true,organism(U,V),true) = true ).
fof(clause31,conjecture,! [U] : ! [V] : ifeq3(organism(U,V),true,entity(U,V),true) = true ).
fof(clause32,conjecture,! [U] : ! [V] : ifeq3(organism(U,V),true,impartial(U,V),true) = true ).
fof(clause33,conjecture,! [U] : ! [V] : ifeq3(organism(U,V),true,living(U,V),true) = true ).
fof(clause34,conjecture,! [U] : ! [V] : ifeq3(human_person(U,V),true,human(U,V),true) = true ).
fof(clause35,conjecture,! [U] : ! [V] : ifeq3(human_person(U,V),true,animate(U,V),true) = true ).
fof(clause36,conjecture,! [U] : ! [V] : ifeq3(woman(U,V),true,female(U,V),true) = true ).
fof(clause44,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq4(of(U,W,X),true,ifeq4(of(U,V,X),true,ifeq4(forename(U,W),true,ifeq4(forename(U,V),true,ifeq4(entity(U,X),true,W,V),V),V),V),V) = V ).
fof(clause45,conjecture,actual_world(skc5) = true ).
fof(clause46,conjecture,woman(skc5,skc9) = true ).
fof(clause47,conjecture,shake_beverage(skc5,skc7) = true ).
fof(clause48,conjecture,order(skc5,skc6) = true ).
fof(clause49,conjecture,nonreflexive(skc5,skc6) = true ).
fof(clause50,conjecture,past(skc5,skc6) = true ).
fof(clause51,conjecture,event(skc5,skc6) = true ).
fof(clause52,conjecture,forename(skc5,skc8) = true ).
fof(clause53,conjecture,mia_forename(skc5,skc8) = true ).
fof(clause54,conjecture,of(skc5,skc8,skc9) = true ).
fof(clause55,conjecture,agent(skc5,skc6,skc9) = true ).
fof(clause56,conjecture,patient(skc5,skc6,skc7) = true ).
fof(clause37,conjecture,! [U] : ! [V] : ifeq2(tuple2(unisex(U,V),female(U,V)),tuple2(true,true),a,b) = b ).
fof(clause38,conjecture,! [U] : ! [V] : ifeq2(tuple2(specific(U,V),general(U,V)),tuple2(true,true),a,b) = b ).
fof(clause39,conjecture,! [U] : ! [V] : ifeq2(tuple2(nonliving(U,V),living(U,V)),tuple2(true,true),a,b) = b ).
fof(clause40,conjecture,! [U] : ! [V] : ifeq2(tuple2(nonhuman(U,V),human(U,V)),tuple2(true,true),a,b) = b ).
fof(clause41,conjecture,! [U] : ! [V] : ifeq2(tuple2(nonexistent(U,V),existent(U,V)),tuple2(true,true),a,b) = b ).
fof(clause42,conjecture,! [U] : ! [V] : ifeq2(tuple2(nonliving(U,V),animate(U,V)),tuple2(true,true),a,b) = b ).
fof(clause43,conjecture,! [U] : ! [V] : ! [W] : ifeq(tuple(patient(U,V,W),nonreflexive(U,V),agent(U,V,W)),tuple(true,true,true),a,b) = b ).
fof(goal,conjecture,a != b ).
