fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq2(A,A,B,C) = B ).
fof(ifeq_axiom_001,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(cls_val_Osimps_I3_J_0,conjecture,! [V_nat] : ! [V_nat_H] : ifeq2(c_Value_Oval_OAddr(V_nat),c_Value_Oval_OAddr(V_nat_H),V_nat,V_nat_H) = V_nat_H ).
fof(cls_val_Osimps_I2_J_0,conjecture,! [V_int] : ! [V_int_H] : ifeq2(c_Value_Oval_OIntg(V_int),c_Value_Oval_OIntg(V_int_H),V_int,V_int_H) = V_int_H ).
fof(cls_CHAINED_0,conjecture,c_WellTypeRT_OWTrt(v_P,v_ha____,v_E____,c_Expr_Oexp_OVal(v_v____,tc_List_Olist(tc_String_Ochar)),c_Type_Oty_ONT) = true ).
fof(cls_val_Osimps_I10_J_0,conjecture,! [V_nat_H] : ifeq(c_Value_Oval_OUnit,c_Value_Oval_OAddr(V_nat_H),a,b) = b ).
fof(cls_val_Osimps_I22_J_0,conjecture,! [V_int] : ! [V_nat_H] : ifeq(c_Value_Oval_OIntg(V_int),c_Value_Oval_OAddr(V_nat_H),a,b) = b ).
fof(cls_val_Osimps_I23_J_0,conjecture,! [V_nat_H] : ! [V_int] : ifeq(c_Value_Oval_OAddr(V_nat_H),c_Value_Oval_OIntg(V_int),a,b) = b ).
fof(cls_val_Osimps_I11_J_0,conjecture,! [V_nat_H] : ifeq(c_Value_Oval_OAddr(V_nat_H),c_Value_Oval_OUnit,a,b) = b ).
fof(cls_val_Osimps_I8_J_0,conjecture,! [V_int_H] : ifeq(c_Value_Oval_OUnit,c_Value_Oval_OIntg(V_int_H),a,b) = b ).
fof(cls_val_Osimps_I9_J_0,conjecture,! [V_int_H] : ifeq(c_Value_Oval_OIntg(V_int_H),c_Value_Oval_OUnit,a,b) = b ).
fof(cls_val_Osimps_I5_J_0,conjecture,ifeq(c_Value_Oval_ONull,c_Value_Oval_OUnit,a,b) = b ).
fof(cls_val_Osimps_I15_J_0,conjecture,! [V_int_H] : ifeq(c_Value_Oval_OIntg(V_int_H),c_Value_Oval_ONull,a,b) = b ).
fof(cls_val_Osimps_I4_J_0,conjecture,ifeq(c_Value_Oval_OUnit,c_Value_Oval_ONull,a,b) = b ).
fof(cls_val_Osimps_I14_J_0,conjecture,! [V_int_H] : ifeq(c_Value_Oval_ONull,c_Value_Oval_OIntg(V_int_H),a,b) = b ).
fof(cls_val_Osimps_I17_J_0,conjecture,! [V_nat_H] : ifeq(c_Value_Oval_OAddr(V_nat_H),c_Value_Oval_ONull,a,b) = b ).
fof(cls_val_Osimps_I16_J_0,conjecture,! [V_nat_H] : ifeq(c_Value_Oval_ONull,c_Value_Oval_OAddr(V_nat_H),a,b) = b ).
fof(cls_conjecture_0,conjecture,ifeq(v_v____,c_Value_Oval_ONull,a,b) = b ).
fof(goal,conjecture,a != b ).
