fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq3(A,A,B,C) = B ).
fof(ifeq_axiom_001,conjecture,! [A] : ! [B] : ! [C] : ifeq2(A,A,B,C) = B ).
fof(ifeq_axiom_002,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(clause1,conjecture,! [U] : ! [V] : event(skf1(U,V)) = true ).
fof(clause2,conjecture,! [U] : ifeq2(nonhuman(U),true,entity(U),true) = true ).
fof(clause3,conjecture,! [U] : ifeq2(drs(U),true,proposition(U),true) = true ).
fof(clause4,conjecture,! [U] : ifeq2(proposition(U),true,drs(U),true) = true ).
fof(clause5,conjecture,! [U] : ifeq2(woman(U),true,female(U),true) = true ).
fof(clause6,conjecture,! [U] : ifeq2(female(U),true,human(U),true) = true ).
fof(clause7,conjecture,! [U] : ifeq2(male(U),true,human(U),true) = true ).
fof(clause8,conjecture,! [U] : ifeq2(man(U),true,male(U),true) = true ).
fof(clause9,conjecture,! [U] : ifeq2(object(U),true,entity(U),true) = true ).
fof(clause10,conjecture,! [U] : ifeq2(location(U),true,object(U),true) = true ).
fof(clause11,conjecture,! [U] : ifeq2(city(U),true,location(U),true) = true ).
fof(clause12,conjecture,! [U] : ifeq2(hollywood(U),true,city(U),true) = true ).
fof(clause13,conjecture,! [U] : ifeq2(event(U),true,eventuality(U),true) = true ).
fof(clause14,conjecture,! [U] : ifeq2(artifact(U),true,object(U),true) = true ).
fof(clause15,conjecture,! [U] : ifeq2(way(U),true,artifact(U),true) = true ).
fof(clause16,conjecture,! [U] : ifeq2(street(U),true,way(U),true) = true ).
fof(clause17,conjecture,! [U] : ifeq2(instrumentality(U),true,artifact(U),true) = true ).
fof(clause18,conjecture,! [U] : ifeq2(transport(U),true,instrumentality(U),true) = true ).
fof(clause19,conjecture,! [U] : ifeq2(vehicle(U),true,transport(U),true) = true ).
fof(clause20,conjecture,! [U] : ifeq2(car(U),true,vehicle(U),true) = true ).
fof(clause21,conjecture,! [U] : ifeq2(chevy(U),true,car(U),true) = true ).
fof(clause31,conjecture,! [U] : ! [V] : ifeq2(of(U,V),true,ifeq2(owner(U),true,human(U),true),true) = true ).
fof(clause32,conjecture,! [U] : ! [V] : ifeq2(of(U,V),true,have(skf1(U,V),V,U),true) = true ).
fof(clause33,conjecture,! [V] : ! [U] : ! [W] : ifeq2(have(V,U,W),true,ifeq2(human(U),true,owner(U),true),true) = true ).
fof(clause34,conjecture,! [U] : ! [W] : ! [V] : ifeq3(partof(U,W),true,ifeq3(partof(U,V),true,W,V),V) = V ).
fof(clause35,conjecture,! [U] : ! [V] : ! [W] : ifeq2(have(U,V,W),true,ifeq2(event(U),true,of(V,W),true),true) = true ).
fof(clause36,conjecture,! [V] : ! [U] : ! [W] : ifeq2(have(V,U,W),true,ifeq2(human(U),true,of(U,W),true),true) = true ).
fof(clause37,conjecture,! [U] : ! [V] : ! [W] : ifeq2(of(U,V),true,ifeq2(owner(U),true,have(W,U,V),true),true) = true ).
fof(clause38,conjecture,! [W] : ! [V] : ! [U] : ifeq2(have(W,V,U),true,ifeq2(nonhuman(V),true,ifeq2(nonhuman(U),true,partof(U,V),true),true),true) = true ).
fof(clause39,conjecture,hollywood(skc7) = true ).
fof(clause40,conjecture,city(skc7) = true ).
fof(clause41,conjecture,event(skc6) = true ).
fof(clause42,conjecture,chevy(skc5) = true ).
fof(clause43,conjecture,car(skc5) = true ).
fof(clause44,conjecture,white(skc5) = true ).
fof(clause45,conjecture,dirty(skc5) = true ).
fof(clause46,conjecture,old(skc5) = true ).
fof(clause47,conjecture,lonely(skc4) = true ).
fof(clause48,conjecture,way(skc4) = true ).
fof(clause49,conjecture,street(skc4) = true ).
fof(clause50,conjecture,in(skc6,skc7) = true ).
fof(clause51,conjecture,down(skc6,skc4) = true ).
fof(clause52,conjecture,barrel(skc6,skc5) = true ).
fof(clause22,conjecture,! [U] : ifeq(tuple(nonhuman(U),human(U)),tuple(true,true),a,b) = b ).
fof(clause23,conjecture,! [U] : ifeq(tuple(woman(U),man(U)),tuple(true,true),a,b) = b ).
fof(clause24,conjecture,! [U] : ifeq(tuple(female(U),male(U)),tuple(true,true),a,b) = b ).
fof(clause25,conjecture,! [U] : ifeq(tuple(eventuality(U),abstraction(U)),tuple(true,true),a,b) = b ).
fof(clause26,conjecture,! [U] : ifeq(tuple(entity(U),abstraction(U)),tuple(true,true),a,b) = b ).
fof(clause27,conjecture,! [U] : ifeq(tuple(entity(U),eventuality(U)),tuple(true,true),a,b) = b ).
fof(clause28,conjecture,! [U] : ifeq(tuple(old(U),new(U)),tuple(true,true),a,b) = b ).
fof(clause29,conjecture,! [U] : ifeq(tuple(location(U),artifact(U)),tuple(true,true),a,b) = b ).
fof(clause30,conjecture,! [U] : ifeq(tuple(way(U),instrumentality(U)),tuple(true,true),a,b) = b ).
fof(goal,conjecture,a != b ).
