include('Saturations/SWB014-10/Saturations/E-SAT---3.0.ax').
fof(testcase_premise_fullish_014_Harry_belongs_to_some_Species_5,conjecture,iext(uri_rdf_rest,sK3_testcase_premise_fullish_014_Harry_belongs_to_some_Species_BNODE_l1,sK1_testcase_premise_fullish_014_Harry_belongs_to_some_Species_BNODE_l2) = true ).
