include('Saturations/SWB028-10/Saturations/E-SAT---3.0.ax').
fof(testcase_premise_fullish_028_Inferred_Property_Characteristics_III_1,conjecture,iext(uri_owl_equivalentClass,uri_ex_InversesOfFunctionalProperties,sK1_testcase_premise_fullish_028_Inferred_Property_Characteristics_III_BNODE_z) = true ).
