fof(ifeq_axiom,conjecture,! [A] : ! [B] : ! [C] : ifeq3(A,A,B,C) = B ).
fof(ifeq_axiom_001,conjecture,! [A] : ! [B] : ! [C] : ifeq2(A,A,B,C) = B ).
fof(ifeq_axiom_002,conjecture,! [A] : ! [B] : ! [C] : ifeq(A,A,B,C) = B ).
fof(clause1,conjecture,! [U] : ! [V] : ifeq2(smoke(U,V),true,event(U,V),true) = true ).
fof(clause2,conjecture,! [U] : ! [V] : ifeq2(event(U,V),true,eventuality(U,V),true) = true ).
fof(clause3,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,thing(U,V),true) = true ).
fof(clause4,conjecture,! [U] : ! [V] : ifeq2(thing(U,V),true,singleton(U,V),true) = true ).
fof(clause5,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,specific(U,V),true) = true ).
fof(clause6,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,nonexistent(U,V),true) = true ).
fof(clause7,conjecture,! [U] : ! [V] : ifeq2(eventuality(U,V),true,unisex(U,V),true) = true ).
fof(clause8,conjecture,! [U] : ! [V] : ifeq2(man(U,V),true,human_person(U,V),true) = true ).
fof(clause9,conjecture,! [U] : ! [V] : ifeq2(human_person(U,V),true,organism(U,V),true) = true ).
fof(clause10,conjecture,! [U] : ! [V] : ifeq2(organism(U,V),true,entity(U,V),true) = true ).
fof(clause11,conjecture,! [U] : ! [V] : ifeq2(entity(U,V),true,thing(U,V),true) = true ).
fof(clause12,conjecture,! [U] : ! [V] : ifeq2(entity(U,V),true,specific(U,V),true) = true ).
fof(clause13,conjecture,! [U] : ! [V] : ifeq2(entity(U,V),true,existent(U,V),true) = true ).
fof(clause14,conjecture,! [U] : ! [V] : ifeq2(organism(U,V),true,impartial(U,V),true) = true ).
fof(clause15,conjecture,! [U] : ! [V] : ifeq2(organism(U,V),true,living(U,V),true) = true ).
fof(clause16,conjecture,! [U] : ! [V] : ifeq2(human_person(U,V),true,human(U,V),true) = true ).
fof(clause17,conjecture,! [U] : ! [V] : ifeq2(human_person(U,V),true,animate(U,V),true) = true ).
fof(clause18,conjecture,! [U] : ! [V] : ifeq2(man(U,V),true,male(U,V),true) = true ).
fof(clause19,conjecture,! [U] : ! [V] : ifeq2(proposition(U,V),true,relation(U,V),true) = true ).
fof(clause20,conjecture,! [U] : ! [V] : ifeq2(relation(U,V),true,abstraction(U,V),true) = true ).
fof(clause21,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,thing(U,V),true) = true ).
fof(clause22,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,nonhuman(U,V),true) = true ).
fof(clause23,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,general(U,V),true) = true ).
fof(clause24,conjecture,! [U] : ! [V] : ifeq2(abstraction(U,V),true,unisex(U,V),true) = true ).
fof(clause25,conjecture,! [U] : ! [V] : ifeq2(forename(U,V),true,relname(U,V),true) = true ).
fof(clause26,conjecture,! [U] : ! [V] : ifeq2(relname(U,V),true,relation(U,V),true) = true ).
fof(clause27,conjecture,! [U] : ! [V] : ifeq2(vincent_forename(U,V),true,forename(U,V),true) = true ).
fof(clause32,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(smoke(U,W),true,smoke(V,W),true),true) = true ).
fof(clause33,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(event(U,W),true,event(V,W),true),true) = true ).
fof(clause34,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(eventuality(U,W),true,eventuality(V,W),true),true) = true ).
fof(clause35,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(thing(U,W),true,thing(V,W),true),true) = true ).
fof(clause36,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(singleton(U,W),true,singleton(V,W),true),true) = true ).
fof(clause37,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(specific(U,W),true,specific(V,W),true),true) = true ).
fof(clause38,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(nonexistent(U,W),true,nonexistent(V,W),true),true) = true ).
fof(clause39,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(unisex(U,W),true,unisex(V,W),true),true) = true ).
fof(clause40,conjecture,! [U] : ! [W] : ! [V] : ifeq2(present(U,W),true,ifeq2(accessible_world(U,V),true,present(V,W),true),true) = true ).
fof(clause41,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(man(U,W),true,man(V,W),true),true) = true ).
fof(clause42,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(human_person(U,W),true,human_person(V,W),true),true) = true ).
fof(clause43,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(organism(U,W),true,organism(V,W),true),true) = true ).
fof(clause44,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(entity(U,W),true,entity(V,W),true),true) = true ).
fof(clause45,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(existent(U,W),true,existent(V,W),true),true) = true ).
fof(clause46,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(impartial(U,W),true,impartial(V,W),true),true) = true ).
fof(clause47,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(living(U,W),true,living(V,W),true),true) = true ).
fof(clause48,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(human(U,W),true,human(V,W),true),true) = true ).
fof(clause49,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(animate(U,W),true,animate(V,W),true),true) = true ).
fof(clause50,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(male(U,W),true,male(V,W),true),true) = true ).
fof(clause51,conjecture,! [U] : ! [W] : ! [V] : ifeq2(think_believe_consider(U,W),true,ifeq2(accessible_world(U,V),true,think_believe_consider(V,W),true),true) = true ).
fof(clause52,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(proposition(U,W),true,proposition(V,W),true),true) = true ).
fof(clause53,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(relation(U,W),true,relation(V,W),true),true) = true ).
fof(clause54,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(abstraction(U,W),true,abstraction(V,W),true),true) = true ).
fof(clause55,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(nonhuman(U,W),true,nonhuman(V,W),true),true) = true ).
fof(clause56,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(general(U,W),true,general(V,W),true),true) = true ).
fof(clause57,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(forename(U,W),true,forename(V,W),true),true) = true ).
fof(clause58,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(relname(U,W),true,relname(V,W),true),true) = true ).
fof(clause59,conjecture,! [U] : ! [V] : ! [W] : ifeq2(accessible_world(U,V),true,ifeq2(vincent_forename(U,W),true,vincent_forename(V,W),true),true) = true ).
fof(clause60,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq2(agent(U,W,X),true,ifeq2(accessible_world(U,V),true,agent(V,W,X),true),true) = true ).
fof(clause61,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq2(theme(U,W,X),true,ifeq2(accessible_world(U,V),true,theme(V,W,X),true),true) = true ).
fof(clause62,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq2(of(U,W,X),true,ifeq2(accessible_world(U,V),true,of(V,W,X),true),true) = true ).
fof(clause63,conjecture,! [U] : ! [W] : ! [X] : ! [V] : ifeq3(of(U,W,X),true,ifeq3(of(U,V,X),true,ifeq3(forename(U,W),true,ifeq3(forename(U,V),true,ifeq3(entity(U,X),true,W,V),V),V),V),V) = V ).
fof(clause64,conjecture,! [U] : ! [Y] : ! [W] : ! [X] : ! [V] : ! [Z] : ifeq3(theme(U,Y,W),true,ifeq3(theme(U,X,V),true,ifeq3(agent(U,Y,Z),true,ifeq3(agent(U,X,Z),true,ifeq3(think_believe_consider(U,Y),true,ifeq3(think_believe_consider(U,X),true,ifeq3(proposition(U,W),true,ifeq3(proposition(U,V),true,V,W),W),W),W),W),W),W),W) = W ).
fof(clause65,conjecture,actual_world(skc5) = true ).
fof(clause66,conjecture,man(skc5,skc9) = true ).
fof(clause67,conjecture,forename(skc5,skc8) = true ).
fof(clause68,conjecture,vincent_forename(skc5,skc8) = true ).
fof(clause69,conjecture,event(skc5,skc7) = true ).
fof(clause70,conjecture,present(skc5,skc7) = true ).
fof(clause71,conjecture,think_believe_consider(skc5,skc7) = true ).
fof(clause72,conjecture,accessible_world(skc5,skc6) = true ).
fof(clause73,conjecture,proposition(skc5,skc6) = true ).
fof(clause74,conjecture,of(skc5,skc8,skc9) = true ).
fof(clause75,conjecture,agent(skc5,skc7,skc9) = true ).
fof(clause76,conjecture,theme(skc5,skc7,skc6) = true ).
fof(clause77,conjecture,! [U] : ! [V] : ifeq2(man(skc6,U),true,smoke(skc6,skf1(V)),true) = true ).
fof(clause78,conjecture,! [U] : ! [V] : ifeq2(man(skc6,U),true,present(skc6,skf1(V)),true) = true ).
fof(clause79,conjecture,! [U] : ! [V] : ifeq2(man(skc6,U),true,event(skc6,skf1(V)),true) = true ).
fof(clause80,conjecture,! [U] : ifeq2(man(skc6,U),true,agent(skc6,skf1(U),U),true) = true ).
fof(clause28,conjecture,! [U] : ! [V] : ifeq(tuple(unisex(U,V),male(U,V)),tuple(true,true),a,b) = b ).
fof(clause29,conjecture,! [U] : ! [V] : ifeq(tuple(specific(U,V),general(U,V)),tuple(true,true),a,b) = b ).
fof(clause30,conjecture,! [U] : ! [V] : ifeq(tuple(human(U,V),nonhuman(U,V)),tuple(true,true),a,b) = b ).
fof(clause31,conjecture,! [U] : ! [V] : ifeq(tuple(nonexistent(U,V),existent(U,V)),tuple(true,true),a,b) = b ).
fof(goal,conjecture,a != b ).
